// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

namespace ToolUp.Platform

open System

// ─── Data Subject Request public types ───────────────────────────────
//
// GDPR Article 15 (export) + Article 17 (erasure) + Article 16
// (rectification, future) shared types. Lives in Core so client-tier
// admin UI (DataSubjectRequestAdminUI, follow-up) and server-tier
// orchestrator (ErasurePipeline) reference one type module.
//
// The platform's persistence model — versioned IDataObjectStore,
// append-only IEventStore, lineage links — was designed for
// "what happened" requirements. The same design fights "make this
// person disappear" requirements. ErasurePolicy is the explicit
// per-deployment choice between competing compliance regimes; the
// SDK provides the tools, the deploying organisation chooses the
// policy and accepts liability for the choice.

/// Stable correlation id for a data-subject request. Generated by
/// the API handler at request creation; flows through audit emission
/// and the orchestrator's per-step status records.
type DataSubjectRequestId = string

/// Kind of request. `Rectify` is reserved for a future phase — the
/// MVP ships `Export` + `Erase` only; the DU includes the third case
/// up front so callers can pattern-match exhaustively without future
/// breakage.
[<RequireQualifiedAccess>]
type DataSubjectRequestKind =
    /// GDPR Article 15 — copy of every record naming the subject.
    | Export
    /// GDPR Article 17 — erase-or-tombstone every record naming the
    /// subject per the deployment's `ErasurePolicy`.
    | Erase
    /// Reserved for future "right to rectification" workflow. Returns
    /// `NotImplemented` from the MVP handler.
    | Rectify

/// How erasure interacts with persistence. The deploying organisation
/// chooses one policy at compose time per legal review; the SDK
/// applies it uniformly across every store the orchestrator covers.
[<RequireQualifiedAccess>]
type ErasurePolicy =
    /// Every store removes the row entirely. Breaks event-log
    /// integrity for the subject — only valid for deployments
    /// without compliance-driven retention requirements (typically
    /// dev or trial-account workflows under
    /// `AuthenticatedEphemeral`).
    | HardDelete
    /// Replace user-identifying fields with `*ERASED*` markers but
    /// preserve shape and version chain. Retains lineage / audit
    /// integrity at the cost of "we know we erased something." The
    /// middle-ground default — fits most GDPR / CCPA / DPDPA
    /// regimes where audit retention is bounded but the deletion
    /// itself must be discoverable.
    | Tombstone
    /// No erasure of audit/event records; only redact user-
    /// identifying content fields where possible. For jurisdictions
    /// where audit retention legally overrides erasure requests
    /// (e.g. financial-services SR 11-7 audit obligations).
    | RetainPerCompliance

/// Configuration carried by `DataSubjectRequestMode.Enabled`. Holds the
/// deployment's default `ErasurePolicy` plus the Phase 9h.A `Async`
/// switch.
type DataSubjectRequestConfig = {
    /// Default erasure policy for requests that don't override it.
    Policy: ErasurePolicy
    /// Phase 9h.A — when `true`, `RequestExportAsync` runs the export on
    /// `IJobScheduler` via `IBackgroundExportStore` (ticket + poll +
    /// download) instead of synchronously on the HTTP request thread.
    /// Large-tenant Article 15 exports (gigabytes across KB + RAG +
    /// EventStore + …) need this to avoid HTTP-timeout failures. The
    /// synchronous `RequestExport` path is always available; this only
    /// adds the async surface. Default `false` preserves the Phase 9h
    /// MVP behaviour byte-for-byte (GP 11).
    Async: bool
}

module DataSubjectRequestConfig =
    /// Synchronous (Phase 9h MVP) configuration for `policy` —
    /// `Async = false`. The ergonomic default when a deployment only
    /// needs the on-thread `RequestExport`.
    let sync (policy: ErasurePolicy) : DataSubjectRequestConfig = { Policy = policy; Async = false }

    /// Background-job configuration for `policy` — `Async = true`. Pairs
    /// with `JobScheduler = InProcessJobScheduler` (or a distributed
    /// scheduler companion); a `Disabled` scheduler falls back to the
    /// synchronous path with a compose-time warning.
    let background (policy: ErasurePolicy) : DataSubjectRequestConfig = { Policy = policy; Async = true }

/// Per-deployment opt-in for the data-subject-request substrate.
/// Defaults to `Disabled` — apps that don't need DSR endpoints pay
/// nothing (no admin module auto-injection, no API endpoint
/// registration).
[<RequireQualifiedAccess>]
type DataSubjectRequestMode =
    | Disabled
    | Enabled of config: DataSubjectRequestConfig

// ─── Phase 9h.A — background-export ticket + status (moved to Core) ───
//
// `ExportTicket` + `ExportStatus` live in Core (not the server-side
// `IBackgroundExportStore.fs`) so the `IDataSubjectRequestApi` contract —
// which crosses the Fable client/server boundary — can name them. The
// server `IBackgroundExportStore` interface references the same types.

/// Opaque, value-typed handle for a background export. Encodes the scope
/// it belongs to so every store method needs only the ticket (no
/// out-of-band scope threading). Treat as opaque — construct only via
/// `IBackgroundExportStore.BeginExport`.
type ExportTicket = string

/// Lifecycle status of a background export ticket.
///
/// `[<RequireQualifiedAccess>]` because the case names (`Failed`,
/// `Cancelled`, `Expired`, `Ready`, `Unknown`, `Preparing`) are generic
/// enough to collide with other DUs in the widely-opened `ToolUp.Platform`
/// namespace (`SignedUrlError.Expired`, `JobStatus<'T>.Failed`/`.Cancelled`,
/// …). Qualified access keeps the cases out of unqualified scope so an
/// `open ToolUp.Platform` elsewhere can't have its own `Expired`/`Failed`
/// silently shadowed.
[<RequireQualifiedAccess>]
type ExportStatus =
    /// The envelope is being assembled by the background job.
    | Preparing
    /// The envelope is assembled and downloadable; `sizeBytes` is its
    /// length.
    | Ready of sizeBytes: int64
    /// The export job failed terminally; `reason` is operator-readable.
    | Failed of reason: string
    /// The ticket was cancelled mid-run (`IJobScheduler.Cancel`).
    | Cancelled
    /// The ticket outlived its TTL; the envelope has been (or will be)
    /// garbage-collected and is no longer downloadable.
    | Expired
    /// No ticket with this id exists (never issued, or GC'd past TTL).
    | Unknown

module ExportStatus =
    /// Stable case-name string for status sidecar persistence + audit.
    let name =
        function
        | ExportStatus.Preparing -> "Preparing"
        | ExportStatus.Ready _ -> "Ready"
        | ExportStatus.Failed _ -> "Failed"
        | ExportStatus.Cancelled -> "Cancelled"
        | ExportStatus.Expired -> "Expired"
        | ExportStatus.Unknown -> "Unknown"

/// One data-subject request. Created by an admin via the API
/// handler; persisted as an audit event before any work begins
/// (so a crash mid-pipeline still leaves a discoverable record of
/// what was attempted).
type DataSubjectRequest = {
    Id: DataSubjectRequestId
    Kind: DataSubjectRequestKind
    /// Subject of the request. Identifies the user across every
    /// store via their `userId` (the same identifier
    /// `IAuthProvider` resolves; the same one stored on
    /// `AuthenticatedUser.UserId`).
    SubjectUserId: string
    /// Optional team-scope. When `Some`, the orchestrator restricts
    /// every store query to that team's scope — useful for tenant-
    /// scoped requests where a user is a member of multiple teams
    /// and only one team's data is in scope.
    TeamId: string option
    /// Admin actor who initiated the request. Audit attribution.
    RequestedBy: string
    RequestedAt: DateTimeOffset
    /// Free-text rationale that lands in audit. Compliance review
    /// often requires this — the operator records the customer's
    /// supporting documentation reference, the ticket id, the
    /// regulator inquiry case number, etc.
    Reason: string
    /// Policy applied for this request. Inherits the deployment's
    /// `DataSubjectRequestMode.Enabled` policy by default; the API
    /// allows per-request override for cases where a deployment
    /// runs `Tombstone` by default but a specific request demands
    /// `HardDelete` (e.g. a verified GDPR Article 17 demand from a
    /// EEA-resident subject without legitimate-interest grounds).
    Policy: ErasurePolicy
}

/// Per-store outcome from one Erase invocation. Each contributing
/// store's `IErasureHandler.Erase` returns one of these; the
/// orchestrator aggregates them into the run summary.
type ErasureSummary = {
    /// Stable name of the contributing handler — appears in audit
    /// + admin UI.
    HandlerName: string
    /// Number of records the handler counted as affected. The exact
    /// meaning depends on the policy: for `HardDelete` it's
    /// records-removed; for `Tombstone` it's records-redacted; for
    /// `RetainPerCompliance` it's records-content-redacted-only.
    RecordsAffected: int
    /// Optional human-readable note (e.g. "skipped — no
    /// user-identifying fields", "blob prefix `data/users/u1/*`
    /// removed"). Surfaces in audit + admin UI.
    Note: string option
}

/// Failure modes for an Erase or Export step. Distinguishes
/// "couldn't reach the store" from "store reachable but refused".
type ErasureError =
    /// The handler crashed or the underlying store was unreachable.
    /// Retried by the orchestrator's IJobScheduler binding.
    | StoreUnreachable of handlerName: string * detail: string
    /// The handler refused the request (e.g.
    /// `RetainPerCompliance` policy on an audit store; the legal
    /// retention rule blocks the erase). Not retried; the run
    /// records the refusal and continues with other stores.
    | HandlerRefused of handlerName: string * reason: string
    /// The handler partially succeeded then failed mid-way. The
    /// summary captures what was completed; the orchestrator marks
    /// the run as `PartialFailure` and admin can resume.
    | HandlerPartialFailure of handlerName: string * partial: ErasureSummary * detail: string

module ErasureError =
    let toMessage =
        function
        | StoreUnreachable(h, d) -> $"{h} unreachable: {d}"
        | HandlerRefused(h, r) -> $"{h} refused: {r}"
        | HandlerPartialFailure(h, _, d) -> $"{h} partial failure: {d}"

/// One segment of an export. The orchestrator concatenates segments
/// (alphabetically by handler name for deterministic byte output)
/// into the streamed zip / tar response.
type ExportSegment = {
    /// Stable name — becomes the file path inside the export
    /// archive (e.g. `entities/team-abc.json`). Alphabetical
    /// ordering on this field gives deterministic export bytes
    /// across runs.
    Name: string
    /// MIME type — the archive's manifest carries this for clients
    /// that want to interpret each segment.
    MimeType: string
    /// Segment bytes. JSON dumps from typed stores; raw bytes from
    /// IBlobStorage; arbitrary file shapes from KB-style segments.
    Body: byte[]
}

/// Shared erasure helpers reused by every per-store erasure surface
/// (`IEventStore.Erase`, `IDataObjectStore.Erase`, …). Kept here in
/// Core so each store's `Tombstone` redaction writes the same
/// discoverable sentinel without re-declaring it per store.
[<RequireQualifiedAccess>]
module Erasure =
    /// Sentinel substituted for user-identifying content under the
    /// `Tombstone` policy. Preserves record shape + version chain
    /// while making the erasure itself discoverable ("we know we
    /// erased something").
    [<Literal>]
    let TombstoneMarker = "*ERASED*"

    /// True when the subject identifier is blank. A blank id would
    /// substring-match every record — a catastrophic over-erasure.
    /// Every store's `Erase` short-circuits to a zero-count no-op on
    /// a blank subject rather than touching anything.
    let isBlankSubject (subjectUserId: string) = String.IsNullOrWhiteSpace subjectUserId