// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

namespace ToolUp.Platform

open System

// ─── Deploy-plane substrate types (Phase 26) ─────────────────────────
//
// Supporting types for the four deploy-plane substrate interfaces
// (`IBuildOrchestrator`, `ITenantFleet`, `IDeployPipeline`,
// `IContainerScheduler`). Records + DUs only; the interfaces
// themselves live server-side in `ToolUp.Platform.Server` because
// `IContainerScheduler.StreamLogs` returns `IAsyncEnumerable<LogEntry>`
// (Fable-incompatible).
//
// These types are Fable-compatible (Async-free, no streams, no live
// handles) so a future Fable client UI can display tenant state /
// deploy state without round-tripping through a remoting DTO layer.
//
// **Identity by value (Phase 9c rule 1).** Every identifier here is a
// `string` alias — `TenantId`, `BuildId`, `DeployId`, `ContainerId`.
// No live framework handles cross the substrate boundary.

/// Stable tenant identifier. Generated by the deploy plane at
/// `ITenantFleet.ProvisionTenant`; same lifetime as the tenant
/// itself. Also used as the `scopeId` for every per-tenant store
/// under the tenant.
type TenantId = string

/// Stable build identifier. Generated by
/// `IBuildOrchestrator.EnqueueBuild` and persisted in the queue.
type BuildId = string

/// Stable deploy identifier. Generated by
/// `IDeployPipeline.BeginDeploy` and persisted across the deploy's
/// state transitions.
type DeployId = string

/// Stable container identifier within an `IContainerScheduler`'s
/// namespace. Operator-defined format (Docker assigns a 64-char
/// hex hash; Kubernetes uses `<pod>/<container>`; Fly assigns its
/// own machine id).
type ContainerId = string

// ─── Build orchestration ─────────────────────────────────────────────

/// What the build orchestrator should build from. Three shapes
/// covering the common cases; operator-specific sources extend via
/// `ExternalSource` and a paired DI registration in the orchestrator
/// companion.
type BuildSource =
    /// GitHub repository at a specific commit SHA. The orchestrator
    /// clones, runs the consumer's build script, and pushes the
    /// resulting image to the operator's registry.
    | GitHubRef of repo: string * sha: string
    /// Local filesystem path. Dev-only; the orchestrator's
    /// single-node default streams the directory contents into the
    /// build context.
    | LocalPath of path: string
    /// Pre-built container image reference. Skips the build phase
    /// entirely — the orchestrator records the build as `Succeeded`
    /// against this image and `IDeployPipeline` proceeds directly to
    /// push / launch.
    | PrebuiltImage of image: string
    /// Operator-defined source. Free-form `(kind, payload)` pair the
    /// orchestrator companion interprets. Use only when the three
    /// canonical sources don't fit.
    | ExternalSource of kind: string * payload: string

/// Retry policy applied to a build that fails transiently (network
/// blip, registry rate limit, transient OOM). Permanent failures
/// (compile error, missing Dockerfile) skip retry — the orchestrator
/// uses the build's exit status / log output to classify.
type BuildRetryPolicy = {
    /// Maximum attempts including the first. `1` disables retry.
    MaxAttempts: int
    /// Wait between attempts, in seconds, in order. `BackoffSeconds.[0]`
    /// is the wait before attempt 2, etc. Shorter than
    /// `MaxAttempts - 1` extends the last value; longer than
    /// `MaxAttempts - 1` ignores the tail.
    BackoffSeconds: int list
}

module BuildRetryPolicy =
    /// Single-attempt policy — fail fast, no retry. Use for builds
    /// where transient failure is unexpected (a manifest-pinned
    /// pre-built image, for example).
    let noRetry: BuildRetryPolicy = { MaxAttempts = 1; BackoffSeconds = [] }

    /// Sensible default: 3 attempts, 30s + 2min backoff. Captures
    /// most transient registry / network failures without making the
    /// failure path lethargic.
    let defaults: BuildRetryPolicy = {
        MaxAttempts = 3
        BackoffSeconds = [ 30; 120 ]
    }

/// Request to enqueue a build. Identity by value (`BuildRequest`
/// has no live handles); the orchestrator persists it and returns a
/// `BuildId`. Re-submitting the same request with the same
/// `Idempotency` token within the orchestrator's TTL returns the
/// existing `BuildId` rather than enqueueing a duplicate.
type BuildRequest = {
    /// Application slug the build is for. Matches `Tenant.Slug` —
    /// the orchestrator uses it for queue partitioning + log
    /// labelling.
    AppSlug: string
    /// What to build from.
    Source: BuildSource
    /// The deploy manifest the build is producing artefacts for.
    /// The orchestrator stores it alongside the build so a later
    /// `IDeployPipeline.BeginDeploy` can recover the manifest by
    /// `BuildId`.
    Manifest: DeployManifest
    /// How to retry a transient failure.
    RetryPolicy: BuildRetryPolicy
    /// Who submitted the build. Free-form `userId` per
    /// `ISubjectResolver`; the orchestrator emits an audit event
    /// stamping this on every state transition.
    SubmittedBy: string
    /// Optional idempotency token. When `Some` and a build exists
    /// with the same token under the orchestrator's TTL, the
    /// returned `BuildId` is the existing one — the duplicate
    /// submission is a no-op.
    Idempotency: string option
}

/// Lifecycle state of a build. Linear progression for the happy
/// path: `Queued` → `Building` → `Succeeded`. Failure branches:
/// `Failed` (terminal — retry exhausted), `Cancelled` (operator
/// abort). Retries between attempts cycle `Building` → (retry) →
/// `Building` until exhausted; the state DU only surfaces the
/// outer journey.
type BuildStatus =
    /// In the queue; the orchestrator hasn't started building yet.
    | Queued
    /// Build process actively running. `Attempt` is the current
    /// attempt number (1-based).
    | Building of startedAt: DateTime * attempt: int
    /// Build completed successfully. `ArtifactRef` is the resulting
    /// container image reference the deploy plane should pull from.
    | Succeeded of completedAt: DateTime * artifactRef: string
    /// Build exhausted its retries. Terminal; the operator surfaces
    /// `Reason` to the user-facing log.
    | Failed of completedAt: DateTime * reason: string
    /// Operator cancelled the build before it completed. Terminal.
    | Cancelled of cancelledAt: DateTime * byUserId: string

/// Lightweight projection over a build. The orchestrator emits these
/// from list / get methods; `BuildRequest` lives behind a separate
/// `GetBuildRequest` call when the full request payload is needed.
type BuildSummary = {
    BuildId: BuildId
    AppSlug: string
    Status: BuildStatus
    SubmittedAt: DateTime
    SubmittedBy: string
    /// Cumulative attempts so far. `1` while the first attempt is
    /// running; higher after each retry.
    AttemptCount: int
}

/// Why an `IBuildOrchestrator` call failed.
type BuildOrchestratorError =
    /// No build with this id exists in the orchestrator's store.
    | UnknownBuild of BuildId
    /// Request validation failed before the build entered the queue
    /// (e.g. empty `AppSlug`, missing `Source.GitHubRef.sha`).
    | InvalidRequest of reason: string
    /// `CancelBuild` called on a build that already terminated.
    /// `CurrentStatus` is the terminal status the orchestrator saw.
    | AlreadyTerminated of BuildId * currentStatus: BuildStatus
    /// Underlying persistence layer surfaced an error that couldn't
    /// be mapped to a more specific case.
    | OrchestratorStorageFailure of message: string

// ─── Tenant fleet ────────────────────────────────────────────────────

/// Tenant health summary. Computed by `ITenantFleet.GetTenantHealth`
/// from the underlying container scheduler's per-container probe
/// status. Aggregates: all containers `Healthy` → `Healthy`; any
/// `Unhealthy` → `Unhealthy`; mixed `Healthy` + `Degraded` →
/// `Degraded`; no containers → `Unknown`.
type TenantHealth =
    | TenantHealthy
    | TenantDegraded of message: string
    | TenantUnhealthy of message: string
    /// No containers running for the tenant (suspended, or never
    /// deployed). Distinguished from `Unhealthy` so admin UIs don't
    /// flag a paused tenant as broken.
    | TenantHealthUnknown

/// Request to provision a fresh tenant. The fleet persists a
/// `Tenant` entity via `IEntityStore` and returns it; no container
/// launches yet (that happens via `DeployToTenant`).
type ProvisioningRequest = {
    /// DNS-safe slug. Must pass
    /// `DeployManifest.isValidSlug` and be unique within `Region`
    /// at the time of provisioning. Concurrent submissions of the
    /// same slug+region are resolved by per-(region,slug) lock; the
    /// loser receives `SlugAlreadyTaken`.
    Slug: string
    /// Owner userId per `ISubjectResolver`. Indexed; one user
    /// can own many tenants.
    OwnerUserId: string
    /// Operator-defined deployment region.
    Region: string
    /// Operator-defined billing tier.
    Tier: string
    /// Display name shown in admin UIs. When `""`, defaults to
    /// `Slug` at provisioning.
    DisplayName: string
}

/// Request to deploy a built artefact to a provisioned tenant.
/// Composes `IBuildOrchestrator` output with `ITenantFleet`'s
/// `DeployToTenant` entry point.
type FleetDeployRequest = {
    TenantId: TenantId
    /// The build whose `Succeeded.ArtifactRef` is being deployed.
    BuildId: BuildId
    /// The manifest the deploy targets. Typically equal to the
    /// manifest the build was created against; carried separately so
    /// a re-deploy of an older build against an updated manifest
    /// (e.g. an env-var change) doesn't require a new build.
    Manifest: DeployManifest
    /// Operator userId submitting the deploy.
    SubmittedBy: string
}

/// Why an `ITenantFleet` call failed.
type TenantFleetError =
    /// No tenant with this id exists in the fleet.
    | UnknownTenant of TenantId
    /// `ProvisionTenant` (or `IsSlugAvailable`) found the slug
    /// already in use within the region.
    | SlugAlreadyTaken of slug: string * region: string
    /// Slug failed `DeployManifest.isValidSlug` format check.
    | TenantSlugInvalid of slug: string * reason: string
    /// State transition attempted on an evicted tenant
    /// (`RestartTenant` / `DeployToTenant` after eviction).
    | TenantEvicted of TenantId
    /// Underlying entity store surfaced an error.
    | FleetStorageFailure of message: string

// ─── Deploy pipeline ─────────────────────────────────────────────────

/// Lifecycle state of a deploy. Linear happy path: `DeployQueued` →
/// `DeployPushing` → `DeployHealthChecking` → `DeploySucceeded`.
/// (When the build was a `PrebuiltImage`, `DeployBuilding` is
/// skipped.) `DeployRolledBack` is set when an operator-triggered
/// or auto-rollback (failed healthcheck) reverted to a prior
/// deploy.
type DeployState =
    /// In the pipeline's queue, not started.
    | DeployQueued
    /// Waiting on `IBuildOrchestrator` to finish the underlying
    /// build. Only set when the build was not a `PrebuiltImage`.
    | DeployBuilding of buildId: BuildId
    /// Pushing the built artefact to the operator's registry.
    | DeployPushing of imageRef: string
    /// Container(s) launched; pipeline is waiting for healthcheck
    /// to pass. `ContainerIds` is the list the scheduler returned.
    | DeployHealthChecking of containerIds: ContainerId list
    /// Healthcheck passed; traffic flipped. Terminal.
    | DeploySucceeded of completedAt: DateTime
    /// Deploy failed at the named phase (`"build"`, `"push"`,
    /// `"healthcheck"`, etc.). Terminal.
    | DeployFailed of phase: string * reason: string
    /// Pipeline rolled this deploy back, restoring an earlier
    /// deploy. Terminal.
    | DeployRolledBack of toDeployId: DeployId

/// Lightweight projection over a deploy. Identity by value;
/// `Manifest` is carried so admin UIs can render the deploy without
/// a second lookup.
type DeploySummary = {
    DeployId: DeployId
    TenantId: TenantId
    BuildId: BuildId
    Manifest: DeployManifest
    State: DeployState
    StartedAt: DateTime
    StateChangedAt: DateTime
    SubmittedBy: string
}

/// Why an `IDeployPipeline` call failed.
type DeployPipelineError =
    /// No deploy with this id exists.
    | UnknownDeploy of DeployId
    /// `Rollback` called while a deploy is still mid-flight. The
    /// caller cancels the in-flight deploy first, then retries.
    | DeployStillRunning of DeployId
    /// `Rollback` had no previous successful deploy to revert to.
    | NothingToRollbackTo of TenantId
    /// Underlying persistence layer surfaced an error.
    | DeployStorageFailure of message: string

// ─── Container scheduler ─────────────────────────────────────────────

/// Spec for launching a container. The operator's
/// `IContainerScheduler` companion translates this to its target's
/// native shape (Docker `ContainerCreateParameters`, Kubernetes
/// `PodSpec`, Fly Machine launch payload, etc.).
type ContainerSpec = {
    /// Fully-qualified image reference (`ghcr.io/me/app:v1.2.3`).
    Image: string
    /// Environment variables passed to the container.
    EnvVars: Map<string, string>
    /// Port the container listens on. `None` for sidecar-shaped
    /// containers that don't accept inbound traffic.
    ExposedPort: int option
    /// HTTP path the scheduler uses for liveness/readiness probes.
    /// `None` disables the scheduler-side healthcheck (the caller
    /// is responsible for external probing).
    HealthcheckPath: string option
    /// Free-form labels the scheduler attaches to the container.
    /// Used by `ListContainers` filtering + operator dashboards.
    Labels: Map<string, string>
}

/// Container lifecycle state from the scheduler's perspective.
type ContainerStatus =
    /// Scheduler has no record of this container id.
    | ContainerNotFound
    /// Container created but not yet running (image pull, etc.).
    | ContainerCreated
    /// Container running normally. `Since` is when the current
    /// run started.
    | ContainerRunning of since: DateTime
    /// Scheduler is in the middle of restarting the container.
    | ContainerRestarting
    /// Container exited with a normal status code.
    | ContainerExited of code: int * at: DateTime
    /// Container crashed (non-zero exit + scheduler-decided
    /// "crash" classification, typically restart-loop hit). `Reason`
    /// is operator-defined; the scheduler companion populates it.
    | ContainerCrashed of reason: string * at: DateTime

/// Container projection returned by `ListContainers`. Identity by
/// value; `Status` is a snapshot at list-time (re-query via
/// `GetContainerStatus` for live state).
type ContainerInfo = {
    ContainerId: ContainerId
    TenantId: TenantId
    ImageRef: string
    Status: ContainerStatus
    Labels: Map<string, string>
}

/// Which side of the container's standard streams a log line came
/// from. Matches the Docker / OCI convention.
type LogStream =
    | Stdout
    | Stderr

/// A single log line. Streamed by
/// `IContainerScheduler.StreamLogs`.
type LogEntry = {
    /// When the container emitted the line (best-effort — the
    /// scheduler may add transport delay before this timestamp).
    At: DateTime
    Stream: LogStream
    Line: string
}

/// Why an `IContainerScheduler` call failed.
type ContainerSchedulerError =
    /// No container with this id exists in the scheduler.
    | UnknownContainer of ContainerId
    /// Image pull / build failed (registry unreachable, image
    /// not found, auth failure).
    | ImagePullFailed of image: string * reason: string
    /// Scheduler backend is unreachable (Docker socket down,
    /// Kubernetes API server down, etc.).
    | SchedulerUnavailable of message: string
    /// `ContainerSpec` failed validation (missing required field,
    /// invalid port, etc.).
    | InvalidContainerSpec of reason: string