// Generated by F* Custard extraction. Do not edit.
module ElmishRingArray
#nowarn "25" "26" "40" "49" "64" "1182" "3220"
open FStarCustard

type elmishRingArray_ring<'t> = {
  items : (('t)[] ref);
  cap : (uint64 ref);
  wix : (uint64 ref);
  rix : (uint64 ref);
  readable : (bool ref);
  dflt : 't;
}

let elmishRingArray_succ_sz (c : uint64) (i : uint64) : uint64 =
  (let i1 = (i + (1UL)) in
   (if (i1 >= c) then (0UL) else i1))

let elmishRingArray_pop (rb : elmishRingArray_ring<'t>) : option<'t> =
  (let rdv = (((rb).readable).Value) in
   (if rdv then (let vv = (((rb).items).Value) in
                 let cv = (((rb).cap).Value) in
                 let wv = (((rb).wix).Value) in
                 let rv = (((rb).rix).Value) in
                 let x = ((vv).[(int rv)]) in
                 let r1 = (elmishRingArray_succ_sz cv rv) in
                 (if (r1 = wv) then ((((rb).readable).Value <- false);
                                     (Some (x))) else ((((rb).rix).Value <- r1);
                                                       (Some (x))))) else None))

let elmishRingArray_grow (src : ('t)[]) (cv : uint64) (rv : uint64) (fill : 't) : ('t)[] =
  (let nc = ((cv + cv) + (1UL)) in
   let dst = (Array.create (int nc) fill) in
   let j = (ref (0UL)) in
   (while (let u___anf0 = ((j).Value) in
           (u___anf0 < cv)) do
      (let vj = ((j).Value) in
       let s = (rv + vj) in
       let from = (if (s >= cv) then (s - cv) else s) in
       let y = ((src).[(int from)]) in
       ((dst).[(int vj)] <- y);
       ((j).Value <- (vj + (1UL)))));
   dst)

let elmishRingArray_push (rb : elmishRingArray_ring<'t>) (x : 't) : bool =
  (let rdv = (((rb).readable).Value) in
   let vv = (((rb).items).Value) in
   let cv = (((rb).cap).Value) in
   let wv = (((rb).wix).Value) in
   (if rdv then (let rv = (((rb).rix).Value) in
                 let w1 = (elmishRingArray_succ_sz cv wv) in
                 (if (w1 = rv) then (if (cv > (1073741823UL)) then false else (((vv).[(int wv)] <- x);
                                                                               let nv = (elmishRingArray_grow vv cv rv (rb).dflt) in
                                                                               ();
                                                                               (((rb).items).Value <- nv);
                                                                               (((rb).cap).Value <- ((cv + cv) + (1UL)));
                                                                               (((rb).wix).Value <- cv);
                                                                               (((rb).rix).Value <- (0UL));
                                                                               true)) else (((vv).[(int wv)] <- x);
                                                                                            (((rb).wix).Value <- w1);
                                                                                            true))) else (((vv).[(int wv)] <- x);
                                                                                                          (((rb).rix).Value <- wv);
                                                                                                          (((rb).wix).Value <- (elmishRingArray_succ_sz cv wv));
                                                                                                          (((rb).readable).Value <- true);
                                                                                                          true)))

let elmishRingArray_create (size : uint64) (dflt : 't) : elmishRingArray_ring<'t> =
  (let n = (if (size > (2UL)) then size else (2UL)) in
   let v = (Array.create (int n) dflt) in
   let items = (ref v) in
   let cap = (ref n) in
   let wix = (ref (0UL)) in
   let rix = (ref (0UL)) in
   let readable = (ref false) in
   { elmishRingArray_ring.items = items;
     cap = cap;
     wix = wix;
     rix = rix;
     readable = readable;
     dflt = dflt })

