// Generated by F* Custard extraction. Do not edit.
//
// The Custard F# support library.  See section 122.8 of
// doc/ref/custard.md.  It holds exactly what .NET does not already
// supply under the name F* declares: the Prims operators on bigint, two
// 128-bit conversions that have no inline spelling, and FStar.IO.
module FStarCustard

open System

// A widening conversion into a 128-bit integer has to know the sign of
// what it came from -- FStar.Int.Cast.Full specifies the result mod
// 2^128, so a negative source sets the high bits -- and F# resolves an
// op_Implicit on the argument type, which at a type variable it cannot
// see.  These two do the resolving with an explicit conversion through
// the widest same-signed type, which is exact in both directions.
let inline toU128 (x : ^a) : UInt128 =
  UInt128.CreateTruncating x

let inline toI128 (x : ^a) : Int128 =
  Int128.CreateTruncating x

// F#'s ~~~ resolves against op_LogicalNot, which the 128-bit types do not
// define even though they define every other bitwise operator.  The
// complement of x is x xor all-ones, and for a signed one it is -x - 1.
let notU128 (x : UInt128) : UInt128 = UInt128.MaxValue ^^^ x
let notI128 (x : Int128) : Int128 = -x - Int128.One

// Section 122.13.  Prims.int is bigint, so these are the .NET operators
// under the names F* declares for them.
module Prims =
  let op_Plus (x : bigint) (y : bigint) : bigint = x + y
  let op_Minus (x : bigint) (y : bigint) : bigint = x - y
  let op_Star (x : bigint) (y : bigint) : bigint = x * y
  let op_Slash (x : bigint) (y : bigint) : bigint = x / y
  let op_Percent (x : bigint) (y : bigint) : bigint = x % y
  let op_Minus_Minus (x : bigint) : bigint = -x
  let op_Less (x : bigint) (y : bigint) : bool = x < y
  let op_Less_Equals (x : bigint) (y : bigint) : bool = x <= y
  let op_Greater (x : bigint) (y : bigint) : bool = x > y
  let op_Greater_Equals (x : bigint) (y : bigint) : bool = x >= y
  let abs (x : bigint) : bigint = if x < 0I then -x else x
  let pow2 (n : bigint) : bigint =
    System.Numerics.BigInteger.Pow (2I, int n)
  let strcat (x : string) (y : string) : string = x + y
  let string_of_bool (b : bool) : string = if b then "true" else "false"
  let string_of_int (x : bigint) : string = x.ToString ()
  let string_of_int8 (x : uint8) : string = x.ToString ()
  let string_of_int16 (x : uint16) : string = x.ToString ()
  let string_of_int32 (x : uint32) : string = x.ToString ()
  let string_of_int64 (x : uint64) : string = x.ToString ()
  let string_of_sint8 (x : int8) : string = x.ToString ()
  let string_of_sint16 (x : int16) : string = x.ToString ()
  let string_of_sint32 (x : int32) : string = x.ToString ()
  let string_of_sint64 (x : int64) : string = x.ToString ()

// Section 122.13.  Prims.list is F#'s own list, so FStar.List.Tot.Base is a
// line-for-line translation of the OCaml realization rather than anything
// this backend had to invent.
module FStar_List_Tot_Base =
  let isEmpty (l : 'a list) : bool = List.isEmpty l
  let hd (l : 'a list) : 'a = List.head l
  let tail (l : 'a list) : 'a list = List.tail l
  let tl (l : 'a list) : 'a list = List.tail l
  let last (l : 'a list) : 'a = List.last l
  let init (l : 'a list) : 'a list = List.truncate (List.length l - 1) l
  let length (l : 'a list) : bigint = bigint (List.length l)
  let nth (l : 'a list) (i : bigint) : 'a option =
    if i < 0I || i >= bigint (List.length l) then None
    else Some (List.item (int i) l)
  let index (l : 'a list) (i : bigint) : 'a = List.item (int i) l
  let count (x : 'a) (l : 'a list) : bigint =
    bigint (List.length (List.filter (fun y -> y = x) l))
  let rev_acc (l : 'a list) (r : 'a list) : 'a list = List.rev l @ r
  let rev (l : 'a list) : 'a list = List.rev l
  let append (l : 'a list) (r : 'a list) : 'a list = l @ r
  let snoc ((l : 'a list), (x : 'a)) : 'a list = l @ [x]
  let flatten (l : 'a list list) : 'a list = List.concat l
  let map (f : 'a -> 'b) (l : 'a list) : 'b list = List.map f l
  let mapi (f : bigint -> 'a -> 'b) (l : 'a list) : 'b list =
    List.mapi (fun i x -> f (bigint i) x) l
  let concatMap (f : 'a -> 'b list) (l : 'a list) : 'b list = List.collect f l
  let fold_left (f : 'a -> 'b -> 'a) (z : 'a) (l : 'b list) : 'a =
    List.fold f z l
  let fold_right (f : 'a -> 'b -> 'b) (l : 'a list) (z : 'b) : 'b =
    List.foldBack f l z
  let fold_left2 (f : 'a -> 'b -> 'c -> 'a) (z : 'a) (l : 'b list)
                 (m : 'c list) : 'a = List.fold2 f z l m
  let mem (x : 'a) (l : 'a list) : bool = List.contains x l
  let contains (x : 'a) (l : 'a list) : bool = List.contains x l
  let existsb (f : 'a -> bool) (l : 'a list) : bool = List.exists f l
  let find (f : 'a -> bool) (l : 'a list) : 'a option = List.tryFind f l
  let filter (f : 'a -> bool) (l : 'a list) : 'a list = List.filter f l
  let for_all (f : 'a -> bool) (l : 'a list) : bool = List.forall f l
  let collect (f : 'a -> 'b list) (l : 'a list) : 'b list = List.collect f l
  let tryFind (f : 'a -> bool) (l : 'a list) : 'a option = List.tryFind f l
  let tryPick (f : 'a -> 'b option) (l : 'a list) : 'b option = List.tryPick f l
  let choose (f : 'a -> 'b option) (l : 'a list) : 'b list = List.choose f l
  let partition (f : 'a -> bool) (l : 'a list) : 'a list * 'a list =
    List.partition f l
  let noRepeats (l : 'a list) : bool =
    List.length (List.distinct l) = List.length l
  let assoc (x : 'a) (l : ('a * 'b) list) : 'b option =
    List.tryPick (fun (k, v) -> if k = x then Some v else None) l
  let split (l : ('a * 'b) list) : 'a list * 'b list = List.unzip l
  let unzip (l : ('a * 'b) list) : 'a list * 'b list = List.unzip l
  let unzip3 (l : ('a * 'b * 'c) list) : 'a list * 'b list * 'c list =
    List.unzip3 l
  let splitAt (n : bigint) (l : 'a list) : 'a list * 'a list =
    List.splitAt (int n) l
  let unsnoc (l : 'a list) : 'a list * 'a =
    (List.truncate (List.length l - 1) l, List.last l)
  let split3 (l : 'a list) (i : bigint) : 'a list * 'a * 'a list =
    let a, b = List.splitAt (int i) l
    (a, List.head b, List.tail b)
  let bool_of_compare (f : 'a -> 'a -> bigint) (x : 'a) (y : 'a) : bool =
    f x y > 0I
  let compare_of_bool (r : 'a -> 'a -> bool) (x : 'a) (y : 'a) : bigint =
    if r x y then 1I elif x = y then 0I else -1I
  let sortWith (f : 'a -> 'a -> bigint) (l : 'a list) : 'a list =
    List.sortWith (fun x y -> int (f x y)) l
  let subset (l : 'a list) (r : 'a list) : bool =
    List.forall (fun x -> List.contains x r) l
  let list_unref (l : 'a list) : 'a list = l
  let list_ref (l : 'a list) : 'a list = l
  let list_refb (l : 'a list) : 'a list = l

module FStar_IO =
  let private w (s : string) : unit =
    Console.Out.Write s
    Console.Out.Flush ()

  let print_newline (_ : unit) : unit = w "\n"
  let print_string (s : string) : unit = w s
  let debug_print_string (s : string) : bool = w s; false

  let private hex (v : uint64) : string = "0x" + v.ToString "x"
  let private hexpad (n : int) (v : uint64) : string =
    "0x" + v.ToString("x").PadLeft(n, '0')
  let private decpad (n : int) (v : uint64) : string =
    v.ToString().PadLeft(n, '0')

  let print_uint8 (v : uint8) : unit = w (hex (uint64 v))
  let print_uint16 (v : uint16) : unit = w (hex (uint64 v))
  let print_uint32 (v : uint32) : unit = w (hex (uint64 v))
  let print_uint64 (v : uint64) : unit = w (hex v)

  let print_uint8_dec (v : uint8) : unit = w (string v)
  let print_uint16_dec (v : uint16) : unit = w (string v)
  let print_uint32_dec (v : uint32) : unit = w (string v)
  let print_uint64_dec (v : uint64) : unit = w (string v)

  let print_uint8_hex_pad (v : uint8) : unit = w (hexpad 2 (uint64 v))
  let print_uint16_hex_pad (v : uint16) : unit = w (hexpad 4 (uint64 v))
  let print_uint32_hex_pad (v : uint32) : unit = w (hexpad 8 (uint64 v))
  let print_uint64_hex_pad (v : uint64) : unit = w (hexpad 16 v)

  let print_uint8_dec_pad (v : uint8) : unit = w (decpad 3 (uint64 v))
  let print_uint16_dec_pad (v : uint16) : unit = w (decpad 5 (uint64 v))
  let print_uint32_dec_pad (v : uint32) : unit = w (decpad 10 (uint64 v))
  let print_uint64_dec_pad (v : uint64) : unit = w (decpad 20 v)

// Section 122.9.  [FStar.Char.char] is .NET's [char] and [Prims.string] is
// .NET's [string], so these are UTF-16 code units throughout -- see the
// note on [builtin_type].  Ordinal comparison and the invariant-culture
// case mappings, so that the result does not depend on the machine's
// locale the way a verified program's does not.
module FStar_Char =
  let lowercase (c : char) : char = System.Char.ToLowerInvariant c
  let uppercase (c : char) : char = System.Char.ToUpperInvariant c
  let int_of_char (c : char) : bigint = bigint (int c)
  let char_of_int (i : bigint) : char = char (int i)
  let u32_of_char (c : char) : uint32 = uint32 (int c)
  let char_of_u32 (u : uint32) : char = char (int u)

module FStar_String =
  let make (n : bigint) (c : char) : string = System.String (c, int n)
  let strcat (s : string) (t : string) : string = s + t
  let split (seps : char list) (s : string) : string list =
    List.ofArray (s.Split (Array.ofList seps))
  let compare (x : string) (y : string) : bigint =
    bigint (System.String.CompareOrdinal (x, y))
  let concat (sep : string) (l : string list) : string =
    System.String.Join (sep, l)
  let length (s : string) : bigint = bigint s.Length
  let substring (s : string) (i : bigint) (j : bigint) : string =
    s.Substring (int i, int j)
  let get (s : string) (i : bigint) : char = s.[int i]
  let collect (f : char -> string) (s : string) : string =
    System.String.Join ("", Seq.map f s)
  let lowercase (s : string) : string = s.ToLowerInvariant ()
  let uppercase (s : string) : string = s.ToUpperInvariant ()
  let index_of (s : string) (c : char) : bigint = bigint (s.IndexOf c)
  let list_of_string (s : string) : char list = List.ofSeq s
  let string_of_list (l : char list) : string = System.String (Array.ofList l)
  let string_of_char (c : char) : string = System.String (c, 1)

module FStar_All =
  let failwith (s : string) : 'a = failwith s
  let exit (i : bigint) : 'a = exit (int i)
  let try_with (f : unit -> 'a) (g : exn -> 'a) : 'a =
    try f () with e -> g e
  let pipe_right (x : 'a) (f : 'a -> 'b) : 'b = f x
  let pipe_left (f : 'a -> 'b) (x : 'a) : 'b = f x

// [FStar.List] is [FStar.List.Tot.Base] with an [ML] effect, which F#
// does not distinguish; only the three that are not in the total module
// under the same meaning are given here.
module FStar_List =
  let nth (l : 'a list) (i : bigint) : 'a = List.item (int i) l
  let iter (f : 'a -> unit) (l : 'a list) : unit = List.iter f l
  let iteri (f : bigint -> 'a -> unit) (l : 'a list) : unit =
    List.iteri (fun i x -> f (bigint i) x) l

// Section 122.17.  FStar.Bytes over byte[].  Where the OCaml realization
// uses a string it is because an OCaml string is a byte string; a .NET
// one is UTF-16, so the representation is an array and the two functions
// that really do relate bytes to text -- utf8_encode and iutf8_opt -- do
// the encoding rather than returning their argument.
module FStar_Bytes =
  let len (b : byte[]) : uint32 = uint32 b.Length
  let empty_bytes : byte[] = Array.empty
  let get (b : byte[]) (pos : uint32) : byte = b.[int pos]
  let create (n : uint32) (v : byte) : byte[] = Array.create (int n) v
  let init (n : uint32) (f : uint32 -> byte) : byte[] =
    Array.init (int n) (fun i -> f (uint32 i))
  let abyte (b : byte) : byte[] = [| b |]
  let twobytes (b : byte * byte) : byte[] = [| fst b; snd b |]
  let append (b1 : byte[]) (b2 : byte[]) : byte[] = Array.append b1 b2
  let slice (b : byte[]) (s : uint32) (e : uint32) : byte[] =
    Array.sub b (int s) (int e - int s)
  let sub (b : byte[]) (s : uint32) (l : uint32) : byte[] =
    Array.sub b (int s) (int l)
  let split (b : byte[]) (k : uint32) : byte[] * byte[] =
    (Array.sub b 0 (int k), Array.sub b (int k) (b.Length - int k))
  let rec repr_bytes (n : bigint) : bigint =
    if n < 256I then 1I else 1I + repr_bytes (n / 256I)
  // Big endian, which is what the specification's int_of_bytes_of_int
  // and the OCaml realization both say.
  let int_of_bytes (b : byte[]) : bigint =
    Array.fold (fun acc (x : byte) -> acc * 256I + bigint (int x)) 0I b
  let bytes_of_int (nb : bigint) (i : bigint) : byte[] =
    let n = int nb
    let r : byte[] = Array.zeroCreate n
    let mutable v = i
    for k in n - 1 .. -1 .. 0 do
      r.[k] <- byte (v % 256I)
      v <- v / 256I
    r
  let int32_of_bytes (b : byte[]) : uint32 = uint32 (int_of_bytes b)
  let int16_of_bytes (b : byte[]) : uint16 = uint16 (int_of_bytes b)
  let int8_of_bytes (b : byte[]) : byte = byte (int_of_bytes b)
  let bytes_of_int32 (n : uint32) : byte[] = bytes_of_int 4I (bigint n)
  let bytes_of_int16 (n : uint16) : byte[] = bytes_of_int 2I (bigint (int n))
  let bytes_of_int8 (n : byte) : byte[] = bytes_of_int 1I (bigint (int n))
  let xor (n : uint32) (b1 : byte[]) (b2 : byte[]) : byte[] =
    Array.init (int n) (fun i -> b1.[i] ^^^ b2.[i])
  let utf8_encode (s : string) : byte[] = Text.Encoding.UTF8.GetBytes s
  let bytes_of_string (s : string) : byte[] = utf8_encode s
  // Strict: the specification says the result decodes back to the
  // argument, and .NET replaces an ill-formed sequence with U+FFFD
  // unless the decoder is told to throw.
  let private strictUtf8 = Text.UTF8Encoding (false, true)
  let iutf8_opt (b : byte[]) : string option =
    try Some (strictUtf8.GetString b) with _ -> None
  let private hexd = "0123456789abcdef"
  let private nibble (c : char) : int =
    if c >= '0' && c <= '9' then int c - int '0'
    elif c >= 'a' && c <= 'f' then 10 + int c - int 'a'
    elif c >= 'A' && c <= 'F' then 10 + int c - int 'A'
    else failwith "bytes_of_hex: invalid hex digit"
  let bytes_of_hex (s : string) : byte[] =
    if s.Length % 2 <> 0 then failwith "bytes_of_hex: invalid length"
    else Array.init (s.Length / 2)
           (fun i -> byte (nibble s.[2 * i] * 16 + nibble s.[2 * i + 1]))
  let hex_of_bytes (b : byte[]) : string =
    System.String (Array.collect
      (fun (x : byte) -> [| hexd.[int x >>> 4]; hexd.[int x &&& 0xf] |]) b)
  // These two are the same encoding over a string whose characters are
  // byte values -- which is what an OCaml string holding bytes is, and
  // is the reading the OCaml realization gives them.
  let string_of_hex (s : string) : string =
    System.String (Array.map char (bytes_of_hex s))
  let hex_of_string (s : string) : string =
    hex_of_bytes (Array.map byte (Array.ofSeq s))
  let print_bytes (b : byte[]) : string =
    (hex_of_bytes b).ToUpperInvariant ()

