// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)
//
// <auto-generated>
//   Phase 841 — emitted by ToolUp.Remoting.Generator from the SAME
//   record/union metadata the System.Text.Json converter set reads:
//   record members by NAME, union cases by case NAME, one decoder per
//   argument type an API record's methods take.
//
//   DO NOT EDIT. Re-run the generator; a contract test in
//   ToolUp.Platform.Tests holds this file to what the generator emits.
// </auto-generated>

namespace ToolUp.Remoting.Json

open System
open ToolUp.Remoting
open ToolUp.Remoting.Json
open ToolUp.Platform
open ToolUp.Platform.Usage

/// Generated JSON algebra decoders for the ARGUMENTS the covered API
/// records' methods take, each registered scoped to its own record by
/// `registerAll` (or, verified against the System.Text.Json converter set
/// first, by `registerAllVerified`). Emitted by ToolUp.Remoting.Generator;
/// do not edit.
[<RequireQualifiedAccess>]
module PlatformJsonDecoders =

    /// Generated JSON decoder for `ColumnMappingTypes.DateOrder` — members by name, cases by case name, read off the type's own shape.
    let dateOrder: JsonDecoder<ColumnMappingTypes.DateOrder> =
        JsonDecode.union "ColumnMappingTypes.DateOrder" (function
            | "DayFirst" -> Some(JsonDecode.case0 ColumnMappingTypes.DateOrder.DayFirst)
            | "MonthFirst" -> Some(JsonDecode.case0 ColumnMappingTypes.DateOrder.MonthFirst)
            | "YearFirst" -> Some(JsonDecode.case0 ColumnMappingTypes.DateOrder.YearFirst)
            | _ -> None)

    /// Generated JSON decoder for `ColumnMappingTypes.CellTransform` — members by name, cases by case name, read off the type's own shape.
    let cellTransform: JsonDecoder<ColumnMappingTypes.CellTransform> =
        JsonDecode.union "ColumnMappingTypes.CellTransform" (function
            | "Trim" -> Some(JsonDecode.case0 ColumnMappingTypes.CellTransform.Trim)
            | "StripThousandsSeparators" -> Some(JsonDecode.case0 ColumnMappingTypes.CellTransform.StripThousandsSeparators)
            | "StripCurrency" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map ColumnMappingTypes.CellTransform.StripCurrency))
            | "StripPercent" -> Some(JsonDecode.case0 ColumnMappingTypes.CellTransform.StripPercent)
            | "DecimalCommaToDot" -> Some(JsonDecode.case0 ColumnMappingTypes.CellTransform.DecimalCommaToDot)
            | "StripLeadingApostrophe" -> Some(JsonDecode.case0 ColumnMappingTypes.CellTransform.StripLeadingApostrophe)
            | "BlankNullMarkers" -> Some(JsonDecode.payload ((JsonDecode.list JsonDecode.asString) |> JsonDecode.map ColumnMappingTypes.CellTransform.BlankNullMarkers))
            | "NormaliseBoolean" -> Some(JsonDecode.case0 ColumnMappingTypes.CellTransform.NormaliseBoolean)
            | "ParseDateToIso" -> Some(JsonDecode.payload (dateOrder |> JsonDecode.map ColumnMappingTypes.CellTransform.ParseDateToIso))
            | _ -> None)

    /// Generated JSON decoder for `ColumnMappingTypes.ColumnExpr` — members by name, cases by case name, read off the type's own shape.
    let rec columnExpr: JsonDecoder<ColumnMappingTypes.ColumnExpr> =
        fun value ->
            (JsonDecode.union "ColumnMappingTypes.ColumnExpr" (function
                 | "SourceColumn" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map ColumnMappingTypes.ColumnExpr.SourceColumn))
                 | "Constant" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map ColumnMappingTypes.ColumnExpr.Constant))
                 | "Concat" ->
                     Some(
                         JsonDecode.fields
                             2
                             (JsonDecode.succeed (fun parts separator -> ColumnMappingTypes.ColumnExpr.Concat(parts, separator))
                              |> JsonDecode.apply (JsonDecode.index 0 (JsonDecode.list columnExpr))
                              |> JsonDecode.apply (JsonDecode.index 1 JsonDecode.asString))
                     )
                 | "SplitTake" ->
                     Some(
                         JsonDecode.fields
                             3
                             (JsonDecode.succeed (fun source delimiter index -> ColumnMappingTypes.ColumnExpr.SplitTake(source, delimiter, index))
                              |> JsonDecode.apply (JsonDecode.index 0 columnExpr)
                              |> JsonDecode.apply (JsonDecode.index 1 JsonDecode.asString)
                              |> JsonDecode.apply (JsonDecode.index 2 JsonDecode.asInt32))
                     )
                 | "Format" ->
                     Some(
                         JsonDecode.fields
                             2
                             (JsonDecode.succeed (fun template args -> ColumnMappingTypes.ColumnExpr.Format(template, args))
                              |> JsonDecode.apply (JsonDecode.index 0 JsonDecode.asString)
                              |> JsonDecode.apply (JsonDecode.index 1 (JsonDecode.list columnExpr)))
                     )
                 | "Substring" ->
                     Some(
                         JsonDecode.fields
                             3
                             (JsonDecode.succeed (fun source start length -> ColumnMappingTypes.ColumnExpr.Substring(source, start, length))
                              |> JsonDecode.apply (JsonDecode.index 0 columnExpr)
                              |> JsonDecode.apply (JsonDecode.index 1 JsonDecode.asInt32)
                              |> JsonDecode.apply (JsonDecode.index 2 JsonDecode.asInt32))
                     )
                 | _ -> None))
                value

    /// Generated JSON decoder for `ColumnMappingTypes.DerivedColumn` — members by name, cases by case name, read off the type's own shape.
    let derivedColumn: JsonDecoder<ColumnMappingTypes.DerivedColumn> =
        JsonDecode.succeed (fun field expr -> ({
            Field = field
            Expr = expr
        }: ColumnMappingTypes.DerivedColumn))
        |> JsonDecode.apply (JsonDecode.field "Field" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Expr" columnExpr)

    /// Generated JSON decoder for `ColumnMappingTypes.Conversion` — members by name, cases by case name, read off the type's own shape.
    let conversion: JsonDecoder<ColumnMappingTypes.Conversion> =
        JsonDecode.succeed (fun fingerprint targetTypeId mapping remediation sourceHeaders derived createdBy createdAt -> ({
            Fingerprint = fingerprint
            TargetTypeId = targetTypeId
            Mapping = mapping
            Remediation = remediation
            SourceHeaders = sourceHeaders
            Derived = derived
            CreatedBy = createdBy
            CreatedAt = createdAt
        }: ColumnMappingTypes.Conversion))
        |> JsonDecode.apply (JsonDecode.field "Fingerprint" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "TargetTypeId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Mapping" (JsonDecode.asMap JsonDecode.Key.string JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.field "Remediation" (JsonDecode.asMap JsonDecode.Key.string (JsonDecode.list cellTransform)))
        |> JsonDecode.apply (JsonDecode.field "SourceHeaders" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.field "Derived" (JsonDecode.list derivedColumn))
        |> JsonDecode.apply (JsonDecode.field "CreatedBy" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "CreatedAt" JsonDecode.asDateTime)

    /// Generated JSON decoder for `ColumnMappingTypes.ConversionRecord` — members by name, cases by case name, read off the type's own shape.
    let conversionRecord: JsonDecoder<ColumnMappingTypes.ConversionRecord> =
        JsonDecode.succeed (fun producedFile sourceFile fingerprint targetTypeId mapping remediationSteps convertedBy convertedAt -> ({
            ProducedFile = producedFile
            SourceFile = sourceFile
            Fingerprint = fingerprint
            TargetTypeId = targetTypeId
            Mapping = mapping
            RemediationSteps = remediationSteps
            ConvertedBy = convertedBy
            ConvertedAt = convertedAt
        }: ColumnMappingTypes.ConversionRecord))
        |> JsonDecode.apply (JsonDecode.field "ProducedFile" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "SourceFile" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Fingerprint" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "TargetTypeId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Mapping" (JsonDecode.asMap JsonDecode.Key.string JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.field "RemediationSteps" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.field "ConvertedBy" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ConvertedAt" JsonDecode.asDateTime)

    /// Generated JSON decoder for `ColumnMappingTypes.DryRunValidationRequest` — members by name, cases by case name, read off the type's own shape.
    let dryRunValidationRequest: JsonDecoder<ColumnMappingTypes.DryRunValidationRequest> =
        JsonDecode.succeed (fun conversion rawCsv -> ({
            Conversion = conversion
            RawCsv = rawCsv
        }: ColumnMappingTypes.DryRunValidationRequest))
        |> JsonDecode.apply (JsonDecode.field "Conversion" conversion)
        |> JsonDecode.apply (JsonDecode.field "RawCsv" JsonDecode.asString)

    /// Generated JSON decoder for `DataManagementTypes.DataFileUpload` — members by name, cases by case name, read off the type's own shape.
    let dataFileUpload: JsonDecoder<DataManagementTypes.DataFileUpload> =
        JsonDecode.succeed (fun filename contents dataType -> ({
            filename = filename
            contents = contents
            dataType = dataType
        }: DataManagementTypes.DataFileUpload))
        |> JsonDecode.apply (JsonDecode.field "filename" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "contents" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "dataType" JsonDecode.asString)

    /// Generated JSON decoder for `DataManagementTypes.FileUploadRequest` — members by name, cases by case name, read off the type's own shape.
    let fileUploadRequest: JsonDecoder<DataManagementTypes.FileUploadRequest> =
        JsonDecode.succeed (fun file -> ({
            File = file
        }: DataManagementTypes.FileUploadRequest))
        |> JsonDecode.apply (JsonDecode.field "File" dataFileUpload)

    /// Generated JSON decoder for `BudgetDenial` — members by name, cases by case name, read off the type's own shape.
    let budgetDenial: JsonDecoder<BudgetDenial> =
        JsonDecode.succeed (fun domain scopeId classLabel dimension quota spent requested periodKey -> ({
            Domain = domain
            ScopeId = scopeId
            ClassLabel = classLabel
            Dimension = dimension
            Quota = quota
            Spent = spent
            Requested = requested
            PeriodKey = periodKey
        }: BudgetDenial))
        |> JsonDecode.apply (JsonDecode.field "Domain" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ScopeId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ClassLabel" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Dimension" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Quota" JsonDecode.asDecimal)
        |> JsonDecode.apply (JsonDecode.field "Spent" JsonDecode.asDecimal)
        |> JsonDecode.apply (JsonDecode.field "Requested" JsonDecode.asDecimal)
        |> JsonDecode.apply (JsonDecode.field "PeriodKey" JsonDecode.asString)

    /// Generated JSON decoder for `BudgetWarning` — members by name, cases by case name, read off the type's own shape.
    let budgetWarning: JsonDecoder<BudgetWarning> =
        JsonDecode.succeed (fun domain scopeId classLabel dimension quota spent threshold periodKey -> ({
            Domain = domain
            ScopeId = scopeId
            ClassLabel = classLabel
            Dimension = dimension
            Quota = quota
            Spent = spent
            Threshold = threshold
            PeriodKey = periodKey
        }: BudgetWarning))
        |> JsonDecode.apply (JsonDecode.field "Domain" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ScopeId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ClassLabel" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Dimension" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Quota" JsonDecode.asDecimal)
        |> JsonDecode.apply (JsonDecode.field "Spent" JsonDecode.asDecimal)
        |> JsonDecode.apply (JsonDecode.field "Threshold" JsonDecode.asDecimal)
        |> JsonDecode.apply (JsonDecode.field "PeriodKey" JsonDecode.asString)

    /// Generated JSON decoder for `DataSubjectRequestApi.ExportRequestInput` — members by name, cases by case name, read off the type's own shape.
    let exportRequestInput: JsonDecoder<DataSubjectRequestApi.ExportRequestInput> =
        JsonDecode.succeed (fun subjectUserId teamId reason -> ({
            SubjectUserId = subjectUserId
            TeamId = teamId
            Reason = reason
        }: DataSubjectRequestApi.ExportRequestInput))
        |> JsonDecode.apply (JsonDecode.field "SubjectUserId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "TeamId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Reason" JsonDecode.asString)

    /// Generated JSON decoder for `ErasurePolicy` — members by name, cases by case name, read off the type's own shape.
    let erasurePolicy: JsonDecoder<ErasurePolicy> =
        JsonDecode.union "ErasurePolicy" (function
            | "HardDelete" -> Some(JsonDecode.case0 ErasurePolicy.HardDelete)
            | "Tombstone" -> Some(JsonDecode.case0 ErasurePolicy.Tombstone)
            | "RetainPerCompliance" -> Some(JsonDecode.case0 ErasurePolicy.RetainPerCompliance)
            | _ -> None)

    /// Generated JSON decoder for `DataSubjectRequestApi.ErasureRequestInput` — members by name, cases by case name, read off the type's own shape.
    let erasureRequestInput: JsonDecoder<DataSubjectRequestApi.ErasureRequestInput> =
        JsonDecode.succeed (fun subjectUserId teamId reason overridePolicy -> ({
            SubjectUserId = subjectUserId
            TeamId = teamId
            Reason = reason
            OverridePolicy = overridePolicy
        }: DataSubjectRequestApi.ErasureRequestInput))
        |> JsonDecode.apply (JsonDecode.field "SubjectUserId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "TeamId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Reason" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "OverridePolicy" erasurePolicy)

    /// Generated JSON decoder for `AuditTrailQuery` — members by name, cases by case name, read off the type's own shape.
    let auditTrailQuery: JsonDecoder<AuditTrailQuery> =
        JsonDecode.succeed (fun from to' eventType actor cursor pageSize -> ({
            From = from
            To = to'
            EventType = eventType
            Actor = actor
            Cursor = cursor
            PageSize = pageSize
        }: AuditTrailQuery))
        |> JsonDecode.apply (JsonDecode.optionalField "From" JsonDecode.asDateTime)
        |> JsonDecode.apply (JsonDecode.optionalField "To" JsonDecode.asDateTime)
        |> JsonDecode.apply (JsonDecode.optionalField "EventType" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "Actor" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "Cursor" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "PageSize" JsonDecode.asInt32)

    /// Generated JSON decoder for `InspectorPanel` — members by name, cases by case name, read off the type's own shape.
    let inspectorPanel: JsonDecoder<InspectorPanel> =
        JsonDecode.union "InspectorPanel" (function
            | "CompositionPanel" -> Some(JsonDecode.case0 InspectorPanel.CompositionPanel)
            | "SurfacesPanel" -> Some(JsonDecode.case0 InspectorPanel.SurfacesPanel)
            | "RulesPanel" -> Some(JsonDecode.case0 InspectorPanel.RulesPanel)
            | "DisclosurePanel" -> Some(JsonDecode.case0 InspectorPanel.DisclosurePanel)
            | "ProvenancePanel" -> Some(JsonDecode.case0 InspectorPanel.ProvenancePanel)
            | _ -> None)

    /// Generated JSON decoder for `DataSourceConfig` — members by name, cases by case name, read off the type's own shape.
    let dataSourceConfig: JsonDecoder<DataSourceConfig> =
        JsonDecode.succeed (fun id name kind connectionScope credentialKey tables tags -> ({
            Id = id
            Name = name
            Kind = kind
            ConnectionScope = connectionScope
            CredentialKey = credentialKey
            Tables = tables
            Tags = tags
        }: DataSourceConfig))
        |> JsonDecode.apply (JsonDecode.field "Id" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Name" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Kind" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ConnectionScope" (JsonDecode.asMap JsonDecode.Key.string JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.field "CredentialKey" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "Tables" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.field "Tags" (JsonDecode.asMap JsonDecode.Key.string JsonDecode.asString))

    /// Generated JSON decoder for `ContactOwner` — members by name, cases by case name, read off the type's own shape.
    let contactOwner: JsonDecoder<ContactOwner> =
        JsonDecode.union "ContactOwner" (function
            | "User" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map ContactOwner.User))
            | "Team" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map ContactOwner.Team))
            | _ -> None)

    /// Generated JSON decoder for `CreateExternalContactRequest` — members by name, cases by case name, read off the type's own shape.
    let createExternalContactRequest: JsonDecoder<CreateExternalContactRequest> =
        JsonDecode.succeed (fun displayName emailAddress phoneNumber whatsAppNumber owner tags notes -> ({
            DisplayName = displayName
            EmailAddress = emailAddress
            PhoneNumber = phoneNumber
            WhatsAppNumber = whatsAppNumber
            Owner = owner
            Tags = tags
            Notes = notes
        }: CreateExternalContactRequest))
        |> JsonDecode.apply (JsonDecode.field "DisplayName" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "EmailAddress" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "PhoneNumber" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "WhatsAppNumber" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Owner" contactOwner)
        |> JsonDecode.apply (JsonDecode.field "Tags" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.optionalField "Notes" JsonDecode.asString)

    /// Generated JSON decoder for `UpdateExternalContactRequest` — members by name, cases by case name, read off the type's own shape.
    let updateExternalContactRequest: JsonDecoder<UpdateExternalContactRequest> =
        JsonDecode.succeed (fun contactId displayName emailAddress phoneNumber whatsAppNumber tags notes -> ({
            ContactId = contactId
            DisplayName = displayName
            EmailAddress = emailAddress
            PhoneNumber = phoneNumber
            WhatsAppNumber = whatsAppNumber
            Tags = tags
            Notes = notes
        }: UpdateExternalContactRequest))
        |> JsonDecode.apply (JsonDecode.field "ContactId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "DisplayName" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "EmailAddress" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "PhoneNumber" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "WhatsAppNumber" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Tags" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.optionalField "Notes" JsonDecode.asString)

    /// Generated JSON decoder for `RecordOptInRequest` — members by name, cases by case name, read off the type's own shape.
    let recordOptInRequest: JsonDecoder<RecordOptInRequest> =
        JsonDecode.succeed (fun contactId channel source expiresAt -> ({
            ContactId = contactId
            Channel = channel
            Source = source
            ExpiresAt = expiresAt
        }: RecordOptInRequest))
        |> JsonDecode.apply (JsonDecode.field "ContactId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Channel" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Source" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "ExpiresAt" JsonDecode.asDateTime)

    /// Generated JSON decoder for `WithdrawOptInRequest` — members by name, cases by case name, read off the type's own shape.
    let withdrawOptInRequest: JsonDecoder<WithdrawOptInRequest> =
        JsonDecode.succeed (fun contactId channel reason -> ({
            ContactId = contactId
            Channel = channel
            Reason = reason
        }: WithdrawOptInRequest))
        |> JsonDecode.apply (JsonDecode.field "ContactId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Channel" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Reason" JsonDecode.asString)

    /// Generated JSON decoder for `FlagValue` — members by name, cases by case name, read off the type's own shape.
    let flagValue: JsonDecoder<FlagValue> =
        JsonDecode.union "FlagValue" (function
            | "Bool" -> Some(JsonDecode.payload (JsonDecode.asBool |> JsonDecode.map FlagValue.Bool))
            | "Variant" ->
                Some(
                    JsonDecode.fields
                        2
                        (JsonDecode.succeed (fun options value -> FlagValue.Variant(options, value))
                         |> JsonDecode.apply (JsonDecode.index 0 (JsonDecode.list JsonDecode.asString))
                         |> JsonDecode.apply (JsonDecode.index 1 JsonDecode.asString))
                )
            | _ -> None)

    /// Generated JSON decoder for `PinRequest` — members by name, cases by case name, read off the type's own shape.
    let pinRequest: JsonDecoder<PinRequest> =
        JsonDecode.succeed (fun moduleId pinned -> ({
            ModuleId = moduleId
            Pinned = pinned
        }: PinRequest))
        |> JsonDecode.apply (JsonDecode.field "ModuleId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Pinned" JsonDecode.asBool)

    /// Generated JSON decoder for `ModuleQueryRequest` — members by name, cases by case name, read off the type's own shape.
    let moduleQueryRequest: JsonDecoder<ModuleQueryRequest> =
        JsonDecode.succeed (fun targetModule queryKey payload -> ({
            TargetModule = targetModule
            QueryKey = queryKey
            Payload = payload
        }: ModuleQueryRequest))
        |> JsonDecode.apply (JsonDecode.field "TargetModule" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "QueryKey" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Payload" JsonDecode.asString)

    /// Generated JSON decoder for `ModuleVisibilityRule` — members by name, cases by case name, read off the type's own shape.
    let moduleVisibilityRule: JsonDecoder<ModuleVisibilityRule> =
        JsonDecode.union "ModuleVisibilityRule" (function
            | "Allow" -> Some(JsonDecode.payload ((JsonDecode.list JsonDecode.asString) |> JsonDecode.map ModuleVisibilityRule.Allow))
            | "Deny" -> Some(JsonDecode.payload ((JsonDecode.list JsonDecode.asString) |> JsonDecode.map ModuleVisibilityRule.Deny))
            | _ -> None)

    /// Generated JSON decoder for `ModuleVisibilityProfileInput` — members by name, cases by case name, read off the type's own shape.
    let moduleVisibilityProfileInput: JsonDecoder<ModuleVisibilityProfileInput> =
        JsonDecode.succeed (fun rule excludedEntryIds note -> ({
            Rule = rule
            ExcludedEntryIds = excludedEntryIds
            Note = note
        }: ModuleVisibilityProfileInput))
        |> JsonDecode.apply (JsonDecode.field "Rule" moduleVisibilityRule)
        |> JsonDecode.apply (JsonDecode.field "ExcludedEntryIds" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.optionalField "Note" JsonDecode.asString)

    /// Generated JSON decoder for `PreferenceChannel` — members by name, cases by case name, read off the type's own shape.
    let preferenceChannel: JsonDecoder<PreferenceChannel> =
        JsonDecode.union "PreferenceChannel" (function
            | "Email" -> Some(JsonDecode.case0 PreferenceChannel.Email)
            | "Sms" -> Some(JsonDecode.case0 PreferenceChannel.Sms)
            | "Push" -> Some(JsonDecode.case0 PreferenceChannel.Push)
            | _ -> None)

    /// Generated JSON decoder for `DigestFrequency` — members by name, cases by case name, read off the type's own shape.
    let digestFrequency: JsonDecoder<DigestFrequency> =
        JsonDecode.union "DigestFrequency" (function
            | "Hourly" -> Some(JsonDecode.case0 DigestFrequency.Hourly)
            | "Daily" -> Some(JsonDecode.case0 DigestFrequency.Daily)
            | "Weekly" -> Some(JsonDecode.case0 DigestFrequency.Weekly)
            | _ -> None)

    /// Generated JSON decoder for `DeliveryPreference` — members by name, cases by case name, read off the type's own shape.
    let deliveryPreference: JsonDecoder<DeliveryPreference> =
        JsonDecode.union "DeliveryPreference" (function
            | "Immediate" -> Some(JsonDecode.case0 DeliveryPreference.Immediate)
            | "Digest" -> Some(JsonDecode.payload (digestFrequency |> JsonDecode.map DeliveryPreference.Digest))
            | "Muted" -> Some(JsonDecode.case0 DeliveryPreference.Muted)
            | _ -> None)

    /// Generated JSON decoder for `CategoryChannelPreference` — members by name, cases by case name, read off the type's own shape.
    let categoryChannelPreference: JsonDecoder<CategoryChannelPreference> =
        JsonDecode.succeed (fun category channel delivery -> ({
            Category = category
            Channel = channel
            Delivery = delivery
        }: CategoryChannelPreference))
        |> JsonDecode.apply (JsonDecode.field "Category" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Channel" preferenceChannel)
        |> JsonDecode.apply (JsonDecode.field "Delivery" deliveryPreference)

    /// Generated JSON decoder for `QuietHours` — members by name, cases by case name, read off the type's own shape.
    let quietHours: JsonDecoder<QuietHours> =
        JsonDecode.succeed (fun startMinute endMinute timeZoneId -> ({
            StartMinute = startMinute
            EndMinute = endMinute
            TimeZoneId = timeZoneId
        }: QuietHours))
        |> JsonDecode.apply (JsonDecode.field "StartMinute" JsonDecode.asInt32)
        |> JsonDecode.apply (JsonDecode.field "EndMinute" JsonDecode.asInt32)
        |> JsonDecode.apply (JsonDecode.field "TimeZoneId" JsonDecode.asString)

    /// Generated JSON decoder for `UserNotificationPreferences` — members by name, cases by case name, read off the type's own shape.
    let userNotificationPreferences: JsonDecoder<UserNotificationPreferences> =
        JsonDecode.succeed (fun channels quietHours -> ({
            Channels = channels
            QuietHours = quietHours
        }: UserNotificationPreferences))
        |> JsonDecode.apply (JsonDecode.field "Channels" (JsonDecode.list categoryChannelPreference))
        |> JsonDecode.apply (JsonDecode.optionalField "QuietHours" quietHours)

    /// Generated JSON decoder for `ProvisioningRequest` — members by name, cases by case name, read off the type's own shape.
    let provisioningRequest: JsonDecoder<ProvisioningRequest> =
        JsonDecode.succeed (fun slug ownerUserId region tier displayName -> ({
            Slug = slug
            OwnerUserId = ownerUserId
            Region = region
            Tier = tier
            DisplayName = displayName
        }: ProvisioningRequest))
        |> JsonDecode.apply (JsonDecode.field "Slug" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "OwnerUserId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Region" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Tier" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "DisplayName" JsonDecode.asString)

    /// Generated JSON decoder for `PresenceLocation` — members by name, cases by case name, read off the type's own shape.
    let presenceLocation: JsonDecoder<PresenceLocation> =
        JsonDecode.succeed (fun module' page -> ({
            Module = module'
            Page = page
        }: PresenceLocation))
        |> JsonDecode.apply (JsonDecode.field "Module" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "Page" JsonDecode.asString)

    /// Generated JSON decoder for `EntityLockRef` — members by name, cases by case name, read off the type's own shape.
    let entityLockRef: JsonDecoder<EntityLockRef> =
        JsonDecode.succeed (fun entityType entityId -> ({
            EntityType = entityType
            EntityId = entityId
        }: EntityLockRef))
        |> JsonDecode.apply (JsonDecode.field "EntityType" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "EntityId" JsonDecode.asString)

    /// Generated JSON decoder for `WireProvenanceRef` — members by name, cases by case name, read off the type's own shape.
    let wireProvenanceRef: JsonDecoder<WireProvenanceRef> =
        JsonDecode.union "WireProvenanceRef" (function
            | "DataObjectRef" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map WireProvenanceRef.DataObjectRef))
            | "ResultRef" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map WireProvenanceRef.ResultRef))
            | "FactRef" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map WireProvenanceRef.FactRef))
            | "MessageRef" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map WireProvenanceRef.MessageRef))
            | "ModelArtifactRef" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map WireProvenanceRef.ModelArtifactRef))
            | _ -> None)

    /// Generated JSON decoder for `WireProvenanceDirection` — members by name, cases by case name, read off the type's own shape.
    let wireProvenanceDirection: JsonDecoder<WireProvenanceDirection> =
        JsonDecode.union "WireProvenanceDirection" (function
            | "Upstream" -> Some(JsonDecode.case0 WireProvenanceDirection.Upstream)
            | "Downstream" -> Some(JsonDecode.case0 WireProvenanceDirection.Downstream)
            | _ -> None)

    /// Generated JSON decoder for `WireProvenanceChainRequest` — members by name, cases by case name, read off the type's own shape.
    let wireProvenanceChainRequest: JsonDecoder<WireProvenanceChainRequest> =
        JsonDecode.succeed (fun root direction depth -> ({
            Root = root
            Direction = direction
            Depth = depth
        }: WireProvenanceChainRequest))
        |> JsonDecode.apply (JsonDecode.field "Root" wireProvenanceRef)
        |> JsonDecode.apply (JsonDecode.field "Direction" wireProvenanceDirection)
        |> JsonDecode.apply (JsonDecode.field "Depth" JsonDecode.asInt32)

    /// Generated JSON decoder for `ProviderEntryInput` — members by name, cases by case name, read off the type's own shape.
    let providerEntryInput: JsonDecoder<ProviderEntryInput> =
        JsonDecode.succeed (fun label providerId model tags apiKey -> ({
            Label = label
            ProviderId = providerId
            Model = model
            Tags = tags
            ApiKey = apiKey
        }: ProviderEntryInput))
        |> JsonDecode.apply (JsonDecode.field "Label" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ProviderId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "Model" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Tags" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.optionalField "ApiKey" JsonDecode.asString)

    /// Generated JSON decoder for `RoutingRule` — members by name, cases by case name, read off the type's own shape.
    let routingRule: JsonDecoder<RoutingRule> =
        JsonDecode.succeed (fun surface context entryLabel -> ({
            Surface = surface
            Context = context
            EntryLabel = entryLabel
        }: RoutingRule))
        |> JsonDecode.apply (JsonDecode.field "Surface" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "Context" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "EntryLabel" JsonDecode.asString)

    /// Generated JSON decoder for `ProviderVerificationOutcome` — members by name, cases by case name, read off the type's own shape.
    let providerVerificationOutcome: JsonDecoder<ProviderVerificationOutcome> =
        JsonDecode.union "ProviderVerificationOutcome" (function
            | "Verified" -> Some(JsonDecode.payload ((JsonDecode.list JsonDecode.asString) |> JsonDecode.map ProviderVerificationOutcome.Verified))
            | "Failed" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map ProviderVerificationOutcome.Failed))
            | _ -> None)

    /// Generated JSON decoder for `ModulePermission` — members by name, cases by case name, read off the type's own shape.
    let modulePermission: JsonDecoder<ModulePermission> =
        JsonDecode.union "ModulePermission" (function
            | "Read" -> Some(JsonDecode.case0 ModulePermission.Read)
            | "Write" -> Some(JsonDecode.case0 ModulePermission.Write)
            | "Admin" -> Some(JsonDecode.case0 ModulePermission.Admin)
            | "SchemaOnly" -> Some(JsonDecode.case0 ModulePermission.SchemaOnly)
            | _ -> None)

    /// Generated JSON decoder for `CreateServiceAccountRequest` — members by name, cases by case name, read off the type's own shape.
    let createServiceAccountRequest: JsonDecoder<CreateServiceAccountRequest> =
        JsonDecode.succeed (fun displayName permissions -> ({
            DisplayName = displayName
            Permissions = permissions
        }: CreateServiceAccountRequest))
        |> JsonDecode.apply (JsonDecode.field "DisplayName" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Permissions" (JsonDecode.asMap JsonDecode.Key.string (JsonDecode.list modulePermission)))

    /// Generated JSON decoder for `ServiceAccountStatus` — members by name, cases by case name, read off the type's own shape.
    let serviceAccountStatus: JsonDecoder<ServiceAccountStatus> =
        JsonDecode.union "ServiceAccountStatus" (function
            | "Active" -> Some(JsonDecode.case0 ServiceAccountStatus.Active)
            | "Disabled" -> Some(JsonDecode.case0 ServiceAccountStatus.Disabled)
            | _ -> None)

    /// Generated JSON decoder for `MintServiceAccountTokenRequest` — members by name, cases by case name, read off the type's own shape.
    let mintServiceAccountTokenRequest: JsonDecoder<MintServiceAccountTokenRequest> =
        JsonDecode.succeed (fun accountId displayName expiresAt -> ({
            AccountId = accountId
            DisplayName = displayName
            ExpiresAt = expiresAt
        }: MintServiceAccountTokenRequest))
        |> JsonDecode.apply (JsonDecode.field "AccountId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "DisplayName" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "ExpiresAt" JsonDecode.asDateTimeOffset)

    /// Generated JSON decoder for `TeamRole` — members by name, cases by case name, read off the type's own shape.
    let teamRole: JsonDecoder<TeamRole> =
        JsonDecode.union "TeamRole" (function
            | "Owner" -> Some(JsonDecode.case0 TeamRole.Owner)
            | "Admin" -> Some(JsonDecode.case0 TeamRole.Admin)
            | "Member" -> Some(JsonDecode.case0 TeamRole.Member)
            | _ -> None)

    /// Generated JSON decoder for `TeamInviteIssueRequest` — members by name, cases by case name, read off the type's own shape.
    let teamInviteIssueRequest: JsonDecoder<TeamInviteIssueRequest> =
        JsonDecode.succeed (fun teamId role expiresIn emailHint maxUses -> ({
            TeamId = teamId
            Role = role
            ExpiresIn = expiresIn
            EmailHint = emailHint
            MaxUses = maxUses
        }: TeamInviteIssueRequest))
        |> JsonDecode.apply (JsonDecode.field "TeamId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Role" teamRole)
        |> JsonDecode.apply (JsonDecode.optionalField "ExpiresIn" JsonDecode.asTimeSpan)
        |> JsonDecode.apply (JsonDecode.optionalField "EmailHint" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.optionalField "MaxUses" JsonDecode.asInt32)

    /// Generated JSON decoder for `PendingInviteIssueRequest` — members by name, cases by case name, read off the type's own shape.
    let pendingInviteIssueRequest: JsonDecoder<PendingInviteIssueRequest> =
        JsonDecode.succeed (fun teamId email role expiresIn -> ({
            TeamId = teamId
            Email = email
            Role = role
            ExpiresIn = expiresIn
        }: PendingInviteIssueRequest))
        |> JsonDecode.apply (JsonDecode.field "TeamId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Email" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Role" teamRole)
        |> JsonDecode.apply (JsonDecode.optionalField "ExpiresIn" JsonDecode.asTimeSpan)

    /// Generated JSON decoder for `AuthoredBy` — members by name, cases by case name, read off the type's own shape.
    let authoredBy: JsonDecoder<AuthoredBy> =
        JsonDecode.union "AuthoredBy" (function
            | "Human" -> Some(JsonDecode.case0 AuthoredBy.Human)
            | "AIWithApproval" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map AuthoredBy.AIWithApproval))
            | _ -> None)

    /// Generated JSON decoder for `BIFriendlyType` — members by name, cases by case name, read off the type's own shape.
    let biFriendlyType: JsonDecoder<BIFriendlyType> =
        JsonDecode.union "BIFriendlyType" (function
            | "String" -> Some(JsonDecode.case0 BIFriendlyType.String)
            | "Number" -> Some(JsonDecode.case0 BIFriendlyType.Number)
            | "Boolean" -> Some(JsonDecode.case0 BIFriendlyType.Boolean)
            | "Date" -> Some(JsonDecode.case0 BIFriendlyType.Date)
            | "DateTime" -> Some(JsonDecode.case0 BIFriendlyType.DateTime)
            | "Currency" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map BIFriendlyType.Currency))
            | "Percentage" -> Some(JsonDecode.payload (JsonDecode.asInt32 |> JsonDecode.map BIFriendlyType.Percentage))
            | "CountryCode" -> Some(JsonDecode.case0 BIFriendlyType.CountryCode)
            | "Enum" -> Some(JsonDecode.payload ((JsonDecode.list JsonDecode.asString) |> JsonDecode.map BIFriendlyType.Enum))
            | "Ref" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map BIFriendlyType.Ref))
            | "Id" -> Some(JsonDecode.case0 BIFriendlyType.Id)
            | "Email" -> Some(JsonDecode.case0 BIFriendlyType.Email)
            | "Url" -> Some(JsonDecode.case0 BIFriendlyType.Url)
            | _ -> None)

    /// Generated JSON decoder for `FieldSensitivity` — members by name, cases by case name, read off the type's own shape.
    let fieldSensitivity: JsonDecoder<FieldSensitivity> =
        JsonDecode.union "FieldSensitivity" (function
            | "Public" -> Some(JsonDecode.case0 FieldSensitivity.Public)
            | "Internal" -> Some(JsonDecode.case0 FieldSensitivity.Internal)
            | "PII" -> Some(JsonDecode.case0 FieldSensitivity.PII)
            | "PHI" -> Some(JsonDecode.case0 FieldSensitivity.PHI)
            | "Financial" -> Some(JsonDecode.case0 FieldSensitivity.Financial)
            | "Secret" -> Some(JsonDecode.case0 FieldSensitivity.Secret)
            | _ -> None)

    /// Generated JSON decoder for `UserSchemaField` — members by name, cases by case name, read off the type's own shape.
    let userSchemaField: JsonDecoder<UserSchemaField> =
        JsonDecode.succeed (fun name type' required description sensitivity -> ({
            Name = name
            Type = type'
            Required = required
            Description = description
            Sensitivity = sensitivity
        }: UserSchemaField))
        |> JsonDecode.apply (JsonDecode.field "Name" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Type" biFriendlyType)
        |> JsonDecode.apply (JsonDecode.field "Required" JsonDecode.asBool)
        |> JsonDecode.apply (JsonDecode.optionalField "Description" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Sensitivity" fieldSensitivity)

    /// Generated JSON decoder for `SchemaMigration` — members by name, cases by case name, read off the type's own shape.
    let schemaMigration: JsonDecoder<SchemaMigration> =
        JsonDecode.union "SchemaMigration" (function
            | "AddField" ->
                Some(
                    JsonDecode.fields
                        2
                        (JsonDecode.succeed (fun field defaultValue -> SchemaMigration.AddField(field, defaultValue))
                         |> JsonDecode.apply (JsonDecode.index 0 userSchemaField)
                         |> JsonDecode.apply (JsonDecode.index 1 JsonDecode.asString))
                )
            | "RemoveField" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map SchemaMigration.RemoveField))
            | "RenameField" ->
                Some(
                    JsonDecode.fields
                        2
                        (JsonDecode.succeed (fun fromName toName -> SchemaMigration.RenameField(fromName, toName))
                         |> JsonDecode.apply (JsonDecode.index 0 JsonDecode.asString)
                         |> JsonDecode.apply (JsonDecode.index 1 JsonDecode.asString))
                )
            | "TightenType" ->
                Some(
                    JsonDecode.fields
                        3
                        (JsonDecode.succeed (fun fieldName fromType toType -> SchemaMigration.TightenType(fieldName, fromType, toType))
                         |> JsonDecode.apply (JsonDecode.index 0 JsonDecode.asString)
                         |> JsonDecode.apply (JsonDecode.index 1 biFriendlyType)
                         |> JsonDecode.apply (JsonDecode.index 2 biFriendlyType))
                )
            | "LooseType" ->
                Some(
                    JsonDecode.fields
                        3
                        (JsonDecode.succeed (fun fieldName fromType toType -> SchemaMigration.LooseType(fieldName, fromType, toType))
                         |> JsonDecode.apply (JsonDecode.index 0 JsonDecode.asString)
                         |> JsonDecode.apply (JsonDecode.index 1 biFriendlyType)
                         |> JsonDecode.apply (JsonDecode.index 2 biFriendlyType))
                )
            | "ChangeRef" ->
                Some(
                    JsonDecode.fields
                        3
                        (JsonDecode.succeed (fun fieldName fromTypeId toTypeId -> SchemaMigration.ChangeRef(fieldName, fromTypeId, toTypeId))
                         |> JsonDecode.apply (JsonDecode.index 0 JsonDecode.asString)
                         |> JsonDecode.apply (JsonDecode.index 1 JsonDecode.asString)
                         |> JsonDecode.apply (JsonDecode.index 2 JsonDecode.asString))
                )
            | _ -> None)

    /// Generated JSON decoder for `UserAuthoredSchema` — members by name, cases by case name, read off the type's own shape.
    let userAuthoredSchema: JsonDecoder<UserAuthoredSchema> =
        JsonDecode.succeed (fun schemaId displayName description owner version versionLabel proposedBy evolvedFrom migrationPlan fields -> ({
            SchemaId = schemaId
            DisplayName = displayName
            Description = description
            Owner = owner
            Version = version
            VersionLabel = versionLabel
            ProposedBy = proposedBy
            EvolvedFrom = evolvedFrom
            MigrationPlan = migrationPlan
            Fields = fields
        }: UserAuthoredSchema))
        |> JsonDecode.apply (JsonDecode.field "SchemaId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "DisplayName" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Description" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Owner" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Version" JsonDecode.asInt32)
        |> JsonDecode.apply (JsonDecode.field "VersionLabel" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ProposedBy" authoredBy)
        |> JsonDecode.apply (JsonDecode.optionalField "EvolvedFrom" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "MigrationPlan" (JsonDecode.list schemaMigration))
        |> JsonDecode.apply (JsonDecode.field "Fields" (JsonDecode.list userSchemaField))

    /// Generated JSON decoder for `CreateWebhookRequest` — members by name, cases by case name, read off the type's own shape.
    let createWebhookRequest: JsonDecoder<CreateWebhookRequest> =
        JsonDecode.succeed (fun targetUrl secret eventTypes -> ({
            TargetUrl = targetUrl
            Secret = secret
            EventTypes = eventTypes
        }: CreateWebhookRequest))
        |> JsonDecode.apply (JsonDecode.field "TargetUrl" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Secret" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "EventTypes" (JsonDecode.list JsonDecode.asString))

    /// Generated JSON decoder for `WebhookStatus` — members by name, cases by case name, read off the type's own shape.
    let webhookStatus: JsonDecoder<WebhookStatus> =
        JsonDecode.union "WebhookStatus" (function
            | "Active" -> Some(JsonDecode.case0 WebhookStatus.Active)
            | "Paused" -> Some(JsonDecode.case0 WebhookStatus.Paused)
            | "Disabled" -> Some(JsonDecode.case0 WebhookStatus.Disabled)
            | _ -> None)

    /// Generated JSON decoder for `Trigger` — members by name, cases by case name, read off the type's own shape.
    let trigger: JsonDecoder<Trigger> =
        JsonDecode.union "Trigger" (function
            | "CronTrigger" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map Trigger.CronTrigger))
            | "OnEvent" -> Some(JsonDecode.payload (JsonDecode.asString |> JsonDecode.map Trigger.OnEvent))
            | "Manual" -> Some(JsonDecode.case0 Trigger.Manual)
            | _ -> None)

    /// Generated JSON decoder for `IdempotencyKey` — members by name, cases by case name, read off the type's own shape.
    let idempotencyKey: JsonDecoder<IdempotencyKey> =
        JsonDecode.succeed (fun key ttlSeconds -> ({
            Key = key
            TtlSeconds = ttlSeconds
        }: IdempotencyKey))
        |> JsonDecode.apply (JsonDecode.field "Key" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "TtlSeconds" JsonDecode.asInt32)

    /// Generated JSON decoder for `JobRetryPolicy` — members by name, cases by case name, read off the type's own shape.
    let jobRetryPolicy: JsonDecoder<JobRetryPolicy> =
        JsonDecode.succeed (fun maxAttempts initialBackoff maxBackoff deadLetterDestination -> ({
            MaxAttempts = maxAttempts
            InitialBackoff = initialBackoff
            MaxBackoff = maxBackoff
            DeadLetterDestination = deadLetterDestination
        }: JobRetryPolicy))
        |> JsonDecode.apply (JsonDecode.field "MaxAttempts" JsonDecode.asInt32)
        |> JsonDecode.apply (JsonDecode.field "InitialBackoff" JsonDecode.asTimeSpan)
        |> JsonDecode.apply (JsonDecode.field "MaxBackoff" JsonDecode.asTimeSpan)
        |> JsonDecode.apply (JsonDecode.optionalField "DeadLetterDestination" JsonDecode.asString)

    /// Generated JSON decoder for `JobPrecision` — members by name, cases by case name, read off the type's own shape.
    let jobPrecision: JsonDecoder<JobPrecision> =
        JsonDecode.union "JobPrecision" (function
            | "Second" -> Some(JsonDecode.case0 JobPrecision.Second)
            | "Minute" -> Some(JsonDecode.case0 JobPrecision.Minute)
            | _ -> None)

    /// Generated JSON decoder for `JobRegistration` — members by name, cases by case name, read off the type's own shape.
    let jobRegistration: JsonDecoder<JobRegistration> =
        JsonDecode.succeed (fun scopeId handler payload trigger idempotency retryPolicy shardKey precision createdBy tags -> ({
            ScopeId = scopeId
            Handler = handler
            Payload = payload
            Trigger = trigger
            Idempotency = idempotency
            RetryPolicy = retryPolicy
            ShardKey = shardKey
            Precision = precision
            CreatedBy = createdBy
            Tags = tags
        }: JobRegistration))
        |> JsonDecode.apply (JsonDecode.field "ScopeId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Handler" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Payload" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Trigger" trigger)
        |> JsonDecode.apply (JsonDecode.optionalField "Idempotency" idempotencyKey)
        |> JsonDecode.apply (JsonDecode.field "RetryPolicy" jobRetryPolicy)
        |> JsonDecode.apply (JsonDecode.optionalField "ShardKey" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Precision" jobPrecision)
        |> JsonDecode.apply (JsonDecode.field "CreatedBy" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Tags" (JsonDecode.asMap JsonDecode.Key.string JsonDecode.asString))

    /// Generated JSON decoder for `ModelExecutionGate` — members by name, cases by case name, read off the type's own shape.
    let modelExecutionGate: JsonDecoder<ModelExecutionGate> =
        JsonDecode.succeed (fun name threshold direction -> ({
            Name = name
            Threshold = threshold
            Direction = direction
        }: ModelExecutionGate))
        |> JsonDecode.apply (JsonDecode.field "Name" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Threshold" JsonDecode.asFloat)
        |> JsonDecode.apply (JsonDecode.field "Direction" JsonDecode.asString)

    /// Generated JSON decoder for `SubmitterClass` — members by name, cases by case name, read off the type's own shape.
    let submitterClass: JsonDecoder<SubmitterClass> =
        JsonDecode.union "SubmitterClass" (function
            | "Human" -> Some(JsonDecode.case0 SubmitterClass.Human)
            | "Scheduled" -> Some(JsonDecode.case0 SubmitterClass.Scheduled)
            | "AgentInitiated" -> Some(JsonDecode.case0 SubmitterClass.AgentInitiated)
            | _ -> None)

    /// Generated JSON decoder for `ModelExecutionFitSubmission` — members by name, cases by case name, read off the type's own shape.
    let modelExecutionFitSubmission: JsonDecoder<ModelExecutionFitSubmission> =
        JsonDecode.succeed (fun datasetId datasetVersion specPayload specHash specHashAlgorithm providerKind seed gates submitterClass -> ({
            DatasetId = datasetId
            DatasetVersion = datasetVersion
            SpecPayload = specPayload
            SpecHash = specHash
            SpecHashAlgorithm = specHashAlgorithm
            ProviderKind = providerKind
            Seed = seed
            Gates = gates
            SubmitterClass = submitterClass
        }: ModelExecutionFitSubmission))
        |> JsonDecode.apply (JsonDecode.field "DatasetId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "DatasetVersion" JsonDecode.asInt32)
        |> JsonDecode.apply (JsonDecode.field "SpecPayload" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "SpecHash" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "SpecHashAlgorithm" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "ProviderKind" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Seed" JsonDecode.asInt64)
        |> JsonDecode.apply (JsonDecode.field "Gates" (JsonDecode.list modelExecutionGate))
        |> JsonDecode.apply (JsonDecode.field "SubmitterClass" submitterClass)

    /// Generated JSON decoder for `ModelExecutionBatchSubmission` — members by name, cases by case name, read off the type's own shape.
    let modelExecutionBatchSubmission: JsonDecoder<ModelExecutionBatchSubmission> =
        JsonDecode.succeed (fun batchId items -> ({
            BatchId = batchId
            Items = items
        }: ModelExecutionBatchSubmission))
        |> JsonDecode.apply (JsonDecode.field "BatchId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "Items" (JsonDecode.list modelExecutionFitSubmission))

    /// Generated JSON decoder for `ModelExecutionOutcomeQuery` — members by name, cases by case name, read off the type's own shape.
    let modelExecutionOutcomeQuery: JsonDecoder<ModelExecutionOutcomeQuery> =
        JsonDecode.succeed (fun specHashes datasetVersions statuses batchId -> ({
            SpecHashes = specHashes
            DatasetVersions = datasetVersions
            Statuses = statuses
            BatchId = batchId
        }: ModelExecutionOutcomeQuery))
        |> JsonDecode.apply (JsonDecode.field "SpecHashes" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.field "DatasetVersions" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.field "Statuses" (JsonDecode.list JsonDecode.asString))
        |> JsonDecode.apply (JsonDecode.optionalField "BatchId" JsonDecode.asString)

    /// Generated JSON decoder for `ModelExecutionScoreRequest` — members by name, cases by case name, read off the type's own shape.
    let modelExecutionScoreRequest: JsonDecoder<ModelExecutionScoreRequest> =
        JsonDecode.succeed (fun artifactKeyHash inputDatasetId inputVersion outputDatasetId -> ({
            ArtifactKeyHash = artifactKeyHash
            InputDatasetId = inputDatasetId
            InputVersion = inputVersion
            OutputDatasetId = outputDatasetId
        }: ModelExecutionScoreRequest))
        |> JsonDecode.apply (JsonDecode.field "ArtifactKeyHash" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "InputDatasetId" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "InputVersion" JsonDecode.asInt32)
        |> JsonDecode.apply (JsonDecode.field "OutputDatasetId" JsonDecode.asString)

    /// Generated JSON decoder for `ModuleExposure` — members by name, cases by case name, read off the type's own shape.
    let moduleExposure: JsonDecoder<ModuleExposure> =
        JsonDecode.union "ModuleExposure" (function
            | "Available" -> Some(JsonDecode.case0 ModuleExposure.Available)
            | "Hidden" -> Some(JsonDecode.case0 ModuleExposure.Hidden)
            | "Unavailable" -> Some(JsonDecode.case0 ModuleExposure.Unavailable)
            | _ -> None)

    /// Generated JSON decoder for `PlatformKnowledgeBaseMode` — members by name, cases by case name, read off the type's own shape.
    let platformKnowledgeBaseMode: JsonDecoder<PlatformKnowledgeBaseMode> =
        JsonDecode.union "PlatformKnowledgeBaseMode" (function
            | "NoPlatformKnowledgeBase" -> Some(JsonDecode.case0 PlatformKnowledgeBaseMode.NoPlatformKnowledgeBase)
            | "EnabledPlatformKnowledgeBase" -> Some(JsonDecode.case0 PlatformKnowledgeBaseMode.EnabledPlatformKnowledgeBase)
            | _ -> None)

    /// Generated JSON decoder for `CreateTeamRequest` — members by name, cases by case name, read off the type's own shape.
    let createTeamRequest: JsonDecoder<CreateTeamRequest> =
        JsonDecode.succeed (fun name initialOwnerUserId -> ({
            Name = name
            InitialOwnerUserId = initialOwnerUserId
        }: CreateTeamRequest))
        |> JsonDecode.apply (JsonDecode.field "Name" JsonDecode.asString)
        |> JsonDecode.apply (JsonDecode.field "InitialOwnerUserId" JsonDecode.asString)

    /// Generated JSON decoder for `UsageDateRange` — members by name, cases by case name, read off the type's own shape.
    let usageDateRange: JsonDecoder<UsageDateRange> =
        JsonDecode.succeed (fun from to' -> ({
            From = from
            To = to'
        }: UsageDateRange))
        |> JsonDecode.apply (JsonDecode.field "From" JsonDecode.asDateTime)
        |> JsonDecode.apply (JsonDecode.field "To" JsonDecode.asDateTime)

    /// Generated JSON decoder for `UsageGrouping` — members by name, cases by case name, read off the type's own shape.
    let usageGrouping: JsonDecoder<UsageGrouping> =
        JsonDecode.union "UsageGrouping" (function
            | "ByDay" -> Some(JsonDecode.case0 UsageGrouping.ByDay)
            | "ByMonth" -> Some(JsonDecode.case0 UsageGrouping.ByMonth)
            | "ByResourceKind" -> Some(JsonDecode.case0 UsageGrouping.ByResourceKind)
            | "ByUser" -> Some(JsonDecode.case0 UsageGrouping.ByUser)
            | _ -> None)

    /// The `(API record, argument type)` pairs this module registers, in
    /// registration order — each decoder scoped to the one record whose
    /// methods take it (Phase 839), never to every record of the same type.
    let covered: (string option * string) list = [
        Some "IConversionApi", typeof<string>.FullName
        Some "IConversionApi", typeof<ColumnMappingTypes.Conversion>.FullName
        Some "IConversionApi", typeof<Tuple<string, string>>.FullName
        Some "IConversionApi", typeof<ColumnMappingTypes.ConversionRecord>.FullName
        Some "IConversionApi", typeof<ColumnMappingTypes.DryRunValidationRequest>.FullName
        Some "FileManagementApi", typeof<DataManagementTypes.FileUploadRequest>.FullName
        Some "FileManagementApi", typeof<string>.FullName
        Some "BudgetAccount", typeof<BudgetDenial>.FullName
        Some "BudgetAccount", typeof<BudgetWarning>.FullName
        Some "IDataSubjectRequestApi", typeof<DataSubjectRequestApi.ExportRequestInput>.FullName
        Some "IDataSubjectRequestApi", typeof<DataSubjectRequestApi.ErasureRequestInput>.FullName
        Some "IDataSubjectRequestApi", typeof<string>.FullName
        Some "IAuditViewApi", typeof<AuditTrailQuery>.FullName
        Some "ICompositionInspectorApi", typeof<InspectorPanel>.FullName
        Some "IConfigApi", typeof<string>.FullName
        Some "IConfigApi", typeof<Tuple<string, Map<string, string>>>.FullName
        Some "IDataIngestionApi", typeof<string>.FullName
        Some "IDataIngestionApi", typeof<DataSourceConfig>.FullName
        Some "IDataIngestionApi", typeof<Tuple<string, string>>.FullName
        Some "IDataIngestionApi", typeof<Tuple<string, int>>.FullName
        Some "IDataMigrationApi", typeof<string>.FullName
        Some "IExternalContactApi", typeof<string>.FullName
        Some "IExternalContactApi", typeof<CreateExternalContactRequest>.FullName
        Some "IExternalContactApi", typeof<UpdateExternalContactRequest>.FullName
        Some "IExternalContactApi", typeof<RecordOptInRequest>.FullName
        Some "IExternalContactApi", typeof<WithdrawOptInRequest>.FullName
        Some "IFeatureFlagApi", typeof<Tuple<string, FlagValue>>.FullName
        Some "IFeatureFlagApi", typeof<string>.FullName
        Some "IHomeOverviewApi", typeof<string>.FullName
        Some "IHomeOverviewApi", typeof<PinRequest>.FullName
        Some "IModuleQueryBusApi", typeof<ModuleQueryRequest>.FullName
        Some "IModuleVisibilityApi", typeof<ModuleVisibilityProfileInput>.FullName
        Some "INotificationPreferenceApi", typeof<UserNotificationPreferences>.FullName
        Some "IPlatformTenantApi", typeof<Tuple<string, string, ProvisioningRequest>>.FullName
        Some "IPlatformTenantApi", typeof<Tuple<string, string, string>>.FullName
        Some "IPlatformTenantApi", typeof<string>.FullName
        Some "IPlatformTenantApi", typeof<Tuple<string, string>>.FullName
        Some "IPlatformTenantApi", typeof<Tuple<string, string, string, string>>.FullName
        Some "IPlatformTenantApi", typeof<Tuple<string, string, int, string>>.FullName
        Some "IPresenceApi", typeof<PresenceLocation>.FullName
        Some "IPresenceApi", typeof<EntityLockRef>.FullName
        Some "IProvenanceQueryApi", typeof<WireProvenanceRef>.FullName
        Some "IProvenanceQueryApi", typeof<WireProvenanceChainRequest>.FullName
        Some "IProviderProfileApi", typeof<ProviderEntryInput>.FullName
        Some "IProviderProfileApi", typeof<string>.FullName
        Some "IProviderProfileApi", typeof<RoutingRule>.FullName
        Some "IProviderProfileApi", typeof<Tuple<string, string option>>.FullName
        Some "IProviderProfileApi", typeof<string list>.FullName
        Some "IProviderProfileApi", typeof<Tuple<string, ProviderVerificationOutcome>>.FullName
        Some "IServiceAccountApi", typeof<CreateServiceAccountRequest>.FullName
        Some "IServiceAccountApi", typeof<Tuple<string, ServiceAccountStatus>>.FullName
        Some "IServiceAccountApi", typeof<Tuple<string, Map<string, ModulePermission list>>>.FullName
        Some "IServiceAccountApi", typeof<string>.FullName
        Some "IServiceAccountApi", typeof<MintServiceAccountTokenRequest>.FullName
        Some "ISessionApi", typeof<string>.FullName
        Some "ITeamInviteApi", typeof<TeamInviteIssueRequest>.FullName
        Some "ITeamInviteApi", typeof<string>.FullName
        Some "ITeamInviteApi", typeof<PendingInviteIssueRequest>.FullName
        Some "IUserDirectoryApi", typeof<Tuple<string, int>>.FullName
        Some "IUserDirectoryApi", typeof<string list>.FullName
        Some "IUserSchemaApi", typeof<string>.FullName
        Some "IUserSchemaApi", typeof<Tuple<string, int>>.FullName
        Some "IUserSchemaApi", typeof<UserAuthoredSchema>.FullName
        Some "IUserSchemaApi", typeof<Tuple<string, SchemaMigration list>>.FullName
        Some "IWebhookApi", typeof<CreateWebhookRequest>.FullName
        Some "IWebhookApi", typeof<Guid>.FullName
        Some "IWebhookApi", typeof<Tuple<Guid, WebhookStatus>>.FullName
        Some "JobApi", typeof<Guid>.FullName
        Some "JobApi", typeof<Tuple<Guid, int>>.FullName
        Some "JobApi", typeof<JobRegistration>.FullName
        Some "ModelExecutionApi", typeof<ModelExecutionFitSubmission>.FullName
        Some "ModelExecutionApi", typeof<ModelExecutionBatchSubmission>.FullName
        Some "ModelExecutionApi", typeof<string>.FullName
        Some "ModelExecutionApi", typeof<Tuple<ModelExecutionOutcomeQuery, string option, int>>.FullName
        Some "ModelExecutionApi", typeof<Tuple<string, int>>.FullName
        Some "ModelExecutionApi", typeof<ModelExecutionScoreRequest>.FullName
        Some "PermissionApi", typeof<string>.FullName
        Some "PermissionApi", typeof<Tuple<string, string, string, ModulePermission list>>.FullName
        Some "PermissionApi", typeof<Tuple<string, Map<string, ModulePermission list>>>.FullName
        Some "PermissionApi", typeof<Tuple<string, string, ModuleExposure>>.FullName
        Some "PlatformAdminApi", typeof<string>.FullName
        Some "PlatformAdminApi", typeof<PlatformKnowledgeBaseMode>.FullName
        Some "TeamApi", typeof<string>.FullName
        Some "TeamApi", typeof<CreateTeamRequest>.FullName
        Some "TeamApi", typeof<Tuple<string, string, TeamRole>>.FullName
        Some "TeamApi", typeof<Tuple<string, string>>.FullName
        Some "IUsageQueryApi", typeof<Tuple<string option, UsageDateRange option>>.FullName
        Some "IUsageQueryApi", typeof<UsageGrouping>.FullName
        Some "IUsageQueryApi", typeof<UsageDateRange option>.FullName
    ]

    /// The API records every one of whose arguments this module decodes
    /// through the JSON algebra — the argument-side census. A record taking
    /// no argument at all is included: nothing of it reaches the converter set.
    let coveredApiRecords: string list = [
        "IConversionApi"
        "FileManagementApi"
        "AccessibilityApi"
        "BudgetAccount"
        "DataCatalogApi"
        "IDataSubjectRequestApi"
        "IAuditViewApi"
        "ICompositionInspectorApi"
        "IConfigApi"
        "IDataIngestionApi"
        "IDataMigrationApi"
        "IDeploymentReadinessApi"
        "IDeploymentVerificationApi"
        "IExternalContactApi"
        "IFeatureFlagApi"
        "IHealthMonitorApi"
        "IHomeOverviewApi"
        "IModuleQueryBusApi"
        "IModuleVisibilityApi"
        "INotificationPreferenceApi"
        "IPlatformTenantApi"
        "IPresenceApi"
        "IProvenanceQueryApi"
        "IProviderProfileApi"
        "IServiceAccountApi"
        "IServiceStatusBoardApi"
        "ISessionApi"
        "ITeamInviteApi"
        "IUserDirectoryApi"
        "IUserSchemaApi"
        "IWebhookApi"
        "JobApi"
        "MaintenanceApi"
        "ModelExecutionApi"
        "PermissionApi"
        "PlatformAdminApi"
        "PlatformInfoApi"
        "TeamApi"
        "IUsageQueryApi"
    ]

    /// Register every decoder above, each scoped to its API record. Idempotent,
    /// and explicit — a static initialiser would fire at a moment nothing
    /// states, so a deployment could not say whether the algebra path was live.
    let registerAll () : unit =
        JsonDecoders.registerFor<string> "IConversionApi" JsonDecode.asString
        JsonDecoders.registerFor<ColumnMappingTypes.Conversion> "IConversionApi" conversion
        JsonDecoders.registerFor<Tuple<string, string>> "IConversionApi" (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asString)
        JsonDecoders.registerFor<ColumnMappingTypes.ConversionRecord> "IConversionApi" conversionRecord
        JsonDecoders.registerFor<ColumnMappingTypes.DryRunValidationRequest> "IConversionApi" dryRunValidationRequest
        JsonDecoders.registerFor<DataManagementTypes.FileUploadRequest> "FileManagementApi" fileUploadRequest
        JsonDecoders.registerFor<string> "FileManagementApi" JsonDecode.asString
        JsonDecoders.registerFor<BudgetDenial> "BudgetAccount" budgetDenial
        JsonDecoders.registerFor<BudgetWarning> "BudgetAccount" budgetWarning
        JsonDecoders.registerFor<DataSubjectRequestApi.ExportRequestInput> "IDataSubjectRequestApi" exportRequestInput
        JsonDecoders.registerFor<DataSubjectRequestApi.ErasureRequestInput> "IDataSubjectRequestApi" erasureRequestInput
        JsonDecoders.registerFor<string> "IDataSubjectRequestApi" JsonDecode.asString
        JsonDecoders.registerFor<AuditTrailQuery> "IAuditViewApi" auditTrailQuery
        JsonDecoders.registerFor<InspectorPanel> "ICompositionInspectorApi" inspectorPanel
        JsonDecoders.registerFor<string> "IConfigApi" JsonDecode.asString
        JsonDecoders.registerFor<Tuple<string, Map<string, string>>> "IConfigApi" (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.asMap JsonDecode.Key.string JsonDecode.asString))
        JsonDecoders.registerFor<string> "IDataIngestionApi" JsonDecode.asString
        JsonDecoders.registerFor<DataSourceConfig> "IDataIngestionApi" dataSourceConfig
        JsonDecoders.registerFor<Tuple<string, string>> "IDataIngestionApi" (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asString)
        JsonDecoders.registerFor<Tuple<string, int>> "IDataIngestionApi" (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asInt32)
        JsonDecoders.registerFor<string> "IDataMigrationApi" JsonDecode.asString
        JsonDecoders.registerFor<string> "IExternalContactApi" JsonDecode.asString
        JsonDecoders.registerFor<CreateExternalContactRequest> "IExternalContactApi" createExternalContactRequest
        JsonDecoders.registerFor<UpdateExternalContactRequest> "IExternalContactApi" updateExternalContactRequest
        JsonDecoders.registerFor<RecordOptInRequest> "IExternalContactApi" recordOptInRequest
        JsonDecoders.registerFor<WithdrawOptInRequest> "IExternalContactApi" withdrawOptInRequest
        JsonDecoders.registerFor<Tuple<string, FlagValue>> "IFeatureFlagApi" (JsonDecode.tuple2 JsonDecode.asString flagValue)
        JsonDecoders.registerFor<string> "IFeatureFlagApi" JsonDecode.asString
        JsonDecoders.registerFor<string> "IHomeOverviewApi" JsonDecode.asString
        JsonDecoders.registerFor<PinRequest> "IHomeOverviewApi" pinRequest
        JsonDecoders.registerFor<ModuleQueryRequest> "IModuleQueryBusApi" moduleQueryRequest
        JsonDecoders.registerFor<ModuleVisibilityProfileInput> "IModuleVisibilityApi" moduleVisibilityProfileInput
        JsonDecoders.registerFor<UserNotificationPreferences> "INotificationPreferenceApi" userNotificationPreferences
        JsonDecoders.registerFor<Tuple<string, string, ProvisioningRequest>> "IPlatformTenantApi" (JsonDecode.tuple3 JsonDecode.asString JsonDecode.asString provisioningRequest)
        JsonDecoders.registerFor<Tuple<string, string, string>> "IPlatformTenantApi" (JsonDecode.tuple3 JsonDecode.asString JsonDecode.asString JsonDecode.asString)
        JsonDecoders.registerFor<string> "IPlatformTenantApi" JsonDecode.asString
        JsonDecoders.registerFor<Tuple<string, string>> "IPlatformTenantApi" (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asString)
        JsonDecoders.registerFor<Tuple<string, string, string, string>> "IPlatformTenantApi" (JsonDecode.tuple4 JsonDecode.asString JsonDecode.asString JsonDecode.asString JsonDecode.asString)
        JsonDecoders.registerFor<Tuple<string, string, int, string>> "IPlatformTenantApi" (JsonDecode.tuple4 JsonDecode.asString JsonDecode.asString JsonDecode.asInt32 JsonDecode.asString)
        JsonDecoders.registerFor<PresenceLocation> "IPresenceApi" presenceLocation
        JsonDecoders.registerFor<EntityLockRef> "IPresenceApi" entityLockRef
        JsonDecoders.registerFor<WireProvenanceRef> "IProvenanceQueryApi" wireProvenanceRef
        JsonDecoders.registerFor<WireProvenanceChainRequest> "IProvenanceQueryApi" wireProvenanceChainRequest
        JsonDecoders.registerFor<ProviderEntryInput> "IProviderProfileApi" providerEntryInput
        JsonDecoders.registerFor<string> "IProviderProfileApi" JsonDecode.asString
        JsonDecoders.registerFor<RoutingRule> "IProviderProfileApi" routingRule
        JsonDecoders.registerFor<Tuple<string, string option>> "IProviderProfileApi" (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.option JsonDecode.asString))
        JsonDecoders.registerFor<string list> "IProviderProfileApi" (JsonDecode.list JsonDecode.asString)
        JsonDecoders.registerFor<Tuple<string, ProviderVerificationOutcome>> "IProviderProfileApi" (JsonDecode.tuple2 JsonDecode.asString providerVerificationOutcome)
        JsonDecoders.registerFor<CreateServiceAccountRequest> "IServiceAccountApi" createServiceAccountRequest
        JsonDecoders.registerFor<Tuple<string, ServiceAccountStatus>> "IServiceAccountApi" (JsonDecode.tuple2 JsonDecode.asString serviceAccountStatus)
        JsonDecoders.registerFor<Tuple<string, Map<string, ModulePermission list>>> "IServiceAccountApi" (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.asMap JsonDecode.Key.string (JsonDecode.list modulePermission)))
        JsonDecoders.registerFor<string> "IServiceAccountApi" JsonDecode.asString
        JsonDecoders.registerFor<MintServiceAccountTokenRequest> "IServiceAccountApi" mintServiceAccountTokenRequest
        JsonDecoders.registerFor<string> "ISessionApi" JsonDecode.asString
        JsonDecoders.registerFor<TeamInviteIssueRequest> "ITeamInviteApi" teamInviteIssueRequest
        JsonDecoders.registerFor<string> "ITeamInviteApi" JsonDecode.asString
        JsonDecoders.registerFor<PendingInviteIssueRequest> "ITeamInviteApi" pendingInviteIssueRequest
        JsonDecoders.registerFor<Tuple<string, int>> "IUserDirectoryApi" (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asInt32)
        JsonDecoders.registerFor<string list> "IUserDirectoryApi" (JsonDecode.list JsonDecode.asString)
        JsonDecoders.registerFor<string> "IUserSchemaApi" JsonDecode.asString
        JsonDecoders.registerFor<Tuple<string, int>> "IUserSchemaApi" (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asInt32)
        JsonDecoders.registerFor<UserAuthoredSchema> "IUserSchemaApi" userAuthoredSchema
        JsonDecoders.registerFor<Tuple<string, SchemaMigration list>> "IUserSchemaApi" (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.list schemaMigration))
        JsonDecoders.registerFor<CreateWebhookRequest> "IWebhookApi" createWebhookRequest
        JsonDecoders.registerFor<Guid> "IWebhookApi" JsonDecode.asGuid
        JsonDecoders.registerFor<Tuple<Guid, WebhookStatus>> "IWebhookApi" (JsonDecode.tuple2 JsonDecode.asGuid webhookStatus)
        JsonDecoders.registerFor<Guid> "JobApi" JsonDecode.asGuid
        JsonDecoders.registerFor<Tuple<Guid, int>> "JobApi" (JsonDecode.tuple2 JsonDecode.asGuid JsonDecode.asInt32)
        JsonDecoders.registerFor<JobRegistration> "JobApi" jobRegistration
        JsonDecoders.registerFor<ModelExecutionFitSubmission> "ModelExecutionApi" modelExecutionFitSubmission
        JsonDecoders.registerFor<ModelExecutionBatchSubmission> "ModelExecutionApi" modelExecutionBatchSubmission
        JsonDecoders.registerFor<string> "ModelExecutionApi" JsonDecode.asString
        JsonDecoders.registerFor<Tuple<ModelExecutionOutcomeQuery, string option, int>> "ModelExecutionApi" (JsonDecode.tuple3 modelExecutionOutcomeQuery (JsonDecode.option JsonDecode.asString) JsonDecode.asInt32)
        JsonDecoders.registerFor<Tuple<string, int>> "ModelExecutionApi" (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asInt32)
        JsonDecoders.registerFor<ModelExecutionScoreRequest> "ModelExecutionApi" modelExecutionScoreRequest
        JsonDecoders.registerFor<string> "PermissionApi" JsonDecode.asString
        JsonDecoders.registerFor<Tuple<string, string, string, ModulePermission list>> "PermissionApi" (JsonDecode.tuple4 JsonDecode.asString JsonDecode.asString JsonDecode.asString (JsonDecode.list modulePermission))
        JsonDecoders.registerFor<Tuple<string, Map<string, ModulePermission list>>> "PermissionApi" (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.asMap JsonDecode.Key.string (JsonDecode.list modulePermission)))
        JsonDecoders.registerFor<Tuple<string, string, ModuleExposure>> "PermissionApi" (JsonDecode.tuple3 JsonDecode.asString JsonDecode.asString moduleExposure)
        JsonDecoders.registerFor<string> "PlatformAdminApi" JsonDecode.asString
        JsonDecoders.registerFor<PlatformKnowledgeBaseMode> "PlatformAdminApi" platformKnowledgeBaseMode
        JsonDecoders.registerFor<string> "TeamApi" JsonDecode.asString
        JsonDecoders.registerFor<CreateTeamRequest> "TeamApi" createTeamRequest
        JsonDecoders.registerFor<Tuple<string, string, TeamRole>> "TeamApi" (JsonDecode.tuple3 JsonDecode.asString JsonDecode.asString teamRole)
        JsonDecoders.registerFor<Tuple<string, string>> "TeamApi" (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asString)
        JsonDecoders.registerFor<Tuple<string option, UsageDateRange option>> "IUsageQueryApi" (JsonDecode.tuple2 (JsonDecode.option JsonDecode.asString) (JsonDecode.option usageDateRange))
        JsonDecoders.registerFor<UsageGrouping> "IUsageQueryApi" usageGrouping
        JsonDecoders.registerFor<UsageDateRange option> "IUsageQueryApi" (JsonDecode.option usageDateRange)

#if !FABLE_COMPILER
    /// Phase 840's gate over every registration above: each decoder beside
    /// `oracle` (the shipped one is `FableConverters.decoderOracle`) over
    /// `draws` draws of its own type from `seed`, keyed as `covered` is.
    let verifyAll
        (oracle: JsonDecoderOracle)
        (draws: int)
        (seed: int)
        : ((string option * string) * Result<JsonDecoderVerification, DecoderRefusal>) list =
        [
            (Some "IConversionApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IConversionApi", typeof<ColumnMappingTypes.Conversion>.FullName), JsonDecoders.verifyWith<ColumnMappingTypes.Conversion> oracle draws seed conversion
            (Some "IConversionApi", typeof<Tuple<string, string>>.FullName), JsonDecoders.verifyWith<Tuple<string, string>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asString)
            (Some "IConversionApi", typeof<ColumnMappingTypes.ConversionRecord>.FullName), JsonDecoders.verifyWith<ColumnMappingTypes.ConversionRecord> oracle draws seed conversionRecord
            (Some "IConversionApi", typeof<ColumnMappingTypes.DryRunValidationRequest>.FullName), JsonDecoders.verifyWith<ColumnMappingTypes.DryRunValidationRequest> oracle draws seed dryRunValidationRequest
            (Some "FileManagementApi", typeof<DataManagementTypes.FileUploadRequest>.FullName), JsonDecoders.verifyWith<DataManagementTypes.FileUploadRequest> oracle draws seed fileUploadRequest
            (Some "FileManagementApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "BudgetAccount", typeof<BudgetDenial>.FullName), JsonDecoders.verifyWith<BudgetDenial> oracle draws seed budgetDenial
            (Some "BudgetAccount", typeof<BudgetWarning>.FullName), JsonDecoders.verifyWith<BudgetWarning> oracle draws seed budgetWarning
            (Some "IDataSubjectRequestApi", typeof<DataSubjectRequestApi.ExportRequestInput>.FullName), JsonDecoders.verifyWith<DataSubjectRequestApi.ExportRequestInput> oracle draws seed exportRequestInput
            (Some "IDataSubjectRequestApi", typeof<DataSubjectRequestApi.ErasureRequestInput>.FullName), JsonDecoders.verifyWith<DataSubjectRequestApi.ErasureRequestInput> oracle draws seed erasureRequestInput
            (Some "IDataSubjectRequestApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IAuditViewApi", typeof<AuditTrailQuery>.FullName), JsonDecoders.verifyWith<AuditTrailQuery> oracle draws seed auditTrailQuery
            (Some "ICompositionInspectorApi", typeof<InspectorPanel>.FullName), JsonDecoders.verifyWith<InspectorPanel> oracle draws seed inspectorPanel
            (Some "IConfigApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IConfigApi", typeof<Tuple<string, Map<string, string>>>.FullName), JsonDecoders.verifyWith<Tuple<string, Map<string, string>>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.asMap JsonDecode.Key.string JsonDecode.asString))
            (Some "IDataIngestionApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IDataIngestionApi", typeof<DataSourceConfig>.FullName), JsonDecoders.verifyWith<DataSourceConfig> oracle draws seed dataSourceConfig
            (Some "IDataIngestionApi", typeof<Tuple<string, string>>.FullName), JsonDecoders.verifyWith<Tuple<string, string>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asString)
            (Some "IDataIngestionApi", typeof<Tuple<string, int>>.FullName), JsonDecoders.verifyWith<Tuple<string, int>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asInt32)
            (Some "IDataMigrationApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IExternalContactApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IExternalContactApi", typeof<CreateExternalContactRequest>.FullName), JsonDecoders.verifyWith<CreateExternalContactRequest> oracle draws seed createExternalContactRequest
            (Some "IExternalContactApi", typeof<UpdateExternalContactRequest>.FullName), JsonDecoders.verifyWith<UpdateExternalContactRequest> oracle draws seed updateExternalContactRequest
            (Some "IExternalContactApi", typeof<RecordOptInRequest>.FullName), JsonDecoders.verifyWith<RecordOptInRequest> oracle draws seed recordOptInRequest
            (Some "IExternalContactApi", typeof<WithdrawOptInRequest>.FullName), JsonDecoders.verifyWith<WithdrawOptInRequest> oracle draws seed withdrawOptInRequest
            (Some "IFeatureFlagApi", typeof<Tuple<string, FlagValue>>.FullName), JsonDecoders.verifyWith<Tuple<string, FlagValue>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString flagValue)
            (Some "IFeatureFlagApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IHomeOverviewApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IHomeOverviewApi", typeof<PinRequest>.FullName), JsonDecoders.verifyWith<PinRequest> oracle draws seed pinRequest
            (Some "IModuleQueryBusApi", typeof<ModuleQueryRequest>.FullName), JsonDecoders.verifyWith<ModuleQueryRequest> oracle draws seed moduleQueryRequest
            (Some "IModuleVisibilityApi", typeof<ModuleVisibilityProfileInput>.FullName), JsonDecoders.verifyWith<ModuleVisibilityProfileInput> oracle draws seed moduleVisibilityProfileInput
            (Some "INotificationPreferenceApi", typeof<UserNotificationPreferences>.FullName), JsonDecoders.verifyWith<UserNotificationPreferences> oracle draws seed userNotificationPreferences
            (Some "IPlatformTenantApi", typeof<Tuple<string, string, ProvisioningRequest>>.FullName), JsonDecoders.verifyWith<Tuple<string, string, ProvisioningRequest>> oracle draws seed (JsonDecode.tuple3 JsonDecode.asString JsonDecode.asString provisioningRequest)
            (Some "IPlatformTenantApi", typeof<Tuple<string, string, string>>.FullName), JsonDecoders.verifyWith<Tuple<string, string, string>> oracle draws seed (JsonDecode.tuple3 JsonDecode.asString JsonDecode.asString JsonDecode.asString)
            (Some "IPlatformTenantApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IPlatformTenantApi", typeof<Tuple<string, string>>.FullName), JsonDecoders.verifyWith<Tuple<string, string>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asString)
            (Some "IPlatformTenantApi", typeof<Tuple<string, string, string, string>>.FullName), JsonDecoders.verifyWith<Tuple<string, string, string, string>> oracle draws seed (JsonDecode.tuple4 JsonDecode.asString JsonDecode.asString JsonDecode.asString JsonDecode.asString)
            (Some "IPlatformTenantApi", typeof<Tuple<string, string, int, string>>.FullName), JsonDecoders.verifyWith<Tuple<string, string, int, string>> oracle draws seed (JsonDecode.tuple4 JsonDecode.asString JsonDecode.asString JsonDecode.asInt32 JsonDecode.asString)
            (Some "IPresenceApi", typeof<PresenceLocation>.FullName), JsonDecoders.verifyWith<PresenceLocation> oracle draws seed presenceLocation
            (Some "IPresenceApi", typeof<EntityLockRef>.FullName), JsonDecoders.verifyWith<EntityLockRef> oracle draws seed entityLockRef
            (Some "IProvenanceQueryApi", typeof<WireProvenanceRef>.FullName), JsonDecoders.verifyWith<WireProvenanceRef> oracle draws seed wireProvenanceRef
            (Some "IProvenanceQueryApi", typeof<WireProvenanceChainRequest>.FullName), JsonDecoders.verifyWith<WireProvenanceChainRequest> oracle draws seed wireProvenanceChainRequest
            (Some "IProviderProfileApi", typeof<ProviderEntryInput>.FullName), JsonDecoders.verifyWith<ProviderEntryInput> oracle draws seed providerEntryInput
            (Some "IProviderProfileApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IProviderProfileApi", typeof<RoutingRule>.FullName), JsonDecoders.verifyWith<RoutingRule> oracle draws seed routingRule
            (Some "IProviderProfileApi", typeof<Tuple<string, string option>>.FullName), JsonDecoders.verifyWith<Tuple<string, string option>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.option JsonDecode.asString))
            (Some "IProviderProfileApi", typeof<string list>.FullName), JsonDecoders.verifyWith<string list> oracle draws seed (JsonDecode.list JsonDecode.asString)
            (Some "IProviderProfileApi", typeof<Tuple<string, ProviderVerificationOutcome>>.FullName), JsonDecoders.verifyWith<Tuple<string, ProviderVerificationOutcome>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString providerVerificationOutcome)
            (Some "IServiceAccountApi", typeof<CreateServiceAccountRequest>.FullName), JsonDecoders.verifyWith<CreateServiceAccountRequest> oracle draws seed createServiceAccountRequest
            (Some "IServiceAccountApi", typeof<Tuple<string, ServiceAccountStatus>>.FullName), JsonDecoders.verifyWith<Tuple<string, ServiceAccountStatus>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString serviceAccountStatus)
            (Some "IServiceAccountApi", typeof<Tuple<string, Map<string, ModulePermission list>>>.FullName), JsonDecoders.verifyWith<Tuple<string, Map<string, ModulePermission list>>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.asMap JsonDecode.Key.string (JsonDecode.list modulePermission)))
            (Some "IServiceAccountApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IServiceAccountApi", typeof<MintServiceAccountTokenRequest>.FullName), JsonDecoders.verifyWith<MintServiceAccountTokenRequest> oracle draws seed mintServiceAccountTokenRequest
            (Some "ISessionApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "ITeamInviteApi", typeof<TeamInviteIssueRequest>.FullName), JsonDecoders.verifyWith<TeamInviteIssueRequest> oracle draws seed teamInviteIssueRequest
            (Some "ITeamInviteApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "ITeamInviteApi", typeof<PendingInviteIssueRequest>.FullName), JsonDecoders.verifyWith<PendingInviteIssueRequest> oracle draws seed pendingInviteIssueRequest
            (Some "IUserDirectoryApi", typeof<Tuple<string, int>>.FullName), JsonDecoders.verifyWith<Tuple<string, int>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asInt32)
            (Some "IUserDirectoryApi", typeof<string list>.FullName), JsonDecoders.verifyWith<string list> oracle draws seed (JsonDecode.list JsonDecode.asString)
            (Some "IUserSchemaApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "IUserSchemaApi", typeof<Tuple<string, int>>.FullName), JsonDecoders.verifyWith<Tuple<string, int>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asInt32)
            (Some "IUserSchemaApi", typeof<UserAuthoredSchema>.FullName), JsonDecoders.verifyWith<UserAuthoredSchema> oracle draws seed userAuthoredSchema
            (Some "IUserSchemaApi", typeof<Tuple<string, SchemaMigration list>>.FullName), JsonDecoders.verifyWith<Tuple<string, SchemaMigration list>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.list schemaMigration))
            (Some "IWebhookApi", typeof<CreateWebhookRequest>.FullName), JsonDecoders.verifyWith<CreateWebhookRequest> oracle draws seed createWebhookRequest
            (Some "IWebhookApi", typeof<Guid>.FullName), JsonDecoders.verifyWith<Guid> oracle draws seed JsonDecode.asGuid
            (Some "IWebhookApi", typeof<Tuple<Guid, WebhookStatus>>.FullName), JsonDecoders.verifyWith<Tuple<Guid, WebhookStatus>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asGuid webhookStatus)
            (Some "JobApi", typeof<Guid>.FullName), JsonDecoders.verifyWith<Guid> oracle draws seed JsonDecode.asGuid
            (Some "JobApi", typeof<Tuple<Guid, int>>.FullName), JsonDecoders.verifyWith<Tuple<Guid, int>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asGuid JsonDecode.asInt32)
            (Some "JobApi", typeof<JobRegistration>.FullName), JsonDecoders.verifyWith<JobRegistration> oracle draws seed jobRegistration
            (Some "ModelExecutionApi", typeof<ModelExecutionFitSubmission>.FullName), JsonDecoders.verifyWith<ModelExecutionFitSubmission> oracle draws seed modelExecutionFitSubmission
            (Some "ModelExecutionApi", typeof<ModelExecutionBatchSubmission>.FullName), JsonDecoders.verifyWith<ModelExecutionBatchSubmission> oracle draws seed modelExecutionBatchSubmission
            (Some "ModelExecutionApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "ModelExecutionApi", typeof<Tuple<ModelExecutionOutcomeQuery, string option, int>>.FullName), JsonDecoders.verifyWith<Tuple<ModelExecutionOutcomeQuery, string option, int>> oracle draws seed (JsonDecode.tuple3 modelExecutionOutcomeQuery (JsonDecode.option JsonDecode.asString) JsonDecode.asInt32)
            (Some "ModelExecutionApi", typeof<Tuple<string, int>>.FullName), JsonDecoders.verifyWith<Tuple<string, int>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asInt32)
            (Some "ModelExecutionApi", typeof<ModelExecutionScoreRequest>.FullName), JsonDecoders.verifyWith<ModelExecutionScoreRequest> oracle draws seed modelExecutionScoreRequest
            (Some "PermissionApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "PermissionApi", typeof<Tuple<string, string, string, ModulePermission list>>.FullName), JsonDecoders.verifyWith<Tuple<string, string, string, ModulePermission list>> oracle draws seed (JsonDecode.tuple4 JsonDecode.asString JsonDecode.asString JsonDecode.asString (JsonDecode.list modulePermission))
            (Some "PermissionApi", typeof<Tuple<string, Map<string, ModulePermission list>>>.FullName), JsonDecoders.verifyWith<Tuple<string, Map<string, ModulePermission list>>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString (JsonDecode.asMap JsonDecode.Key.string (JsonDecode.list modulePermission)))
            (Some "PermissionApi", typeof<Tuple<string, string, ModuleExposure>>.FullName), JsonDecoders.verifyWith<Tuple<string, string, ModuleExposure>> oracle draws seed (JsonDecode.tuple3 JsonDecode.asString JsonDecode.asString moduleExposure)
            (Some "PlatformAdminApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "PlatformAdminApi", typeof<PlatformKnowledgeBaseMode>.FullName), JsonDecoders.verifyWith<PlatformKnowledgeBaseMode> oracle draws seed platformKnowledgeBaseMode
            (Some "TeamApi", typeof<string>.FullName), JsonDecoders.verifyWith<string> oracle draws seed JsonDecode.asString
            (Some "TeamApi", typeof<CreateTeamRequest>.FullName), JsonDecoders.verifyWith<CreateTeamRequest> oracle draws seed createTeamRequest
            (Some "TeamApi", typeof<Tuple<string, string, TeamRole>>.FullName), JsonDecoders.verifyWith<Tuple<string, string, TeamRole>> oracle draws seed (JsonDecode.tuple3 JsonDecode.asString JsonDecode.asString teamRole)
            (Some "TeamApi", typeof<Tuple<string, string>>.FullName), JsonDecoders.verifyWith<Tuple<string, string>> oracle draws seed (JsonDecode.tuple2 JsonDecode.asString JsonDecode.asString)
            (Some "IUsageQueryApi", typeof<Tuple<string option, UsageDateRange option>>.FullName), JsonDecoders.verifyWith<Tuple<string option, UsageDateRange option>> oracle draws seed (JsonDecode.tuple2 (JsonDecode.option JsonDecode.asString) (JsonDecode.option usageDateRange))
            (Some "IUsageQueryApi", typeof<UsageGrouping>.FullName), JsonDecoders.verifyWith<UsageGrouping> oracle draws seed usageGrouping
            (Some "IUsageQueryApi", typeof<UsageDateRange option>.FullName), JsonDecoders.verifyWith<UsageDateRange option> oracle draws seed (JsonDecode.option usageDateRange)
        ]

    /// `registerAll`, gated: registers every decoder above only when every
    /// one agrees with `oracle`, and registers NOTHING otherwise, so a
    /// disagreement can never leave the table half-adopted.
    let registerAllVerified
        (oracle: JsonDecoderOracle)
        (draws: int)
        (seed: int)
        : Result<JsonDecoderVerification list, DecoderRefusal list> =
        let outcomes = verifyAll oracle draws seed |> List.map snd

        let refusals =
            outcomes
            |> List.choose (function
                | Error refusal -> Some refusal
                | Ok _ -> None)

        if List.isEmpty refusals then
            registerAll ()

            Ok(
                outcomes
                |> List.choose (function
                    | Ok verification -> Some verification
                    | Error _ -> None)
            )
        else
            Error refusals
#endif

