<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Shared\Shared.fsproj" />
        <ProjectReference Include="..\..\..\..\src\ToolUp.Platform.Server\ToolUp.Platform.Server.fsproj" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="Server.fs" />
    </ItemGroup>
</Project>
