// GENERATED by proofs/check.ps1 — the F* extractor's output for ../DisclosureFold.fst, re-laid-out by
// proofs/normalise-extraction.fsx (Phase 850). Do not edit: the proof leg byte-diffs this file.

module DisclosureFold

type opt<'a> =
    | ONone
    | OSome of 'a

let uu___is_ONone =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | ONone -> (true)
          | uu___ -> (false)))

let uu___is_OSome =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | OSome (item) -> (true)
          | uu___ -> (false)))

let __proj__OSome__item__item =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | OSome (item) -> (item)))

type pair<'a, 'b> =
    | Pair of 'a * 'b

let uu___is_Pair = (fun (projectee : pair<'a, 'b>) -> true)

let __proj__Pair__item__first =
    (fun (projectee : pair<'a, 'b>) ->
         (match (projectee) with
          | Pair (first, second) -> (first)))

let __proj__Pair__item__second =
    (fun (projectee : pair<'a, 'b>) ->
         (match (projectee) with
          | Pair (first, second) -> (second)))

let rec length =
    (fun (xs : Prims.list<'a>) ->
         (match (xs) with
          | [] -> ((Prims.parse_int "0"))
          | (uu___) ::rest -> (((Prims.parse_int "1") + (length rest)))))

type disclosure =
    | Surfaceable
    | Internal
    | Restricted of Prims.string

let uu___is_Surfaceable : disclosure -> Prims.bool =
    (fun (projectee : disclosure) ->
         (match (projectee) with
          | Surfaceable -> (true)
          | uu___ -> (false)))

let uu___is_Internal : disclosure -> Prims.bool =
    (fun (projectee : disclosure) ->
         (match (projectee) with
          | Internal -> (true)
          | uu___ -> (false)))

let uu___is_Restricted : disclosure -> Prims.bool =
    (fun (projectee : disclosure) ->
         (match (projectee) with
          | Restricted (policy_ref) -> (true)
          | uu___ -> (false)))

let __proj__Restricted__item__policy_ref : disclosure -> Prims.string =
    (fun (projectee : disclosure) ->
         (match (projectee) with
          | Restricted (policy_ref) -> (policy_ref)))

type verdict =
    | Disclosable
    | NotDisclosable of Prims.string

let uu___is_Disclosable : verdict -> Prims.bool =
    (fun (projectee : verdict) ->
         (match (projectee) with
          | Disclosable -> (true)
          | uu___ -> (false)))

let uu___is_NotDisclosable : verdict -> Prims.bool =
    (fun (projectee : verdict) ->
         (match (projectee) with
          | NotDisclosable (policy_ref) -> (true)
          | uu___ -> (false)))

let __proj__NotDisclosable__item__policy_ref : verdict -> Prims.string =
    (fun (projectee : verdict) ->
         (match (projectee) with
          | NotDisclosable (policy_ref) -> (policy_ref)))

type resolver<'surface> = Prims.string  ->  'surface  ->  opt<Prims.bool>

let deny_unknown = (fun (uu___ : Prims.string) (uu___1 : 'surface) -> ONone)

let evaluate =
    (fun (resolve_policy : resolver<'surface>) (at_surface : 'surface) (d : disclosure) ->
         (match (d) with
          | Surfaceable -> (Disclosable)
          | Internal -> (NotDisclosable ("Internal"))
          | Restricted (policy_ref) ->
              ((match ((resolve_policy policy_ref at_surface)) with
                | OSome (true) -> (Disclosable)
                | OSome (false) -> (NotDisclosable (policy_ref))
                | ONone -> (NotDisclosable (policy_ref))))))

type fact<'p> = {fact_id : Prims.string; payload : 'p}

let __proj__Mkfact__item__fact_id =
    (fun (projectee : fact<'p>) ->
         (match (projectee) with
          | {fact_id = fact_id; payload = payload} -> (fact_id)))

let __proj__Mkfact__item__payload =
    (fun (projectee : fact<'p>) ->
         (match (projectee) with
          | {fact_id = fact_id; payload = payload} -> (payload)))

type population_disclosure<'p> = {disclosable : Prims.list<pair<Prims.nat, fact<'p>>>; withheld_count : Prims.nat; withheld_by_policy : Prims.list<pair<Prims.string, Prims.nat>>}

let __proj__Mkpopulation_disclosure__item__disclosable =
    (fun (projectee : population_disclosure<'p>) ->
         (match (projectee) with
          | {disclosable = disclosable; withheld_count = withheld_count; withheld_by_policy = withheld_by_policy} -> (disclosable)))

let __proj__Mkpopulation_disclosure__item__withheld_count =
    (fun (projectee : population_disclosure<'p>) ->
         (match (projectee) with
          | {disclosable = disclosable; withheld_count = withheld_count; withheld_by_policy = withheld_by_policy} -> (withheld_count)))

let __proj__Mkpopulation_disclosure__item__withheld_by_policy =
    (fun (projectee : population_disclosure<'p>) ->
         (match (projectee) with
          | {disclosable = disclosable; withheld_count = withheld_count; withheld_by_policy = withheld_by_policy} -> (withheld_by_policy)))

type judged<'p> = {rank : Prims.nat; judged_fact : fact<'p>; judged_verdict : verdict}

let __proj__Mkjudged__item__rank =
    (fun (projectee : judged<'p>) ->
         (match (projectee) with
          | {rank = rank; judged_fact = judged_fact; judged_verdict = judged_verdict} -> (rank)))

let __proj__Mkjudged__item__judged_fact =
    (fun (projectee : judged<'p>) ->
         (match (projectee) with
          | {rank = rank; judged_fact = judged_fact; judged_verdict = judged_verdict} -> (judged_fact)))

let __proj__Mkjudged__item__judged_verdict =
    (fun (projectee : judged<'p>) ->
         (match (projectee) with
          | {rank = rank; judged_fact = judged_fact; judged_verdict = judged_verdict} -> (judged_verdict)))

let rec judge =
    (fun (verdict_for : Prims.string -> verdict) (position : Prims.nat) (ranked : Prims.list<fact<'p>>) ->
         (match (ranked) with
          | [] -> ([])
          | (f) ::rest -> (({rank = (position + (Prims.parse_int "1")); judged_fact = f; judged_verdict = (verdict_for f.fact_id)}) :: (judge verdict_for (position + (Prims.parse_int "1")) rest))))

let rec disclosable_of =
    (fun (js : Prims.list<judged<'p>>) ->
         (match (js) with
          | [] -> ([])
          | (j) ::rest ->
              (if
                   (match (j.judged_verdict) with
                    | Disclosable -> (true)
                    | uu___ -> (false))
               then
                   ((Pair (j.rank, j.judged_fact)) :: (disclosable_of rest))
               else
                   ((disclosable_of rest)))))

let rec withheld_refs =
    (fun (js : Prims.list<judged<'p>>) ->
         (match (js) with
          | [] -> ([])
          | (j) ::rest ->
              ((match (j.judged_verdict) with
                | Disclosable -> ((withheld_refs rest))
                | NotDisclosable (policy_ref) -> ((policy_ref) :: (withheld_refs rest))))))

let rec count_into : Prims.string -> Prims.list<pair<Prims.string, Prims.nat>> -> Prims.list<pair<Prims.string, Prims.nat>> =
    (fun (key : Prims.string) (counts : Prims.list<pair<Prims.string, Prims.nat>>) ->
         (match (counts) with
          | [] -> ((Pair (key, (Prims.parse_int "1"))) :: [])
          | (Pair (k, n)) ::rest -> (if (Prims.op_Equals k key) then ((Pair (k, (n + (Prims.parse_int "1")))) ::rest) else ((Pair (k, n)) :: (count_into key rest)))))

let rec count_by : Prims.list<Prims.string> -> Prims.list<pair<Prims.string, Prims.nat>> -> Prims.list<pair<Prims.string, Prims.nat>> =
    (fun (keys : Prims.list<Prims.string>) (counts : Prims.list<pair<Prims.string, Prims.nat>>) ->
         (match (keys) with
          | [] -> (counts)
          | (key) ::rest -> ((count_by rest (count_into key counts)))))

let rec insert_by : (Prims.string -> Prims.string -> Prims.bool) -> pair<Prims.string, Prims.nat> -> Prims.list<pair<Prims.string, Prims.nat>> -> Prims.list<pair<Prims.string, Prims.nat>> =
    (fun (before : Prims.string -> Prims.string -> Prims.bool) (entry : pair<Prims.string, Prims.nat>) (sorted : Prims.list<pair<Prims.string, Prims.nat>>) ->
         (match (sorted) with
          | [] -> ((entry) :: [])
          | (head) ::rest ->
              ((match (((entry), (head))) with
                | (Pair (key, uu___), Pair (head_key, uu___1)) -> (if (before head_key key) then ((head) :: (insert_by before entry rest)) else ((entry) ::sorted))))))

let rec sort_by : (Prims.string -> Prims.string -> Prims.bool) -> Prims.list<pair<Prims.string, Prims.nat>> -> Prims.list<pair<Prims.string, Prims.nat>> =
    (fun (before : Prims.string -> Prims.string -> Prims.bool) (entries : Prims.list<pair<Prims.string, Prims.nat>>) ->
         (match (entries) with
          | [] -> ([])
          | (entry) ::rest -> ((insert_by before entry (sort_by before rest)))))

let withheld_projection : (Prims.string -> Prims.string -> Prims.bool) -> Prims.list<Prims.string> -> Prims.list<pair<Prims.string, Prims.nat>> = (fun (before : Prims.string -> Prims.string -> Prims.bool) (refs : Prims.list<Prims.string>) -> (sort_by before (count_by refs [])))

let fold =
    (fun (before : Prims.string -> Prims.string -> Prims.bool) (verdict_for : Prims.string -> verdict) (ranked : Prims.list<fact<'p>>) ->
         (let judged1 = (judge verdict_for (Prims.parse_int "0") ranked) in
          (let withheld_policies = (withheld_refs judged1) in
           {disclosable = (disclosable_of judged1); withheld_count = (length withheld_policies); withheld_by_policy = (withheld_projection before withheld_policies)})))

let values_withheld = (fun (d : population_disclosure<'p>) -> (d.withheld_count > (Prims.parse_int "0")))

type stats<'m, 'r> = {minimum : opt<'m>; maximum : opt<'m>; mean : opt<'m>; existence : 'r}

let __proj__Mkstats__item__minimum =
    (fun (projectee : stats<'m, 'r>) ->
         (match (projectee) with
          | {minimum = minimum; maximum = maximum; mean = mean; existence = existence} -> (minimum)))

let __proj__Mkstats__item__maximum =
    (fun (projectee : stats<'m, 'r>) ->
         (match (projectee) with
          | {minimum = minimum; maximum = maximum; mean = mean; existence = existence} -> (maximum)))

let __proj__Mkstats__item__mean =
    (fun (projectee : stats<'m, 'r>) ->
         (match (projectee) with
          | {minimum = minimum; maximum = maximum; mean = mean; existence = existence} -> (mean)))

let __proj__Mkstats__item__existence =
    (fun (projectee : stats<'m, 'r>) ->
         (match (projectee) with
          | {minimum = minimum; maximum = maximum; mean = mean; existence = existence} -> (existence)))

let disclosed_stats = (fun (d : population_disclosure<'p>) (s : stats<'m, 'r>) -> if (values_withheld d) then ({minimum = ONone; maximum = ONone; mean = ONone; existence = s.existence}) else (s))
