// GENERATED by proofs/check.ps1 — the F* extractor's output for ../ElmishSub.fst, re-laid-out by
// proofs/normalise-extraction.fsx (Phase 850). Do not edit: the proof leg byte-diffs this file.

module ElmishSub

type opt<'a> =
    | ONone
    | OSome of 'a

let uu___is_ONone =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | ONone -> (true)
          | uu___ -> (false)))

let uu___is_OSome =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | OSome (item) -> (true)
          | uu___ -> (false)))

let __proj__OSome__item__item =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | OSome (item) -> (item)))

type pair<'a, 'b> =
    | Pair of 'a * 'b

let uu___is_Pair = (fun (projectee : pair<'a, 'b>) -> true)

let __proj__Pair__item__first =
    (fun (projectee : pair<'a, 'b>) ->
         (match (projectee) with
          | Pair (first, second) -> (first)))

let __proj__Pair__item__second =
    (fun (projectee : pair<'a, 'b>) ->
         (match (projectee) with
          | Pair (first, second) -> (second)))

type diff_result<'k, 'h, 's> =
    | Diff of Prims.list<'k> * Prims.list<pair<'k, 'h>> * Prims.list<pair<'k, 'h>> * Prims.list<pair<'k, 's>>

let uu___is_Diff = (fun (projectee : diff_result<'k, 'h, 's>) -> true)

let __proj__Diff__item__dupes =
    (fun (projectee : diff_result<'k, 'h, 's>) ->
         (match (projectee) with
          | Diff (dupes, to_stop, to_keep, to_start) -> (dupes)))

let __proj__Diff__item__to_stop =
    (fun (projectee : diff_result<'k, 'h, 's>) ->
         (match (projectee) with
          | Diff (dupes, to_stop, to_keep, to_start) -> (to_stop)))

let __proj__Diff__item__to_keep =
    (fun (projectee : diff_result<'k, 'h, 's>) ->
         (match (projectee) with
          | Diff (dupes, to_stop, to_keep, to_start) -> (to_keep)))

let __proj__Diff__item__to_start =
    (fun (projectee : diff_result<'k, 'h, 's>) ->
         (match (projectee) with
          | Diff (dupes, to_stop, to_keep, to_start) -> (to_start)))

type accumulator<'k, 's> =
    | Calc of Prims.list<'k> * Prims.list<'k> * Prims.list<pair<'k, 's>>

let uu___is_Calc = (fun (projectee : accumulator<'k, 's>) -> true)

let __proj__Calc__item__dupes =
    (fun (projectee : accumulator<'k, 's>) ->
         (match (projectee) with
          | Calc (dupes, new_keys, new_subs) -> (dupes)))

let __proj__Calc__item__new_keys =
    (fun (projectee : accumulator<'k, 's>) ->
         (match (projectee) with
          | Calc (dupes, new_keys, new_subs) -> (new_keys)))

let __proj__Calc__item__new_subs =
    (fun (projectee : accumulator<'k, 's>) ->
         (match (projectee) with
          | Calc (dupes, new_keys, new_subs) -> (new_subs)))

let rec mem =
    (fun (key : 'k) (keys : Prims.list<'k>) ->
         (match (keys) with
          | [] -> (false)
          | (x) ::rest -> (((Prims.op_Equals x key) || (mem key rest)))))

let rec subset =
    (fun (xs : Prims.list<'k>) (ys : Prims.list<'k>) ->
         (match (xs) with
          | [] -> (true)
          | (x) ::rest -> (((mem x ys) && (subset rest ys)))))

let set_equal = (fun (xs : Prims.list<'k>) (ys : Prims.list<'k>) -> ((subset xs ys) && (subset ys xs)))

let rec keys_of =
    (fun (xs : Prims.list<pair<'k, 'v>>) ->
         (match (xs) with
          | [] -> ([])
          | (Pair (key, uu___)) ::rest -> ((key) :: (keys_of rest))))

let rec with_key_in =
    (fun (keys : Prims.list<'k>) (xs : Prims.list<pair<'k, 'v>>) ->
         (match (xs) with
          | [] -> ([])
          | (Pair (key, value)) ::rest -> (if (mem key keys) then ((Pair (key, value)) :: (with_key_in keys rest)) else ((with_key_in keys rest)))))

let rec with_key_not_in =
    (fun (keys : Prims.list<'k>) (xs : Prims.list<pair<'k, 'v>>) ->
         (match (xs) with
          | [] -> ([])
          | (Pair (key, value)) ::rest -> (if (mem key keys) then ((with_key_not_in keys rest)) else ((Pair (key, value)) :: (with_key_not_in keys rest)))))

let rec append =
    (fun (xs : Prims.list<'a>) (ys : Prims.list<'a>) ->
         (match (xs) with
          | [] -> (ys)
          | (x) ::rest -> ((x) :: (append rest ys))))

let update =
    (fun (entry : pair<'k, 's>) (acc : accumulator<'k, 's>) ->
         (let uu___ = entry in
          (match (uu___) with
           | Pair (sub_id, start) ->
               ((let uu___1 = acc in
                 (match (uu___1) with
                  | Calc (dupes, new_keys, new_subs) -> (if (mem sub_id new_keys) then (Calc ((sub_id) ::dupes, new_keys, new_subs)) else (Calc (dupes, (sub_id) ::new_keys, (Pair (sub_id, start)) ::new_subs)))))))))

let rec calculate =
    (fun (subs : Prims.list<pair<'k, 's>>) ->
         (match (subs) with
          | [] -> (Calc ([], [], []))
          | (entry) ::rest -> ((update entry (calculate rest)))))

let diff =
    (fun (active : Prims.list<pair<'k, 'h>>) (sub : Prims.list<pair<'k, 's>>) ->
         (let keys = (keys_of active) in
          (let uu___ = (calculate sub) in
           (match (uu___) with
            | Calc (dupes, new_keys, new_subs) ->
                (if (set_equal keys new_keys) then
                     (Diff (dupes, [], active, []))
                 else
                     ((let to_keep = (with_key_in new_keys active) in
                       (let to_stop = (with_key_not_in new_keys active) in
                        (let to_start = (with_key_not_in keys new_subs) in
                         Diff (dupes, to_stop, to_keep, to_start))))))))))

let rec started =
    (fun (start : 'k -> 's -> opt<'h>) (xs : Prims.list<pair<'k, 's>>) ->
         (match (xs) with
          | [] -> ([])
          | (Pair (key, subscribe)) ::rest ->
              ((match ((start key subscribe)) with
                | OSome (handle) -> ((Pair (key, handle)) :: (started start rest))
                | ONone -> ((started start rest))))))

let change =
    (fun (start : 'k -> 's -> opt<'h>) (d : diff_result<'k, 'h, 's>) ->
         (let uu___ = d in
          (match (uu___) with
           | Diff (uu___1, uu___2, to_keep, to_start) -> ((append to_keep (started start to_start))))))
