// GENERATED by proofs/check.ps1 — the F* extractor's output for ../ElmishRing.fst, re-laid-out by
// proofs/normalise-extraction.fsx (Phase 850). Do not edit: the proof leg byte-diffs this file.

module ElmishRing

type opt<'a> =
    | ONone
    | OSome of 'a

let uu___is_ONone =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | ONone -> (true)
          | uu___ -> (false)))

let uu___is_OSome =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | OSome (item) -> (true)
          | uu___ -> (false)))

let __proj__OSome__item__item =
    (fun (projectee : opt<'a>) ->
         (match (projectee) with
          | OSome (item) -> (item)))

type pair<'a, 'b> =
    | Pair of 'a * 'b

let uu___is_Pair = (fun (projectee : pair<'a, 'b>) -> true)

let __proj__Pair__item__first =
    (fun (projectee : pair<'a, 'b>) ->
         (match (projectee) with
          | Pair (first, second) -> (first)))

let __proj__Pair__item__second =
    (fun (projectee : pair<'a, 'b>) ->
         (match (projectee) with
          | Pair (first, second) -> (second)))

type slot<'a> =
    | Placeholder
    | Written of 'a

let uu___is_Placeholder =
    (fun (projectee : slot<'a>) ->
         (match (projectee) with
          | Placeholder -> (true)
          | uu___ -> (false)))

let uu___is_Written =
    (fun (projectee : slot<'a>) ->
         (match (projectee) with
          | Written (value) -> (true)
          | uu___ -> (false)))

let __proj__Written__item__value =
    (fun (projectee : slot<'a>) ->
         (match (projectee) with
          | Written (value) -> (value)))

let rec length =
    (fun (xs : Prims.list<'a>) ->
         (match (xs) with
          | [] -> ((Prims.parse_int "0"))
          | (uu___) ::rest -> (((Prims.parse_int "1") + (length rest)))))

let rec nth =
    (fun (xs : Prims.list<slot<'a>>) (i : Prims.nat) ->
         (match (xs) with
          | [] -> (Placeholder)
          | (x) ::rest -> (if (Prims.op_Equals i (Prims.parse_int "0")) then (x) else ((nth rest (i - (Prims.parse_int "1")))))))

let rec set =
    (fun (xs : Prims.list<slot<'a>>) (i : Prims.nat) (v : slot<'a>) ->
         (match (xs) with
          | [] -> ([])
          | (x) ::rest -> (if (Prims.op_Equals i (Prims.parse_int "0")) then ((v) ::rest) else ((x) :: (set rest (i - (Prims.parse_int "1")) v)))))

let rec append =
    (fun (xs : Prims.list<'a>) (ys : Prims.list<'a>) ->
         (match (xs) with
          | [] -> (ys)
          | (x) ::rest -> ((x) :: (append rest ys))))

let rec skip =
    (fun (n : Prims.nat) (xs : Prims.list<'a>) ->
         if (Prims.op_Equals n (Prims.parse_int "0")) then
             (xs)
         else
             ((match (xs) with
               | [] -> ([])
               | (uu___) ::rest -> ((skip (n - (Prims.parse_int "1")) rest)))))

let rec take =
    (fun (n : Prims.nat) (xs : Prims.list<'a>) ->
         if (Prims.op_Equals n (Prims.parse_int "0")) then
             ([])
         else
             ((match (xs) with
               | [] -> ([])
               | (x) ::rest -> ((x) :: (take (n - (Prims.parse_int "1")) rest)))))

let rec replicate = (fun (n : Prims.nat) (v : 'a) -> if (Prims.op_Equals n (Prims.parse_int "0")) then ([]) else ((v) :: (replicate (n - (Prims.parse_int "1")) v)))

let succ : Prims.nat -> Prims.nat -> Prims.nat = (fun (n : Prims.nat) (i : Prims.nat) -> if ((i + (Prims.parse_int "1")) >= n) then ((Prims.parse_int "0")) else ((i + (Prims.parse_int "1"))))

type ring<'a> =
    | Writable of Prims.list<slot<'a>> * Prims.nat
    | ReadWritable of Prims.list<slot<'a>> * Prims.nat * Prims.nat

let uu___is_Writable =
    (fun (projectee : ring<'a>) ->
         (match (projectee) with
          | Writable (items, ix) -> (true)
          | uu___ -> (false)))

let __proj__Writable__item__items =
    (fun (projectee : ring<'a>) ->
         (match (projectee) with
          | Writable (items, ix) -> (items)))

let __proj__Writable__item__ix =
    (fun (projectee : ring<'a>) ->
         (match (projectee) with
          | Writable (items, ix) -> (ix)))

let uu___is_ReadWritable =
    (fun (projectee : ring<'a>) ->
         (match (projectee) with
          | ReadWritable (items, wix, rix) -> (true)
          | uu___ -> (false)))

let __proj__ReadWritable__item__items =
    (fun (projectee : ring<'a>) ->
         (match (projectee) with
          | ReadWritable (items, wix, rix) -> (items)))

let __proj__ReadWritable__item__wix =
    (fun (projectee : ring<'a>) ->
         (match (projectee) with
          | ReadWritable (items, wix, rix) -> (wix)))

let __proj__ReadWritable__item__rix =
    (fun (projectee : ring<'a>) ->
         (match (projectee) with
          | ReadWritable (items, wix, rix) -> (rix)))

let minimum_capacity : Prims.nat = (Prims.parse_int "2")

let capacity_of : Prims.int -> Prims.nat = (fun (size : Prims.int) -> if (size > minimum_capacity) then (size) else (minimum_capacity))

let create = (fun (size : Prims.int) -> Writable ((replicate (capacity_of size) Placeholder), (Prims.parse_int "0")))

let double_size = (fun (ix : Prims.nat) (items : Prims.list<slot<'a>>) -> (append (skip ix items) (append (take ix items) (replicate ((length items) + (Prims.parse_int "1")) Placeholder))))

let pop =
    (fun (r : ring<'a>) ->
         (match (r) with
          | ReadWritable (items, wix, rix) ->
              ((let rix' = (succ (length items) rix) in
                if (Prims.op_Equals rix' wix) then (Pair (Writable (items, wix), OSome ((nth items rix)))) else (Pair (ReadWritable (items, wix, rix'), OSome ((nth items rix))))))
          | Writable (uu___, uu___1) -> (Pair (r, ONone))))

let push =
    (fun (item : 'a) (r : ring<'a>) ->
         (match (r) with
          | Writable (items, ix) ->
              ((let items' = (set items ix (Written (item))) in
                ReadWritable (items', (succ (length items) ix), ix)))
          | ReadWritable (items, wix, rix) ->
              ((let items' = (set items wix (Written (item))) in
                (let wix' = (succ (length items) wix) in
                 if (Prims.op_Equals wix' rix) then (ReadWritable ((double_size rix items'), (length items'), (Prims.parse_int "0"))) else (ReadWritable (items', wix', rix)))))))

type op<'a> =
    | Push of 'a
    | Pop

let uu___is_Push =
    (fun (projectee : op<'a>) ->
         (match (projectee) with
          | Push (item) -> (true)
          | uu___ -> (false)))

let __proj__Push__item__item =
    (fun (projectee : op<'a>) ->
         (match (projectee) with
          | Push (item) -> (item)))

let uu___is_Pop =
    (fun (projectee : op<'a>) ->
         (match (projectee) with
          | Pop -> (true)
          | uu___ -> (false)))

let rec run =
    (fun (r : ring<'a>) (ops : Prims.list<op<'a>>) ->
         (match (ops) with
          | [] -> (Pair (r, []))
          | (Push (item)) ::rest -> ((run (push item r) rest))
          | (Pop) ::rest ->
              ((let uu___ = (pop r) in
                (match (uu___) with
                 | Pair (r', out) ->
                     ((let uu___1 = (run r' rest) in
                       (match (uu___1) with
                        | Pair (r'', outs) -> (Pair (r'', (out) ::outs))))))))))
