// GENERATED by proofs/check.ps1 — the F* extractor's output for ../ElmishLoop.fst, re-laid-out by
// proofs/normalise-extraction.fsx (Phase 850). Do not edit: the proof leg byte-diffs this file.

module ElmishLoop

type ev<'m> =
    | Msg of 'm
    | Term

let uu___is_Msg =
    (fun (projectee : ev<'m>) ->
         (match (projectee) with
          | Msg (msg) -> (true)
          | uu___ -> (false)))

let __proj__Msg__item__msg =
    (fun (projectee : ev<'m>) ->
         (match (projectee) with
          | Msg (msg) -> (msg)))

let uu___is_Term =
    (fun (projectee : ev<'m>) ->
         (match (projectee) with
          | Term -> (true)
          | uu___ -> (false)))

type ext<'m> =
    | XDispatch of 'm
    | XTerminate

let uu___is_XDispatch =
    (fun (projectee : ext<'m>) ->
         (match (projectee) with
          | XDispatch (msg) -> (true)
          | uu___ -> (false)))

let __proj__XDispatch__item__msg =
    (fun (projectee : ext<'m>) ->
         (match (projectee) with
          | XDispatch (msg) -> (msg)))

let uu___is_XTerminate =
    (fun (projectee : ext<'m>) ->
         (match (projectee) with
          | XTerminate -> (true)
          | uu___ -> (false)))

type st<'m, 'md> = {ring : ElmishRing.ring<'m>; reentered : Prims.bool; terminated : Prims.bool; active : Prims.bool; model : 'md; trace : Prims.list<'m>; log : Prims.list<'m>}

let __proj__Mkst__item__ring =
    (fun (projectee : st<'m, 'md>) ->
         (match (projectee) with
          | {ring = ring; reentered = reentered; terminated = terminated; active = active; model = model; trace = trace; log = log} -> (ring)))

let __proj__Mkst__item__reentered =
    (fun (projectee : st<'m, 'md>) ->
         (match (projectee) with
          | {ring = ring; reentered = reentered; terminated = terminated; active = active; model = model; trace = trace; log = log} -> (reentered)))

let __proj__Mkst__item__terminated =
    (fun (projectee : st<'m, 'md>) ->
         (match (projectee) with
          | {ring = ring; reentered = reentered; terminated = terminated; active = active; model = model; trace = trace; log = log} -> (terminated)))

let __proj__Mkst__item__active =
    (fun (projectee : st<'m, 'md>) ->
         (match (projectee) with
          | {ring = ring; reentered = reentered; terminated = terminated; active = active; model = model; trace = trace; log = log} -> (active)))

let __proj__Mkst__item__model =
    (fun (projectee : st<'m, 'md>) ->
         (match (projectee) with
          | {ring = ring; reentered = reentered; terminated = terminated; active = active; model = model; trace = trace; log = log} -> (model)))

let __proj__Mkst__item__trace =
    (fun (projectee : st<'m, 'md>) ->
         (match (projectee) with
          | {ring = ring; reentered = reentered; terminated = terminated; active = active; model = model; trace = trace; log = log} -> (trace)))

let __proj__Mkst__item__log =
    (fun (projectee : st<'m, 'md>) ->
         (match (projectee) with
          | {ring = ring; reentered = reentered; terminated = terminated; active = active; model = model; trace = trace; log = log} -> (log)))

let initial = (fun (capacity : Prims.int) (model : 'md) -> {ring = (ElmishRing.create capacity); reentered = false; terminated = false; active = true; model = model; trace = []; log = []})

let enqueue = (fun (s : st<'m, 'md>) (msg : 'm) -> if s.terminated then (s) else ({ring = (ElmishRing.push msg s.ring); reentered = s.reentered; terminated = s.terminated; active = s.active; model = s.model; trace = s.trace; log = (ElmishRing.append s.log ((msg) :: []))}))

let terminate = (fun (s : st<'m, 'md>) -> if s.terminated then (s) else ({ring = s.ring; reentered = s.reentered; terminated = true; active = false; model = s.model; trace = s.trace; log = s.log}))

let apply_ev =
    (fun (s : st<'m, 'md>) (e : ev<'m>) ->
         (match (e) with
          | Msg (msg) -> ((enqueue s msg))
          | Term -> ((terminate s))))

let rec apply_evs =
    (fun (s : st<'m, 'md>) (evs : Prims.list<ev<'m>>) ->
         (match (evs) with
          | [] -> (s)
          | (e) ::rest -> ((apply_evs (apply_ev s e) rest))))

let step =
    (fun (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (msg : 'm) (s : st<'m, 'md>) ->
         if (to_terminate msg) then
             ((terminate s))
         else
             ((let uu___ = (update msg s.model) in
               (match (uu___) with
                | ElmishRing.Pair (model', evs) ->
                    ((let s1 = {ring = s.ring; reentered = s.reentered; terminated = s.terminated; active = s.active; model = s.model; trace = (ElmishRing.append s.trace ((msg) :: [])); log = s.log} in
                      (let s2 = (apply_evs s1 evs) in
                       {ring = s2.ring; reentered = s2.reentered; terminated = s2.terminated; active = s2.active; model = model'; trace = s2.trace; log = s2.log})))))))

let rec loop =
    (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (s : st<'m, 'md>) (next : ElmishRing.opt<ElmishRing.slot<'m>>) ->
         if s.terminated then
             (ElmishRing.Pair (s, true))
         else
             ((match (next) with
               | ElmishRing.ONone -> (ElmishRing.Pair (s, true))
               | ElmishRing.OSome (ElmishRing.Placeholder) -> (ElmishRing.Pair (s, true))
               | ElmishRing.OSome (ElmishRing.Written (msg)) ->
                   ((let s' = (step update to_terminate msg s) in
                     if (Prims.op_Equals fuel (Prims.parse_int "0")) then
                         (ElmishRing.Pair (s', false))
                     else
                         ((let uu___ = (ElmishRing.pop s'.ring) in
                           (match (uu___) with
                            | ElmishRing.Pair (r', next') -> ((loop (fuel - (Prims.parse_int "1")) update to_terminate {ring = r'; reentered = s'.reentered; terminated = s'.terminated; active = s'.active; model = s'.model; trace = s'.trace; log = s'.log} next'))))))))))

let process_msgs =
    (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (s : st<'m, 'md>) ->
         (let uu___ = (ElmishRing.pop s.ring) in
          (match (uu___) with
           | ElmishRing.Pair (r, next) -> ((loop fuel update to_terminate {ring = r; reentered = s.reentered; terminated = s.terminated; active = s.active; model = s.model; trace = s.trace; log = s.log} next)))))

let critical =
    (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (s : st<'m, 'md>) ->
         (let uu___ = (process_msgs fuel update to_terminate {ring = s.ring; reentered = true; terminated = s.terminated; active = s.active; model = s.model; trace = s.trace; log = s.log}) in
          (match (uu___) with
           | ElmishRing.Pair (s', finished) -> (if finished then ({ring = s'.ring; reentered = false; terminated = s'.terminated; active = s'.active; model = s'.model; trace = s'.trace; log = s'.log}) else (s')))))

let dispatch =
    (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (s : st<'m, 'md>) (msg : 'm) ->
         if s.terminated then
             (s)
         else
             ((let s1 = {ring = (ElmishRing.push msg s.ring); reentered = s.reentered; terminated = s.terminated; active = s.active; model = s.model; trace = s.trace; log = (ElmishRing.append s.log ((msg) :: []))} in
               if s1.reentered then (s1) else ((critical fuel update to_terminate s1)))))

let boot_ev =
    (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (s : st<'m, 'md>) (e : ev<'m>) ->
         (match (e) with
          | Msg (msg) -> ((dispatch fuel update to_terminate s msg))
          | Term -> ((terminate s))))

let rec boot_evs =
    (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (s : st<'m, 'md>) (evs : Prims.list<ev<'m>>) ->
         (match (evs) with
          | [] -> (s)
          | (e) ::rest -> ((boot_evs fuel update to_terminate (boot_ev fuel update to_terminate s e) rest))))

let boot =
    (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (s : st<'m, 'md>) (evs : Prims.list<ev<'m>>) ->
         (let s1 = {ring = s.ring; reentered = true; terminated = s.terminated; active = s.active; model = s.model; trace = s.trace; log = s.log} in
          (let s2 = (boot_evs fuel update to_terminate s1 evs) in
           (let uu___ = (process_msgs fuel update to_terminate s2) in
            (match (uu___) with
             | ElmishRing.Pair (s3, finished) -> (if finished then ({ring = s3.ring; reentered = false; terminated = s3.terminated; active = s3.active; model = s3.model; trace = s3.trace; log = s3.log}) else (s3)))))))

let rec run =
    (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (s : st<'m, 'md>) (exts : Prims.list<ext<'m>>) ->
         if s.reentered then
             (s)
         else
             ((match (exts) with
               | [] -> (s)
               | (XDispatch (msg)) ::rest -> ((run fuel update to_terminate (dispatch fuel update to_terminate s msg) rest))
               | (XTerminate) ::rest -> ((run fuel update to_terminate (terminate s) rest)))))

let program = (fun (fuel : Prims.nat) (update : 'm -> 'md -> ElmishRing.pair<'md, Prims.list<ev<'m>>>) (to_terminate : 'm -> Prims.bool) (capacity : Prims.int) (model : 'md) (init_evs : Prims.list<ev<'m>>) (exts : Prims.list<ext<'m>>) -> (run fuel update to_terminate (boot fuel update to_terminate (initial capacity model) init_evs) exts))

let fallback_terminate = (fun (s : st<'m, 'md>) -> {ring = s.ring; reentered = s.reentered; terminated = s.terminated; active = false; model = s.model; trace = s.trace; log = s.log})
