module ToolUp.Platform.Tests.InProcess.ShareTokenSigningKeyGovernanceTests

open System
open System.Collections.Concurrent
open System.IO
open Expecto
open ToolUp.Platform
open ToolUp.Platform.BlobStorage
open ToolUp.Platform.ConfigValidation
open ToolUp.Platform.Secrets

// ─── Phase 460 — share-token signing-key governance ──────────────────
//
// Two halves, and they are deliberately tested against different
// surfaces because they fail differently:
//
//   * The **validator** half (tasks A + C) is a preflight decision over
//     a config + a secret store. Its pack pins the whole severity
//     ladder, including the two arms that must stay `Ok` — a validator
//     that refuses everything would satisfy "refuses when unprovisioned"
//     and be useless.
//   * The **race** half (task B) is a store behaviour, so it is tested
//     through `BlobShareTokenStore` end to end: a token minted while a
//     peer replica wins the write must still verify on the replica that
//     reads the peer's key. Asserting on the cached bytes would pass for
//     an implementation that caches locally and diverges — which is the
//     bug.

let private silentLogger =
    { new ILogger with
        member _.Debug _ = ()
        member _.Info _ = ()
        member _.Warn _ = ()
        member _.Error(_, _) = ()
    }

/// A base64url-encoded 32-byte value, shaped exactly as the store
/// expects an operator-provisioned key to be.
let private encodedKey (seed: byte) = Base64Url.encode (Array.create 32 seed)

// ─── Validator harness ───────────────────────────────────────────────

type private SeedableSecretStore(seed: (string * string) list) =
    let store = ConcurrentDictionary<string * string, string>()

    do
        for key, value in seed do
            store[(ShareTokenStore.platformContainer, key)] <- value

    interface ISecretStore with
        member _.GetSecret(scopeId, key) = async {
            match store.TryGetValue((scopeId, key)) with
            | true, v -> return Some v
            | _ -> return None
        }

        member _.SetSecret(scopeId, key, value) = async {
            store[(scopeId, key)] <- value
            return Result.Ok()
        }

        member _.DeleteSecret(scopeId, key) = async {
            store.TryRemove((scopeId, key)) |> ignore
            return Result.Ok()
        }

        member _.ListKeys(scopeId) = async {
            return
                store.Keys
                |> Seq.filter (fun (s, _) -> s = scopeId)
                |> Seq.map snd
                |> List.ofSeq
        }

/// Live share-token surface; the caller decides the deployment shape and
/// whether the ephemeral-key acknowledgement is set.
let private cfg (replicaCount: int) (publicBaseUrl: string option) (acceptEphemeral: bool) = {
    ServerConfig.defaults with
        Surfaces = Surfaces.individual
        ShareTokenStore = EnabledShareTokenStore
        ReplicaCount = replicaCount
        PublicBaseUrl = publicBaseUrl
        AcceptEphemeralShareTokenKey = acceptEphemeral
}

let private validate (config: ServerConfig) (seed: (string * string) list) : ValidationResult =
    let store = SeedableSecretStore(seed) :> ISecretStore

    let v =
        ShareTokenSigningKeyProvenanceValidator.ShareTokenSigningKeyProvenanceValidator(config, store)
        :> IConfigValidator

    v.Validate() |> Async.RunSynchronously

let private provisioned = [ ShareTokenStore.signingKeySecretName, encodedKey 7uy ]

let private autoGenerated = [
    ShareTokenStore.signingKeySecretName, encodedKey 9uy
    ShareTokenStore.signingKeyOriginSecretName, ShareTokenStore.autoGeneratedOriginMarker
]

// ─── Race harness ────────────────────────────────────────────────────

/// Models a peer replica that wins the first-write race: this process's
/// first `SetSecret` of the signing key is accepted and then immediately
/// overwritten by the peer's value, exactly as a last-writer-wins secret
/// store would leave it. Everything else passes through.
///
/// The store under test must therefore NOT sign with the key it minted —
/// it must adopt what the store ended up holding, or the token it issues
/// is unverifiable on every sibling replica.
type private PeerWinsSecretStore(peerKeyEncoded: string) =
    let store = ConcurrentDictionary<string * string, string>()
    let mutable raced = false

    member _.Raced = raced

    interface ISecretStore with
        member _.GetSecret(scopeId, key) = async {
            match store.TryGetValue((scopeId, key)) with
            | true, v -> return Some v
            | _ -> return None
        }

        member _.SetSecret(scopeId, key, value) = async {
            if key = ShareTokenStore.signingKeySecretName && not raced then
                raced <- true
                // The write lands, and the peer's write lands after it.
                store[(scopeId, key)] <- peerKeyEncoded
            else
                store[(scopeId, key)] <- value

            return Result.Ok()
        }

        member _.DeleteSecret(scopeId, key) = async {
            store.TryRemove((scopeId, key)) |> ignore
            return Result.Ok()
        }

        member _.ListKeys(scopeId) = async {
            return
                store.Keys
                |> Seq.filter (fun (s, _) -> s = scopeId)
                |> Seq.map snd
                |> List.ofSeq
        }

let private freshStorage () =
    let root =
        Path.Combine(Path.GetTempPath(), "toolup-sharetoken-gov-" + Guid.NewGuid().ToString("N"))

    Directory.CreateDirectory(root) |> ignore
    LocalFileStorage.LocalFileStorage(root) :> IBlobStorage

let private issueRequest (scopeId: string) = {
    ScopeId = scopeId
    ResourceKind = "form"
    ResourceId = "f-1"
    AttributedHandle = None
    IssuedBy = "u-1"
    ExpiresAt = None
    UseLimit = Some None
    RateLimit = None
}

[<Tests>]
let tests =
    testList "Phase 460 — share-token signing-key governance" [

        // ── Task A: the refusal, and the two arms that must stay quiet ──

        testList "validator severity ladder" [

            test "public surface + key absent + no acknowledgement → Error (startup refused)" {
                match validate (cfg 1 (Some "https://app.example.com") false) [] with
                | Error msg ->
                    Expect.stringContains msg ShareTokenStore.signingKeySecretName "names the unprovisioned secret"
                    Expect.stringContains msg "TOOLUP_ACCEPT_EPHEMERAL_SHARE_TOKEN_KEY" "names the acknowledgement"
                    Expect.stringContains msg "pre-provision" "names the correct fix first"
                | other -> failtestf "expected Error, got %A" other
            }

            test "ReplicaCount > 1 + key absent + no acknowledgement → Error" {
                match validate (cfg 3 None false) [] with
                | Error _ -> ()
                | other -> failtestf "expected Error, got %A" other
            }

            test "production shape + key absent + acknowledgement → Warning naming the flag" {
                match validate (cfg 3 (Some "https://app.example.com") true) [] with
                | Warning msg ->
                    Expect.stringContains
                        msg
                        "AcceptEphemeralShareTokenKey"
                        "the opt-out is named as the reason nothing was refused"

                    Expect.stringContains msg "NOT being refused" "the downgrade is explicit, not silent"
                | other -> failtestf "expected Warning, got %A" other
            }

            test "production shape + key operator-provisioned → Ok (unchanged, GP 11)" {
                Expect.equal
                    (validate (cfg 3 (Some "https://app.example.com") false) provisioned)
                    Ok
                    "a correctly-configured deployment sees nothing"
            }

            test "single instance, non-public + key absent → Ok (dev convenience survives)" {
                Expect.equal (validate (cfg 1 None false) []) Ok "non-production shape is silent"
            }

            test "single instance, non-public + auto-generated key → Ok" {
                Expect.equal (validate (cfg 1 None false) autoGenerated) Ok "dev auto-generation is not a finding"
            }

            test "surface off → Ok even in a public multi-replica shape" {
                let config = {
                    cfg 5 (Some "https://app.example.com") false with
                        ShareTokenStore = NoShareTokenStore
                }

                Expect.equal (validate config []) Ok "no share-token surface → the key is irrelevant"
            }

            // ── Task C: the provenance the store now records ──

            test "production shape + key present but AUTO-GENERATED → Warning (Wave 19 was silent here)" {
                match validate (cfg 3 (Some "https://app.example.com") false) autoGenerated with
                | Warning msg ->
                    Expect.stringContains msg "AUTO-GENERATED" "states the provenance"

                    Expect.stringContains
                        msg
                        ShareTokenStore.signingKeyOriginSecretName
                        "names the marker so the operator can clear it"
                | other -> failtestf "expected Warning, got %A" other
            }

            test "the acknowledgement does NOT silence an already-minted unmanaged key" {
                // The flag acknowledges "a key may be auto-generated", not
                // "stop telling me one is in force". Different findings.
                match validate (cfg 3 (Some "https://app.example.com") true) autoGenerated with
                | Warning msg -> Expect.stringContains msg "AUTO-GENERATED" "still reported"
                | other -> failtestf "expected Warning, got %A" other
            }
        ]

        testList "provenance probe" [

            test "absent key → AbsentWillAutoGenerate" {
                let store = SeedableSecretStore([]) :> ISecretStore

                Expect.equal
                    (ShareTokenStore.probeSigningKeyProvenance store |> Async.RunSynchronously)
                    ShareTokenStore.AbsentWillAutoGenerate
                    "nothing provisioned"
            }

            test "key with no marker → OperatorProvisioned (a pre-460 key is not retro-classified)" {
                let store = SeedableSecretStore(provisioned) :> ISecretStore

                Expect.equal
                    (ShareTokenStore.probeSigningKeyProvenance store |> Async.RunSynchronously)
                    ShareTokenStore.OperatorProvisioned
                    "no marker ⇒ presumed managed"
            }

            test "key with the marker → AutoGenerated" {
                let store = SeedableSecretStore(autoGenerated) :> ISecretStore

                Expect.equal
                    (ShareTokenStore.probeSigningKeyProvenance store |> Async.RunSynchronously)
                    ShareTokenStore.AutoGenerated
                    "marker ⇒ SDK-minted"
            }

            test "the probe never writes — preflight must not create the key it warns about" {
                let store = SeedableSecretStore([]) :> ISecretStore

                ShareTokenStore.probeSigningKeyProvenance store
                |> Async.RunSynchronously
                |> ignore

                Expect.isEmpty
                    (store.ListKeys ShareTokenStore.platformContainer |> Async.RunSynchronously)
                    "the store is untouched"
            }
        ]

        // ── Task B: concurrent first-write convergence ──

        testList "first-write race" [

            test "auto-generation marks the key's provenance" {
                let secrets = SeedableSecretStore([]) :> ISecretStore
                let store = ShareTokenStore.create (freshStorage ()) secrets None silentLogger

                match store.Issue(issueRequest "team-a") |> Async.RunSynchronously with
                | Result.Ok _ -> ()
                | Result.Error e -> failtestf "issue failed: %A" e

                Expect.equal
                    (ShareTokenStore.probeSigningKeyProvenance secrets |> Async.RunSynchronously)
                    ShareTokenStore.AutoGenerated
                    "the store records that it minted the key"
            }

            test "a peer replica winning the write does not fork the key — the token still verifies" {
                let peerKey = encodedKey 42uy
                let secrets = PeerWinsSecretStore(peerKey)
                let storage = freshStorage ()

                // Replica A: mints a key, but the peer's write lands over it.
                let replicaA =
                    ShareTokenStore.create storage (secrets :> ISecretStore) None silentLogger

                let issued =
                    match replicaA.Issue(issueRequest "team-a") |> Async.RunSynchronously with
                    | Result.Ok t -> t
                    | Result.Error e -> failtestf "issue failed: %A" e

                Expect.isTrue secrets.Raced "the harness actually raced the write"

                Expect.equal
                    ((secrets :> ISecretStore)
                        .GetSecret(ShareTokenStore.platformContainer, ShareTokenStore.signingKeySecretName)
                     |> Async.RunSynchronously)
                    (Some peerKey)
                    "the peer's key is what the store holds"

                // Replica B: boots later, reads the peer's key, shares the
                // same blob storage. If A had signed with its own minted
                // key, this verification fails.
                let replicaB =
                    ShareTokenStore.create
                        storage
                        (SeedableSecretStore([ ShareTokenStore.signingKeySecretName, peerKey ]) :> ISecretStore)
                        None
                        silentLogger

                match replicaB.Validate issued.Token |> Async.RunSynchronously with
                | Result.Ok claim -> Expect.equal claim.ScopeId "team-a" "the claim round-trips across replicas"
                | Result.Error e -> failtestf "the token minted by replica A did not verify on replica B: %A" e
            }

            test "concurrent first uses within one process converge on a single key" {
                let secrets = SeedableSecretStore([]) :> ISecretStore
                let storage = freshStorage ()

                let stores = [ for _ in 1..6 -> ShareTokenStore.create storage secrets None silentLogger ]

                let issued =
                    stores
                    |> List.mapi (fun i s -> async {
                        let! r = s.Issue(issueRequest $"team-{i}")

                        return
                            match r with
                            | Result.Ok t -> t
                            | Result.Error e -> failtestf "issue failed: %A" e
                    })
                    |> Async.Parallel
                    |> Async.RunSynchronously

                // Every token must verify on every store. A per-replica
                // minted key would leave most of this matrix red.
                for token in issued do
                    for store in stores do
                        match store.Validate token.Token |> Async.RunSynchronously with
                        | Result.Ok _ -> ()
                        | Result.Error e -> failtestf "cross-store verification failed: %A" e
            }
        ]
    ]