<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ToolUpSdkVersion>TOOLUP_SDK_VERSION</ToolUpSdkVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ToolUp.Platform.Core" Version="$(ToolUpSdkVersion)" />
    <PackageVersion Include="ToolUp.Platform.Server" Version="$(ToolUpSdkVersion)" />
    <PackageVersion Include="ToolUp.Platform.Client" Version="$(ToolUpSdkVersion)" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Giraffe" Version="8.2" />
    <PackageVersion Include="Fable.Core" Version="5.0" />
    <PackageVersion Include="Fable.SimpleJson" Version="3.24" />
    <PackageVersion Include="Feliz" Version="3.3.3" />
    <PackageVersion Include="FSharp.Core" Version="10.1.300" />
  </ItemGroup>
</Project>
