// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

module ToolUp.InterPlatform.PythonClientGen

open System
open System.Text

// ─── Phase 18e (Stage 3) — Python client generator ───────────────────
//
// Emits an idiomatic, dependency-free Python peer client from a
// `PeerContractSchema`: a `@dataclass` per referenced record, plus a
// client class with one method per contract method. Uses only the Python
// standard library (`urllib.request` + `json` + `uuid`) so a generated
// client carries no third-party runtime dependency (GP 1 / GP 2) —
// symmetric with the TypeScript generator's dependency-free `fetch`.
//
// Deterministic from the schema (snapshot-tested); the exact F#-DU wire
// encoding is execution-verified by the cross-runtime round-trip harness
// (18e.tail).

let private pascal (s: string) : string =
    if String.IsNullOrEmpty s then
        s
    else
        string (Char.ToUpperInvariant s[0]) + s.Substring 1

/// Map a neutral type reference to a Python type annotation.
let rec pyType (t: PeerTypeRef) : string =
    match t with
    | PrimString -> "str"
    | PrimInt -> "int"
    | PrimFloat -> "float"
    | PrimBool -> "bool"
    | PrimUnit -> "None"
    | PrimGuid -> "str"
    | PrimDateTimeOffset -> "str"
    | OptionOf inner -> $"Optional[{pyType inner}]"
    | ListOf inner -> $"List[{pyType inner}]"
    | RecordRef name -> $"\"{name}\""
    | UnionRef _ -> "Any"
    | Unknown _ -> "Any"

/// Emit the full `.py` client module for a contract schema.
let emit (schema: PeerContractSchema) : string =
    let sb = StringBuilder()
    let line (s: string) = sb.AppendLine s |> ignore

    line "# Generated by ToolUp.InterPlatform PeerSchema -> Python. Do not edit by hand."
    line $"# Contract: {schema.ContractId} (schema v{schema.SchemaVersion})"
    line "import json"
    line "import uuid"
    line "import urllib.request"
    line "from dataclasses import dataclass"
    line "from typing import Optional, List, Any"
    line ""

    for record in schema.Records do
        line "@dataclass"
        line $"class {record.Name}:"

        if List.isEmpty record.Fields then
            line "    pass"
        else
            for fieldName, fieldType in record.Fields do
                line $"    {fieldName}: {pyType fieldType}"

        line ""

    let className = $"{pascal schema.ContractId}Client"

    line $"class {className}:"
    line "    def __init__(self, base_url: str, token: str, caller_peer_id: str):"
    line "        self.base_url = base_url"
    line "        self.token = token"
    line "        self.caller_peer_id = caller_peer_id"
    line ""
    line "    def _context(self):"
    line "        return {"
    line "            \"Peer\": {\"PeerId\": self.caller_peer_id, \"DisplayName\": self.caller_peer_id},"
    line "            \"User\": \"Anonymous\","
    line "            \"ContractVersion\": {\"Major\": 1, \"Minor\": 0},"
    line "            \"Route\": [self.caller_peer_id],"
    line "            \"RootRequestId\": str(uuid.uuid4()),"
    line "            \"ParentRequestId\": None,"
    line "            \"HopsRemaining\": 8,"
    line "        }"
    line ""
    line "    def _rpc(self, method: str, args: list) -> str:"
    line "        payload = {\"Context\": self._context(), \"Arguments\": json.dumps(args)}"

    line
        "        body = {\"JsonRpc\": \"2.0\", \"Method\": method, \"Params\": json.dumps(payload), \"Id\": str(uuid.uuid4())}"

    line $"        req = urllib.request.Request(f\"{{self.base_url}}/peer/v1/{schema.ContractId}\","
    line "            data=json.dumps(body).encode(), method=\"POST\","
    line "            headers={\"Authorization\": f\"Bearer {self.token}\", \"Content-Type\": \"application/json\"})"
    line "        with urllib.request.urlopen(req) as resp:"
    line "            env = json.loads(resp.read())"
    line "        if env.get(\"Error\"):"
    line "            raise RuntimeError(f\"peer error {env['Error']['Code']}: {env['Error']['Message']}\")"
    line "        return env[\"Result\"]"
    line ""

    for m in schema.Methods do
        let args =
            m.Arguments
            |> List.mapi (fun i a -> $"arg{i}: {pyType a}")
            |> String.concat ", "

        let argList = m.Arguments |> List.mapi (fun i _ -> $"arg{i}") |> String.concat ", "

        let sep = if List.isEmpty m.Arguments then "" else ", "

        match m.Lifetime with
        | ImmediateMethod ->
            line $"    def {m.Name}(self{sep}{args}) -> {pyType m.Returns}:"
            line $"        return json.loads(self._rpc(\"{m.Name}\", [{argList}]))"
            line ""
        | LongRunningMethod ->
            line $"    def {m.Name}(self{sep}{args}) -> str:"
            line $"        return json.loads(self._rpc(\"{m.Name}\", [{argList}]))  # job id"
            line ""
            line $"    def poll_{m.Name}(self, job_id: str):"

            line
                $"        req = urllib.request.Request(f\"{{self.base_url}}/peer/v1/{schema.ContractId}/jobs/{{job_id}}\","

            line "            headers={\"Authorization\": f\"Bearer {self.token}\"})"
            line "        with urllib.request.urlopen(req) as resp:"
            line "            env = json.loads(resp.read())"
            line "        status = json.loads(env[\"Result\"])"
            line "        return status.get(\"Completed\")"
            line ""

    sb.ToString()