// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

module ToolUp.InterPlatform.TypeScriptClientGen

open System
open System.Text

// ─── Phase 18e (Stage 2) — TypeScript client generator ───────────────
//
// Emits an idiomatic, dependency-free TypeScript peer client from a
// `PeerContractSchema`: one `interface` per referenced record, plus a
// class with one method per contract method. Each method POSTs the open
// JSON-RPC 2.0 envelope to `/peer/v1/{contractId}` with a bearer token,
// maps a `PeerError` response to a thrown error, and (for long-running
// methods) returns a poll helper over `/peer/v1/{contractId}/jobs/{jobId}`.
//
// The emitted code is deterministic from the schema, so it is pinned by a
// generation snapshot test. The exact F#-DU wire encoding of the call
// context (`User = "Anonymous"` etc.) follows the universal converter
// set's Fable.SimpleJson-compatible shape and is execution-verified by the
// cross-runtime conformance harness (Phase 189), which runs this
// generator's output under a real Node against a live receiver and
// certifies the documents it produces against the federation-seam wire
// corpus.
//
// ─── Phase 189 — the emitted TypeScript is erasable-syntax-only ───────
//
// The class declares its fields and assigns them in the constructor body
// rather than using TypeScript parameter properties
// (`constructor(private baseUrl: string)`). A parameter property is the
// one construct here that a type *eraser* cannot handle — it has to
// synthesise an assignment — so Node refuses it with
// `ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX` in strip-only mode. Emitting the
// longer form means a generated client runs directly on any Node with
// type stripping (>= 22.6 behind `--experimental-strip-types`, >= 23.6
// by default) with **no build step and no toolchain**, which is the same
// promise the dependency-free `fetch` transport already makes.

let private pascal (s: string) : string =
    if String.IsNullOrEmpty s then
        s
    else
        string (Char.ToUpperInvariant s[0]) + s.Substring 1

/// The generated client's class name. A contract id is a dotted path by
/// convention (`example.orders`), and neither TypeScript nor Python
/// accepts a dot in an identifier — so the id is split on its separators
/// and PascalCased segment by segment (`example.orders` →
/// `ExampleOrdersClient`). A single-segment id is unaffected.
let internal clientClassName (contractId: string) : string =
    let segments =
        contractId.Split([| '.'; '-'; '_'; '/'; ' ' |], StringSplitOptions.RemoveEmptyEntries)
        |> Array.map pascal
        |> String.concat ""

    $"{segments}Client"

/// Map a neutral type reference to a TypeScript type expression.
let rec tsType (t: PeerTypeRef) : string =
    match t with
    | PrimString -> "string"
    | PrimInt
    | PrimFloat -> "number"
    | PrimBool -> "boolean"
    | PrimUnit -> "null"
    | PrimGuid -> "string"
    | PrimDateTimeOffset -> "string"
    | OptionOf inner -> $"{tsType inner} | null"
    | ListOf inner -> $"{tsType inner}[]"
    | RecordRef name -> name
    | UnionRef _ -> "unknown"
    | Unknown _ -> "unknown"

/// Emit the full `.ts` client module for a contract schema.
let emit (schema: PeerContractSchema) : string =
    let sb = StringBuilder()
    let line (s: string) = sb.AppendLine s |> ignore

    line "// Generated by ToolUp.InterPlatform PeerSchema → TypeScript. Do not edit by hand."
    line $"// Contract: {schema.ContractId} (schema v{schema.SchemaVersion})"
    line ""

    // The handshake shapes. Emitted unconditionally so `capabilities()`
    // below is typed without the schema having to carry them.
    line "export interface PeerContractVersion {"
    line "  Major: number;"
    line "  Minor: number;"
    line "}"
    line ""
    line "export interface PeerContractCapability {"
    line "  ContractId: string;"
    line "  Versions: PeerContractVersion[];"
    line "}"
    line ""

    // One interface per referenced record.
    for record in schema.Records do
        line $"export interface {record.Name} {{"

        for fieldName, fieldType in record.Fields do
            line $"  {fieldName}: {tsType fieldType};"

        line "}"
        line ""

    let className = clientClassName schema.ContractId

    line $"export class {className} {{"
    line "  private baseUrl: string;"
    line "  private token: string;"
    line "  private callerPeerId: string;"
    line ""
    line "  constructor(baseUrl: string, token: string, callerPeerId: string) {"
    line "    this.baseUrl = baseUrl;"
    line "    this.token = token;"
    line "    this.callerPeerId = callerPeerId;"
    line "  }"
    line ""
    line "  private context() {"
    line "    return {"
    line "      Peer: { PeerId: this.callerPeerId, DisplayName: this.callerPeerId },"
    line "      User: \"Anonymous\","
    line "      ContractVersion: { Major: 1, Minor: 0 },"
    line "      Route: [this.callerPeerId],"
    line "      RootRequestId: crypto.randomUUID(),"
    line "      ParentRequestId: null,"
    line "      HopsRemaining: 8,"
    line "    };"
    line "  }"
    line ""
    line "  private async rpc(method: string, args: unknown[]): Promise<string> {"
    line "    const payload = { Context: this.context(), Arguments: JSON.stringify(args) };"

    line
        "    const body = { JsonRpc: \"2.0\", Method: method, Params: JSON.stringify(payload), Id: crypto.randomUUID() };"

    line $"    const res = await fetch(`${{this.baseUrl}}/peer/v1/{schema.ContractId}`, {{"
    line "      method: \"POST\","
    line "      headers: { \"Authorization\": `Bearer ${this.token}`, \"Content-Type\": \"application/json\" },"
    line "      body: JSON.stringify(body),"
    line "    });"
    line "    const env = await res.json();"
    line "    if (env.Error) throw new Error(`peer error ${env.Error.Code}: ${env.Error.Message}`);"
    line "    return env.Result as string;"
    line "  }"
    line ""
    // The capability handshake. A non-F# peer that cannot ask which
    // contract versions the receiver supports has to hard-code one and
    // find out from a `PeerVersionMismatch` — so the generated client
    // carries the same first-contact call the F# initiator makes.
    line "  async capabilities(): Promise<PeerContractCapability[]> {"
    line "    const res = await fetch(`${this.baseUrl}/peer/v1/capabilities`, {"
    line "      headers: { \"Authorization\": `Bearer ${this.token}` },"
    line "    });"
    line "    if (!res.ok) throw new Error(`peer handshake failed with status ${res.status}`);"
    line "    return await res.json();"
    line "  }"
    line ""

    for m in schema.Methods do
        let args =
            m.Arguments
            |> List.mapi (fun i a -> $"arg{i}: {tsType a}")
            |> String.concat ", "

        let argNames = m.Arguments |> List.mapi (fun i _ -> $"arg{i}") |> String.concat ", "

        match m.Lifetime with
        | ImmediateMethod ->
            line $"  async {m.Name}({args}): Promise<{tsType m.Returns}> {{"
            line $"    const result = await this.rpc(\"{m.Name}\", [{argNames}]);"
            line "    return JSON.parse(result);"
            line "  }"
            line ""
        | LongRunningMethod ->
            // The first leg returns a job id; the caller polls the jobs route.
            line $"  async {m.Name}({args}): Promise<{{ jobId: string }}> {{"
            line $"    const result = await this.rpc(\"{m.Name}\", [{argNames}]);"
            line "    return { jobId: JSON.parse(result) };"
            line "  }"
            line ""
            line $"  async poll{m.Name}(jobId: string): Promise<{tsType m.Returns} | null> {{"
            line $"    const res = await fetch(`${{this.baseUrl}}/peer/v1/{schema.ContractId}/jobs/${{jobId}}`, {{"
            line "      headers: { \"Authorization\": `Bearer ${this.token}` },"
            line "    });"
            line "    const env = await res.json();"
            line "    if (env.Error) throw new Error(env.Error.Message);"
            line "    const status = JSON.parse(env.Result);"
            line "    return status.Completed !== undefined ? status.Completed : null;"
            line "  }"
            line ""

    line "}"
    sb.ToString()