// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

/// Phase 259 — the conformance-pack coverage gate: "ship the pack WITH
/// the interface" enforced by a build gate rather than by review habit.
///
/// **The problem this closes.** Epoch 2's R1 pattern says a substrate
/// seam ships its conformance pack alongside it, and GP 12 says a
/// portable interface is not proven until a SECOND implementation runs
/// the same pack. Both were code-review habits. Nothing computed the
/// answer, and the one place that wrote it down —
/// `docs/platform/portability-rules.md` § "Conformance bar" — listed
/// FIVE current packs against the 97 the tree actually carries. A prose
/// registry of a growing set is a registry that is wrong by the time it
/// is read.
///
/// **Everything here is DERIVED from the checkout.** There is no
/// hand-typed list of seams anywhere in this module, deliberately: a
/// hand-typed universe is exactly how a new seam gets forgotten, which
/// is the failure this gate exists to catch. The four derivations are:
///
///   1. **The public interface set** — every `X (interface)` line in
///      `api-baselines/*.approved.txt`. Those files are generated by
///      Phase 175's `PublicApiApproval` and drift-gated in BOTH
///      directions by Phase 618, so they cannot silently go stale; that
///      is precisely why they are the universe rather than a source
///      scan for `type I… =`, which would also sweep up private and
///      internal shapes that no consumer can implement.
///   2. **The packs** — `src/ToolUp.Platform.Tests/Contracts/*Contract.fs`.
///   3. **The bindings** — `<Pack>.tests` call sites across `src/`. Each
///      one is an implementation running the pack against itself.
///   4. **The production implementation count** — `interface I… with` /
///      `new I… with` occurrences OUTSIDE the test projects.
///
/// **The universe that MUST carry a pack is (1) ∩ (4 ≥ 2).** A public
/// interface with two or more production implementations is a
/// replaceable seam BY CONSTRUCTION — that is the definition GP 12
/// already uses, read off the tree instead of asserted about it. The
/// moment a second implementation of anything lands, that interface
/// enters the must-pack set with no edit to this file. 381 public
/// interfaces are not all seams; 146 of them are.
///
/// **The registry is a RATCHET BASELINE, not a threshold.** Measured on
/// the untouched tree at the phase's start: 51 of 146 replaceable seams
/// carry a pack (34.9%), and 63 of the 96 entry-point packs are bound by
/// exactly one implementation. A gate demanding either property outright
/// would be red on arrival, and a gate that is red on arrival is one
/// people learn to step over. So the two shortfalls are *pinned as
/// committed lists* — the same shape as the api-baselines beside them,
/// and drift in EITHER direction fails: a NEW unpacked seam or a NEW
/// single-bound pack fails immediately (nothing is forgotten), and a
/// name that has since been fixed must be REMOVED from the baseline
/// (the ratchet cannot slip back, and the file cannot rot). The
/// threshold is therefore "today, and never worse", which needs no
/// number to tune and no ratchet plan to remember: the plan is the
/// shrinking file.
///
/// **Counts are deliberately NOT recorded in the baseline.** Only names.
/// An implementation count churns on every unrelated commit, and a
/// baseline that churns is one whose failures stop being read. The full
/// annotated census — pack type, binding labels, implementation counts,
/// the shard's "implementations expected to bind it" — is DERIVED on
/// demand by `census` below, which is strictly better than a recorded
/// one because it cannot disagree with the tree.
///
/// **Pure over its inputs, BCL-only.** Every parser takes text and
/// returns data, so the companion pack drives each one from synthetic
/// fixtures and proves the gate fails closed. Same philosophy as
/// `ArchitectureFitness` and `SdkManifest`: a drift guard whose failure
/// path is never exercised is indistinguishable from one that cannot
/// fail.
module ToolUp.Platform.Build.Tests.ConformanceCoverage

open System
open System.IO
open System.Text
open System.Text.RegularExpressions

// ─── Paths ────────────────────────────────────────────────────────────

/// The directory the contract packs live in.
let contractsDir (root: string) =
    Path.Combine(root, "src", "ToolUp.Platform.Tests", "Contracts")

/// The committed ratchet baseline. It sits WITH the packs rather than
/// with the gate: it is a statement about the contents of that
/// directory, and a reader browsing `Contracts/` should meet it there.
let registryPath (root: string) =
    Path.Combine(contractsDir root, "conformance-coverage.approved.txt")

/// The api-baselines directory — the universe's source.
let apiBaselinesDir (root: string) = Path.Combine(root, "api-baselines")

/// The command that repairs every finding this module can report.
///
/// Deliberately the SAME switch the api-baselines use rather than a new
/// one. This artefact is an approval baseline of exactly their family,
/// and a reviewer who has decided to accept the tree's current shape
/// wants both regenerated in one pass. A second env var would also need
/// a `ConfigKeyDescriptor` row, and a config surface is a poor price for
/// a synonym.
let regenerateCommand =
    "$env:TOOLUP_APPROVE_API = \"1\"; dotnet run --project Build.fsproj -- VerifyAll; $env:TOOLUP_APPROVE_API = $null"

let private approveEnvVar = "TOOLUP_APPROVE_API"

/// True when the caller has asked for baselines to be rewritten rather
/// than checked.
let approvalRequested () =
    match Environment.GetEnvironmentVariable approveEnvVar with
    | null -> false
    | v -> v.Trim() <> "" && v.Trim() <> "0"

// ─── Pure parsers ─────────────────────────────────────────────────────

/// `Foo+IBar (interface)` / `IBar (interface)` -> `IBar`. Nested-type and
/// namespace qualification are stripped to the simple name, and a
/// generic arity suffix (`IBar\`1`) with it, because every other
/// derivation here keys on the simple name a source file writes.
let private simpleTypeName (qualified: string) =
    let afterDot =
        match qualified.LastIndexOfAny([| '.'; '+' |]) with
        | -1 -> qualified
        | i -> qualified.Substring(i + 1)

    match afterDot.IndexOf('`') with
    | -1 -> afterDot
    | i -> afterDot.Substring(0, i)

let private interfaceLine =
    Regex(@"^(?<name>[A-Za-z0-9_.+`]+) \(interface\)$", RegexOptions.Compiled ||| RegexOptions.Multiline)

/// Every interface simple-name an api-baseline text declares.
let interfaceNamesIn (baselineText: string) : string list =
    interfaceLine.Matches baselineText
    |> Seq.map (fun m -> simpleTypeName m.Groups["name"].Value)
    |> Seq.distinct
    |> List.ofSeq

/// An F# interface-implementation site: `interface IFoo with` (a type's
/// implementation clause) or `new IFoo with` (an object expression).
/// Generic arguments are tolerated between the name and `with`.
let private implSite =
    Regex(@"\b(?:interface|new)\s+(?<name>I[A-Za-z0-9_]+)\s*(?:<[^>\n]*>)?\s+with\b", RegexOptions.Compiled)

/// Every interface implemented in one source text, one entry per site
/// (so a file implementing the same seam twice counts twice — two object
/// expressions are two implementations).
let implementedInterfacesIn (sourceText: string) : string list =
    implSite.Matches sourceText
    |> Seq.map (fun m -> m.Groups["name"].Value)
    |> List.ofSeq

/// `IJobSchedulerContract.fs` -> `Some "IJobSchedulerContract"`. Anything
/// not named `*Contract.fs` is not a pack.
let packNameOfFile (fileName: string) : string option =
    let stem = Path.GetFileNameWithoutExtension fileName

    if
        stem.EndsWith("Contract", StringComparison.Ordinal)
        && stem.Length > "Contract".Length
    then
        Some stem
    else
        None

/// The interface a pack is about: the pack name minus its `Contract`
/// suffix. `IJobSchedulerContract` -> `IJobScheduler`.
let interfaceOfPack (packName: string) =
    packName.Substring(0, packName.Length - "Contract".Length)

/// A pack is *bindable* when it exposes a `tests` entry point an
/// implementation can call. Matched at line start with the signature
/// allowed to continue on the next line, because several packs are
/// formatted `let tests` / `    (name: string)` and a stricter pattern
/// silently classified four of them as unbindable.
let private entryPoint =
    Regex(@"^let tests($|[\s:])", RegexOptions.Compiled ||| RegexOptions.Multiline)

let hasEntryPoint (packText: string) = entryPoint.IsMatch packText

/// Binding call sites in one source text: occurrences of `<Pack>.tests`
/// for any pack in `packNames`.
let bindingsIn (packNames: Set<string>) (sourceText: string) : string list =
    Regex.Matches(sourceText, @"\b(?<pack>I?[A-Za-z0-9_]+Contract)\.tests\b")
    |> Seq.map (fun m -> m.Groups["pack"].Value)
    |> Seq.filter packNames.Contains
    |> List.ofSeq

// ─── Tree readers ─────────────────────────────────────────────────────

/// A file lives in a test project when any directory segment of its path
/// mentions `Test`. Production implementations are what make a seam
/// replaceable; a test double proves nothing about portability, and
/// counting doubles would have promoted most of the BCL into the
/// must-pack set.
let private isTestPath (path: string) =
    path.Replace('\\', '/').Split('/')
    |> Array.exists (fun seg -> seg.Contains "Test")

let private sourceFiles (root: string) =
    let srcDir = Path.Combine(root, "src")

    if Directory.Exists srcDir then
        Directory.EnumerateFiles(srcDir, "*.fs", SearchOption.AllDirectories)
        |> List.ofSeq
    else
        []

/// Every public interface the repo's api-baselines declare.
let publicInterfaces (root: string) : Set<string> =
    let dir = apiBaselinesDir root

    if not (Directory.Exists dir) then
        Set.empty
    else
        Directory.EnumerateFiles(dir, "*.approved.txt")
        |> Seq.collect (File.ReadAllText >> interfaceNamesIn)
        |> Set.ofSeq

type Pack = {
    /// `IJobSchedulerContract`.
    Name: string
    /// `IJobScheduler` — the interface the pack is about.
    Interface: string
    /// Exposes a `tests` entry point an implementation can bind.
    Bindable: bool
}

let packs (root: string) : Pack list =
    let dir = contractsDir root

    if not (Directory.Exists dir) then
        []
    else
        Directory.EnumerateFiles(dir, "*Contract.fs")
        |> Seq.choose (fun file ->
            packNameOfFile file
            |> Option.map (fun name -> {
                Name = name
                Interface = interfaceOfPack name
                Bindable = hasEntryPoint (File.ReadAllText file)
            }))
        |> Seq.sortBy _.Name
        |> List.ofSeq

/// How many implementations bind each pack, keyed by pack name.
let bindingCounts (root: string) (allPacks: Pack list) : Map<string, int> =
    let names = allPacks |> List.map _.Name |> Set.ofList

    sourceFiles root
    |> Seq.collect (File.ReadAllText >> bindingsIn names)
    |> Seq.countBy id
    |> Map.ofSeq

/// How many PRODUCTION sites implement each interface.
let productionImplCounts (root: string) : Map<string, int> =
    sourceFiles root
    |> Seq.filter (fun f -> not (isTestPath (Path.GetRelativePath(root, f))))
    |> Seq.collect (File.ReadAllText >> implementedInterfacesIn)
    |> Seq.countBy id
    |> Map.ofSeq

/// A public interface with two or more production implementations: a
/// replaceable seam, by construction rather than by assertion.
let replaceableSeams (root: string) : Map<string, int> =
    let public' = publicInterfaces root

    productionImplCounts root
    |> Map.filter (fun name count -> count >= 2 && public'.Contains name)

// ─── The committed registry ───────────────────────────────────────────

type Registry = {
    /// Replaceable seams known to carry no pack. May only shrink.
    Unpacked: string list
    /// Packs bound by exactly one implementation. May only shrink.
    SingleBound: string list
    /// Hand-authored: a seam that will never carry a pack, and why.
    /// Never written by the generator — a regeneration carries it
    /// through verbatim, because a rationale a machine can rewrite is
    /// a rationale nobody wrote.
    Exempt: (string * string) list
}

let emptyRegistry = {
    Unpacked = []
    SingleBound = []
    Exempt = []
}

[<Literal>]
let private unpackedHeader = "[UNPACKED]"

[<Literal>]
let private singleBoundHeader = "[SINGLE-BOUND]"

[<Literal>]
let private exemptHeader = "[EXEMPT]"

/// Parse the committed baseline. Blank lines and `#` comments are
/// ignored; an `[EXEMPT]` row is `<name>: <reason>`.
let parseRegistry (text: string) : Registry =
    let mutable section = ""
    let unpacked = ResizeArray<string>()
    let singleBound = ResizeArray<string>()
    let exempt = ResizeArray<string * string>()

    for rawLine in text.Replace("\r\n", "\n").Split('\n') do
        let line = rawLine.Trim()

        if line = "" || line.StartsWith("#", StringComparison.Ordinal) then
            ()
        elif line.StartsWith("[", StringComparison.Ordinal) then
            section <- line
        else
            match section with
            | s when s = unpackedHeader -> unpacked.Add line
            | s when s = singleBoundHeader -> singleBound.Add line
            | s when s = exemptHeader ->
                match line.IndexOf(':') with
                | -1 -> exempt.Add(line, "")
                | i -> exempt.Add(line.Substring(0, i).Trim(), line.Substring(i + 1).Trim())
            | _ -> ()

    {
        Unpacked = List.ofSeq unpacked
        SingleBound = List.ofSeq singleBound
        Exempt = List.ofSeq exempt
    }

let readRegistry (root: string) : Registry =
    let path = registryPath root

    if File.Exists path then
        parseRegistry (File.ReadAllText path)
    else
        emptyRegistry

// ─── Reconciliation ───────────────────────────────────────────────────

type Finding =
    /// A replaceable seam with no pack that the baseline does not know
    /// about. THE finding this gate exists for: a new seam, forgotten.
    | NewUnpackedSeam of seam: string * productionImpls: int
    /// A baseline entry that is no longer true — packed since, or no
    /// longer a replaceable seam. The ratchet's other direction.
    | StaleUnpacked of seam: string * why: string
    /// A pack only one implementation runs, which the baseline does not
    /// know about. GP 12's "second implementation" rule, shifted left.
    | NewSingleBoundPack of pack: string * bindings: int
    | StaleSingleBound of pack: string * why: string
    /// A bindable pack nothing calls: conformance code that runs against
    /// nothing at all.
    | UnboundPack of pack: string
    /// An exemption for something that is not a replaceable seam.
    | StaleExempt of seam: string * why: string

type Reconciliation = {
    Findings: Finding list
    /// Replaceable seams (public interface, ≥2 production impls).
    SeamCount: int
    /// How many of them carry a pack.
    PackedSeamCount: int
    PackCount: int
    BindablePackCount: int
    /// Packs bound by ≥2 implementations.
    MultiBoundPackCount: int
}

let private reconcileFrom
    (seams: Map<string, int>)
    (allPacks: Pack list)
    (bindings: Map<string, int>)
    (registry: Registry)
    : Reconciliation =
    let packedInterfaces = allPacks |> List.map _.Interface |> Set.ofList
    let exempt = registry.Exempt |> List.map fst |> Set.ofList
    let bindablePacks = allPacks |> List.filter _.Bindable

    let bindingOf (p: Pack) =
        bindings |> Map.tryFind p.Name |> Option.defaultValue 0

    let unpackedNow =
        seams
        |> Map.filter (fun name _ -> not (packedInterfaces.Contains name))
        |> Map.keys
        |> Set.ofSeq

    let singleBoundNow =
        bindablePacks
        |> List.filter (fun p -> bindingOf p = 1)
        |> List.map _.Name
        |> Set.ofList

    let baselineUnpacked = Set.ofList registry.Unpacked
    let baselineSingleBound = Set.ofList registry.SingleBound

    let newUnpacked =
        unpackedNow - baselineUnpacked - exempt
        |> Seq.sort
        |> Seq.map (fun s -> NewUnpackedSeam(s, seams[s]))
        |> List.ofSeq

    let staleUnpacked =
        baselineUnpacked - unpackedNow
        |> Seq.sort
        |> Seq.map (fun s ->
            let why =
                if packedInterfaces.Contains s then
                    "it now HAS a contract pack — the ratchet moved, so drop the row"
                elif not (seams.ContainsKey s) then
                    "it is no longer a replaceable seam (public with ≥2 production implementations) — drop the row"
                else
                    "it no longer matches the baseline — drop the row"

            StaleUnpacked(s, why))
        |> List.ofSeq

    let newSingleBound =
        singleBoundNow - baselineSingleBound
        |> Seq.sort
        |> Seq.map (fun p -> NewSingleBoundPack(p, 1))
        |> List.ofSeq

    let staleSingleBound =
        baselineSingleBound - singleBoundNow
        |> Seq.sort
        |> Seq.map (fun p ->
            let why =
                match bindablePacks |> List.tryFind (fun x -> x.Name = p) with
                | Some pack when bindingOf pack >= 2 ->
                    sprintf "%d implementations bind it now — the ratchet moved, so drop the row" (bindingOf pack)
                | Some _ -> "nothing binds it any more — it is reported as an unbound pack instead, so drop the row"
                | None -> "no bindable pack of that name exists any more — drop the row"

            StaleSingleBound(p, why))
        |> List.ofSeq

    let unbound =
        bindablePacks
        |> List.filter (fun p -> bindingOf p = 0)
        |> List.map (fun p -> UnboundPack p.Name)

    let staleExempt =
        registry.Exempt
        |> List.filter (fun (name, _) -> not (unpackedNow.Contains name))
        |> List.map (fun (name, _) ->
            let why =
                if packedInterfaces.Contains name then
                    "it has a pack now, so the exemption is spent"
                else
                    "it is not a replaceable seam, so nothing was being exempted"

            StaleExempt(name, why))

    {
        Findings =
            newUnpacked
            @ staleUnpacked
            @ newSingleBound
            @ staleSingleBound
            @ unbound
            @ staleExempt
        SeamCount = seams.Count
        PackedSeamCount = seams |> Map.filter (fun n _ -> packedInterfaces.Contains n) |> Map.count
        PackCount = allPacks.Length
        BindablePackCount = bindablePacks.Length
        MultiBoundPackCount = bindablePacks |> List.filter (fun p -> bindingOf p >= 2) |> List.length
    }

/// Pure reconciliation over synthetic inputs — the seam the companion
/// pack drives to prove each finding class fires.
let reconcileWith = reconcileFrom

let reconcile (root: string) : Reconciliation =
    let allPacks = packs root
    reconcileFrom (replaceableSeams root) allPacks (bindingCounts root allPacks) (readRegistry root)

// ─── Reporting ────────────────────────────────────────────────────────

let describeFinding =
    function
    | NewUnpackedSeam(seam, impls) ->
        sprintf
            "%s is a replaceable seam (%d production implementations) with NO contract pack, and the baseline does not know about it. Author src/ToolUp.Platform.Tests/Contracts/%sContract.fs and bind it, or — if it genuinely cannot be packed — add an [EXEMPT] row with the reason."
            seam
            impls
            seam
    | StaleUnpacked(seam, why) -> sprintf "[UNPACKED] carries %s, but %s" seam why
    | NewSingleBoundPack(pack, _) ->
        sprintf
            "%s is bound by exactly ONE implementation. GP 12 treats a portable interface as unproven until a second implementation runs the same pack. Bind a second one, or add the pack to [SINGLE-BOUND] with the coverage debt acknowledged."
            pack
    | StaleSingleBound(pack, why) -> sprintf "[SINGLE-BOUND] carries %s, but %s" pack why
    | UnboundPack pack ->
        sprintf
            "%s exposes a `tests` entry point that NOTHING calls. A conformance pack no implementation runs proves nothing; bind it or delete it."
            pack
    | StaleExempt(seam, why) -> sprintf "[EXEMPT] carries %s, but %s" seam why

/// One human-readable account of a reconciliation, or `None` when it is
/// clean.
let describe (r: Reconciliation) : string option =
    if List.isEmpty r.Findings then
        None
    else
        let sb = StringBuilder()

        sb
            .AppendFormat(
                "Conformance-pack coverage: {0} finding(s). {1} of {2} replaceable seams carry a pack; {3} of {4} bindable packs are bound by two or more implementations.",
                List.length r.Findings,
                r.PackedSeamCount,
                r.SeamCount,
                r.MultiBoundPackCount,
                r.BindablePackCount
            )
            .AppendLine()
        |> ignore

        for finding in r.Findings do
            sb.AppendLine().Append("  - ").Append(describeFinding finding) |> ignore

        sb
            .AppendLine()
            .AppendLine()
            .AppendFormat(
                "  The baseline is {0}. Every row is coverage debt, and it may only SHRINK — a stale row fails here precisely so the ratchet cannot slip back. To accept the tree's current shape wholesale: {1}",
                "src/ToolUp.Platform.Tests/Contracts/conformance-coverage.approved.txt",
                regenerateCommand
            )
            .AppendLine()
        |> ignore

        Some(sb.ToString())

/// The derived census the shard asks the registry to carry: every
/// replaceable seam, its pack, and the implementations expected to bind
/// it. Derived rather than committed — a recorded census disagrees with
/// the tree the moment an implementation lands, and this one cannot.
let census (root: string) : string =
    let allPacks = packs root
    let bindings = bindingCounts root allPacks
    let byInterface = allPacks |> List.map (fun p -> p.Interface, p) |> Map.ofList
    let sb = StringBuilder()

    for seam, impls in replaceableSeams root |> Map.toList |> List.sortBy fst do
        let packCell =
            match Map.tryFind seam byInterface with
            | Some p -> sprintf "%s (bound by %d)" p.Name (bindings |> Map.tryFind p.Name |> Option.defaultValue 0)
            | None -> "— no pack —"

        sb.AppendFormat("{0,-44} impls={1,-4} {2}", seam, impls, packCell).AppendLine()
        |> ignore

    sb.ToString()

// ─── Rendering the baseline ───────────────────────────────────────────

let private renderFrom
    (seams: Map<string, int>)
    (allPacks: Pack list)
    (bindings: Map<string, int>)
    (existing: Registry)
    =
    let packedInterfaces = allPacks |> List.map _.Interface |> Set.ofList
    let exempt = existing.Exempt |> List.map fst |> Set.ofList

    let unpacked =
        seams
        |> Map.filter (fun name _ -> not (packedInterfaces.Contains name) && not (exempt.Contains name))
        |> Map.keys
        |> Seq.sort
        |> List.ofSeq

    let singleBound =
        allPacks
        |> List.filter (fun p -> p.Bindable && (bindings |> Map.tryFind p.Name |> Option.defaultValue 0) = 1)
        |> List.map _.Name
        |> List.sort

    let nl = "\n"
    let sb = StringBuilder()

    sb
        .Append("# Conformance-pack coverage baseline (Phase 259).")
        .Append(nl)
        .Append("#")
        .Append(nl)
        .Append("# GENERATED — regenerate rather than hand-edit the two ratchet sections.")
        .Append(nl)
        .Append("# [EXEMPT] is the exception: it is hand-authored and carried through a")
        .Append(nl)
        .Append("# regeneration verbatim, because a rationale a machine can rewrite is a")
        .Append(nl)
        .Append("# rationale nobody wrote.")
        .Append(nl)
        .Append("#")
        .Append(nl)
        .Append("# Each row is COVERAGE DEBT. The gate fails on drift in EITHER direction:")
        .Append(nl)
        .Append("# a name that appears and is not here (a seam nobody packed, a pack only")
        .Append(nl)
        .Append("# one implementation runs), and a name here that has since been fixed and")
        .Append(nl)
        .Append("# must be removed. So the list may only SHRINK — that is the whole ratchet,")
        .Append(nl)
        .Append("# and it needs no threshold to tune.")
        .Append(nl)
        .Append("#")
        .Append(nl)
        .Append("# The universe is DERIVED, never listed: a replaceable seam is a public")
        .Append(nl)
        .Append("# interface (api-baselines) with two or more production implementations.")
        .Append(nl)
        .Append("# A new seam therefore arrives here on its own rather than being forgotten.")
        .Append(nl)
    |> ignore

    let packedSeamCount =
        seams |> Map.filter (fun name _ -> packedInterfaces.Contains name) |> Map.count

    let bindablePacks = allPacks |> List.filter _.Bindable

    let multiBoundCount =
        bindablePacks
        |> List.filter (fun p -> (bindings |> Map.tryFind p.Name |> Option.defaultValue 0) >= 2)
        |> List.length

    sb
        .Append("#")
        .Append(nl)
        .AppendFormat(
            "# At generation: {0} of {1} replaceable seams packed; {2} of {3} bindable packs bound twice or more.",
            packedSeamCount,
            seams.Count,
            multiBoundCount,
            bindablePacks.Length
        )
        .Append(nl)
    |> ignore

    sb
        .Append(nl)
        .Append("# Replaceable seams carrying no contract pack. Author the pack and drop the row.")
        .Append(nl)
        .Append(unpackedHeader)
        .Append(nl)
    |> ignore

    for name in unpacked do
        sb.Append(name).Append(nl) |> ignore

    sb
        .Append(nl)
        .Append("# Packs exercised by exactly one implementation. GP 12 treats the interface")
        .Append(nl)
        .Append("# as unproven until a second one runs the same pack. Bind one and drop the row.")
        .Append(nl)
        .Append(singleBoundHeader)
        .Append(nl)
    |> ignore

    for name in singleBound do
        sb.Append(name).Append(nl) |> ignore

    sb
        .Append(nl)
        .Append("# Seams that will never carry a pack, with the reason. `<name>: <why>`.")
        .Append(nl)
        .Append("# Hand-authored; a regeneration preserves these rows.")
        .Append(nl)
        .Append(exemptHeader)
        .Append(nl)
    |> ignore

    for name, why in existing.Exempt |> List.sortBy fst do
        sb.Append(name).Append(": ").Append(why).Append(nl) |> ignore

    sb.ToString()

/// The baseline text for `root`, preserving whatever `[EXEMPT]` rows the
/// committed file already carries.
let render (root: string) =
    let allPacks = packs root
    renderFrom (replaceableSeams root) allPacks (bindingCounts root allPacks) (readRegistry root)

/// Rewrite the committed baseline from the tree. Called only under
/// `TOOLUP_APPROVE_API`.
let approve (root: string) =
    let path = registryPath root
    Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
    File.WriteAllText(path, render root)
    path