// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

module ToolUp.Platform.Build.Tests.SemVerBumpTests

open System.IO
open System.Reflection
open Expecto
open ToolUp.Forge
open ToolUp.Forge.SemVerBump

// ─── Phase 260 — the release bump derived from the API diff ───────────
//
// `VerifySemVerBump` runs once, at a release, against a git history. This
// pack runs on every commit against strings, and it is where the rule
// itself is decided — so the release is not the first time anything here
// has been exercised. Same split, and same reason, as Phase 184's
// `PublishedSmokeTests` and Phase 326's `SdkManifestTests`: the module is
// source-linked from the repo root, not copied, so the target and these
// proofs cannot come to different conclusions.
//
// ── The two policy tables are BOTH pinned, deliberately ──
// The phase shard specifies the ordinary SemVer mapping — breaking →
// major, additive → minor, unchanged → patch. This repo is on `0.x`, and
// states its own policy twice in `Directory.Build.props`: "minor bumps
// may include breaking changes during 0.x; patch bumps remain
// non-breaking", and "MINOR is where this repo's SemVer-on-0.x policy
// puts a break". Those are two different tables and the check needs both:
// the 0.x one is what fires today, the shard's is what fires from 1.0.0.
// Pinning only the live one would let the 1.0 transition silently change
// what the gate means, on the exact release where it matters most.
//
// ── The vacuity pins are not padding ──
// The whole computation is a set difference plus a comparison of two
// triples, and both are clean over empty inputs. A classifier that
// stopped seeing tokens, or a release-point selector that returned
// nothing, would report "unchanged, patch is fine" for every release
// forever — a green that means the gate has died. `an unchanged pair
// really is unchanged` alone cannot tell those apart, so each direction
// is proven able to fire.
//
// Zero shipped code: test tier plus a repo-root build file (GP 13).

/// Repo root (`toolup-forge`) from the running test assembly:
/// `src/ToolUp.Platform.Build.Tests/bin/<Config>/net10.0` -> up 5. The
/// same walk `SdkManifestTests` and `PublicApiApproval.repoRoot` use.
let private repoRoot () =
    let assemblyDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)

    Path.GetFullPath(Path.Combine(assemblyDir, "..", "..", "..", "..", ".."))

/// A minimal baseline text in the shape the renderer emits: a comment
/// preamble the comparer ignores, then one line per member.
let private baseline (members: string list) =
    let header =
        "# Public API baseline — Demo\n# Generated by Phase 175 PublicApiApproval — regenerate with TOOLUP_APPROVE_API=1.\n"

    header + (members |> List.map (fun m -> m + "\n") |> String.concat "")

let private alpha = "Demo.T.Alpha() : System.Int32"
let private beta = "Demo.T.Beta() : System.String"
let private gamma = "Demo.T.Gamma() : System.Boolean"

let private v (major, minor, patch) = {
    Major = major
    Minor = minor
    Patch = patch
}

/// One package, classified between two baselines that both exist.
let private change (released: string list) (current: string list) =
    classifyPackage "Demo" (Some(baseline released)) (Some(baseline current))

/// An assessment over one package, from `released` to `declared`.
let private assessOne releasedVersion declaredVersion (changes: PackageChange list) =
    assess "vX" releasedVersion declaredVersion changes

let tests =
    testList "SemVerBump" [

        // ── Vacuity: each classification is proven able to fire ───────

        testCase "an unchanged pair classifies unchanged" (fun _ ->
            let c = change [ alpha; beta ] [ alpha; beta ]
            Expect.equal c.Class Unchanged "identical baselines are not a surface change"
            Expect.isEmpty c.Removed "nothing removed"
            Expect.isEmpty c.Added "nothing added")

        testCase "an added member classifies additive and names it" (fun _ ->
            let c = change [ alpha ] [ alpha; gamma ]
            Expect.equal c.Class Additive "a new member is additive"
            Expect.equal c.Added [ gamma ] "the added token is reported"
            Expect.isEmpty c.Removed "nothing was removed")

        testCase "a removed member classifies breaking and names it" (fun _ ->
            let c = change [ alpha; beta ] [ alpha ]
            Expect.equal c.Class Breaking "a lost member is breaking"
            Expect.equal c.Removed [ beta ] "the removed token is reported")

        testCase "a retyped member reads as breaking, not additive" (fun _ ->
            // A rename or retype is a token vanishing and another
            // appearing. Both arms fire; breaking wins, because the old
            // token really is gone for a consumer.
            let c = change [ alpha ] [ "Demo.T.Alpha() : System.Int64" ]
            Expect.equal c.Class Breaking "a retype is a removal from the consumer's side"
            Expect.equal c.Removed [ alpha ] "the old token is reported as lost")

        // ── The comparer is the GATE's, not a second copy ─────────────

        testCase "an [<Obsolete>] marking classifies additive with no special case" (fun _ ->
            // Phase 258's sanctioned rendering is a SEPARATE marker line
            // beside the untouched member token, so it reaches this
            // classifier as an ordinary addition. Pinned here because the
            // deprecation policy's promise — deprecating is a minor, not
            // a major — is only true while that stays so.
            let c = change [ alpha ] [ alpha; alpha + "  (obsolete)" ]
            Expect.equal c.Class Additive "adding a deprecation marker is additive"
            Expect.isEmpty c.Removed "the member token itself is untouched")

        testCase "the SDK-band-dependent serialization ctor is ignored on both sides" (fun _ ->
            // The one token whose presence depends on which SDK feature
            // band built the DLL. `SurfaceDiff` excludes it; a second
            // tokeniser that forgot to would read an ordinary band
            // difference as a removal and demand a breaking bump for a
            // change nobody made. That skew reddened CI across eleven
            // assemblies on 2026-08-19, which is why this classifier
            // reuses the gate's comparer instead of owning one.
            let ctor =
                "Demo.T..ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)"

            let c = change [ alpha; ctor ] [ alpha ]
            Expect.equal c.Class Unchanged "a band-dependent ctor difference is not a surface change")

        // ── Whole-package shapes ──────────────────────────────────────

        testCase "a withdrawn package is breaking and is flagged as a withdrawal" (fun _ ->
            let c = classifyPackage "Demo" (Some(baseline [ alpha; beta ])) None
            Expect.equal c.Class Breaking "a package that stops being produced is breaking"
            Expect.isTrue c.Withdrawn "the withdrawal is flagged for the report"
            Expect.equal c.Removed.Length 2 "every member of the withdrawn package is lost")

        testCase "an introduced package is additive and is flagged as new" (fun _ ->
            let c = classifyPackage "Demo" None (Some(baseline [ alpha ]))
            Expect.equal c.Class Additive "a brand-new package breaks nobody"
            Expect.isTrue c.Introduced "the introduction is flagged for the report"
            Expect.equal c.Added [ alpha ] "its members are reported as additions")

        // ── The lockstep roll-up ──────────────────────────────────────

        testCase "the roll-up takes the highest class across packages" (fun _ ->
            let changes = [
                classifyPackage "A" (Some(baseline [ alpha ])) (Some(baseline [ alpha ]))
                classifyPackage "B" (Some(baseline [ alpha ])) (Some(baseline [ alpha; gamma ]))
                classifyPackage "C" (Some(baseline [ alpha; beta ])) (Some(baseline [ alpha ]))
            ]

            Expect.equal (rollUp changes) Breaking "one breaking package makes the lockstep release breaking")

        testCase "the roll-up over no changes is unchanged" (fun _ ->
            Expect.equal (rollUp []) Unchanged "nothing moved")

        // ── The two policy tables ─────────────────────────────────────

        testCase "on 0.x a breaking surface demands a MINOR" (fun _ ->
            // The repo's own policy, stated twice in
            // Directory.Build.props. This is the table that fires today.
            Expect.equal (demandedBump true Breaking) Minor "0.x puts a break in the minor slot"
            Expect.equal (demandedBump true Additive) Patch "0.x compatible growth fits a patch"
            Expect.equal (demandedBump true Unchanged) Patch "no surface change needs no slot")

        testCase "from 1.0.0 the ordinary SemVer table applies" (fun _ ->
            Expect.equal (demandedBump false Breaking) Major "a break past 1.0 is a major"
            Expect.equal (demandedBump false Additive) Minor "additive growth past 1.0 is a minor"
            Expect.equal (demandedBump false Unchanged) Patch "no surface change is a patch")

        testCase "the table is selected by the RELEASED version, not the declared one" (fun _ ->
            // The promise a consumer holds is the one attached to the
            // version they are on. Releasing 1.0.0 out of 0.23.0 with a
            // breaking diff is judged under the 0.x table — and 1.0.0
            // clears that floor comfortably, which is the right answer.
            let a = assessOne (v (0, 23, 0)) (v (1, 0, 0)) [ change [ alpha; beta ] [ alpha ] ]
            Expect.equal a.Demanded Minor "measured against the 0.x release point"
            Expect.isTrue (meetsDemand a) "a major clears a minor floor")

        // ── The four shard fixtures, on the 1.x table ─────────────────

        testCase "shard fixture: a removed symbol demands major (1.x)" (fun _ ->
            let a = assessOne (v (1, 2, 3)) (v (2, 0, 0)) [ change [ alpha; beta ] [ alpha ] ]
            Expect.equal a.Class Breaking "the surface broke"
            Expect.equal a.Demanded Major "a break past 1.0 demands a major"
            Expect.equal a.Proposed (v (2, 0, 0)) "the proposal is the smallest version that satisfies it"
            Expect.isTrue (meetsDemand a) "2.0.0 meets it")

        testCase "shard fixture: an additive-only change demands minor (1.x)" (fun _ ->
            let a = assessOne (v (1, 2, 3)) (v (1, 3, 0)) [ change [ alpha ] [ alpha; gamma ] ]
            Expect.equal a.Class Additive "the surface grew"
            Expect.equal a.Demanded Minor "additive growth past 1.0 demands a minor"
            Expect.equal a.Proposed (v (1, 3, 0)) "the proposal advances the minor slot and zeroes the patch"
            Expect.isTrue (meetsDemand a) "1.3.0 meets it")

        testCase "shard fixture: an unchanged surface demands patch (1.x)" (fun _ ->
            let a = assessOne (v (1, 2, 3)) (v (1, 2, 4)) [ change [ alpha ] [ alpha ] ]
            Expect.equal a.Class Unchanged "the surface did not move"
            Expect.equal a.Demanded Patch "a release with no surface change is a patch"
            Expect.equal a.Proposed (v (1, 2, 4)) "the proposal advances the patch slot"
            Expect.isTrue (meetsDemand a) "1.2.4 meets it")

        testCase "shard fixture: an under-bump FAILS the check" (fun _ ->
            let a = assessOne (v (1, 2, 3)) (v (1, 2, 4)) [ change [ alpha; beta ] [ alpha ] ]
            Expect.isFalse (meetsDemand a) "a patch cannot carry a break past 1.0"

            match defect a with
            | None -> failtest "an under-bump must produce a defect report"
            | Some report ->
                Expect.stringContains report "UNDER-BUMP" "the report leads with the verdict"
                Expect.stringContains report "2.0.0" "the report names the smallest correct version"
                Expect.stringContains report beta "the report names the member whose loss makes it breaking")

        testCase "an under-bump on 0.x fails the same way, one slot down" (fun _ ->
            // The live shape: a break shipped as a patch while pre-1.0.
            let a = assessOne (v (0, 22, 0)) (v (0, 22, 1)) [ change [ alpha; beta ] [ alpha ] ]
            Expect.equal a.Demanded Minor "0.x puts the break in the minor slot"
            Expect.isFalse (meetsDemand a) "0.22.1 is a patch and does not carry it"
            Expect.isSome (defect a) "and it is reported")

        testCase "a version that EXCEEDS the demand passes" (fun _ ->
            // The floor is a floor. A deliberately larger bump — the
            // shape the props file's own 0.23.0 rationale describes — is
            // never wrong, and a check that insisted on the exact
            // proposal would be forcing the operator's hand.
            let a = assessOne (v (0, 22, 0)) (v (1, 0, 0)) [ change [ alpha ] [ alpha; gamma ] ]
            Expect.equal a.Demanded Patch "additive on 0.x needs only a patch"
            Expect.isTrue (meetsDemand a) "a major far exceeds a patch floor"
            Expect.isNone (defect a) "and produces no defect")

        testCase "a version that does not advance at all fails, whatever the surface did" (fun _ ->
            let a = assessOne (v (0, 22, 0)) (v (0, 22, 0)) [ change [ alpha ] [ alpha ] ]
            Expect.equal a.Advance None "0.22.0 does not advance past 0.22.0"
            Expect.isFalse (meetsDemand a) "re-releasing a version is never legal"

            match defect a with
            | None -> failtest "a non-advance must produce a defect report"
            | Some report -> Expect.stringContains report "does not advance" "the report says which failure this is")

        testCase "a declared version BEHIND the release point does not advance" (fun _ ->
            let a = assessOne (v (0, 22, 0)) (v (0, 21, 9)) [ change [ alpha ] [ alpha ] ]
            Expect.equal a.Advance None "going backwards is not an advance"
            Expect.isFalse (meetsDemand a) "and cannot meet any floor")

        // ── Release-point selection ───────────────────────────────────

        testCase "the release point is the newest tag BELOW the declared version" (fun _ ->
            let tags = [ "v0.20.1"; "v0.21.0"; "v0.9.4"; "v0.22.0" ]

            match releasePoint (v (0, 23, 0)) tags with
            | Some(tag, version) ->
                Expect.equal tag "v0.22.0" "the newest release below the declared version"
                Expect.equal version (v (0, 22, 0)) "parsed from the tag name"
            | None -> failtest "a release point must be found")

        testCase "a tag EQUAL to the declared version is not the release point" (fun _ ->
            // The publish workflow runs on the `v*` tag push, so the tag
            // being released already exists and points at HEAD. Measuring
            // against it would compare the release with itself, find
            // nothing, and then fail the version for not advancing past
            // itself. Excluding it makes the check give the same answer
            // before and after the tag is cut.
            let tags = [ "v0.22.0"; "v0.23.0" ]

            match releasePoint (v (0, 23, 0)) tags with
            | Some(tag, _) -> Expect.equal tag "v0.22.0" "the tag being released is skipped"
            | None -> failtest "a release point must still be found")

        testCase "tag ordering is by version, not by string" (fun _ ->
            // `v0.9.4` sorts after `v0.22.0` lexically. It must not win.
            match releasePoint (v (0, 23, 0)) [ "v0.9.4"; "v0.22.0"; "v0.10.0" ] with
            | Some(tag, _) -> Expect.equal tag "v0.22.0" "0.22.0 is newer than 0.9.4"
            | None -> failtest "a release point must be found")

        testCase "unparseable tags are skipped, not fatal" (fun _ ->
            match releasePoint (v (0, 23, 0)) [ "nightly"; "v0.22.0"; "release-candidate" ] with
            | Some(tag, _) -> Expect.equal tag "v0.22.0" "a non-release tag is not a release"
            | None -> failtest "the parseable tag must still be found")

        testCase "no release point below the declared version is reported, not passed" (fun _ ->
            Expect.isNone (releasePoint (v (0, 1, 0)) [ "v0.22.0" ]) "nothing below 0.1.0"

            let report = noReleasePointReport (v (0, 1, 0)) 1

            Expect.stringContains
                report
                "git fetch --tags"
                "a shallow checkout is the likely cause; the remedy is named"

            Expect.stringContains report "0.1.0" "the declared version is named")

        testCase "a release already AHEAD of the declared version is its own finding" (fun _ ->
            let ahead = releasesAhead (v (0, 22, 0)) [ "v0.21.0"; "v0.23.0"; "v1.0.0" ]
            Expect.equal (ahead |> List.map fst) [ "v0.23.0"; "v1.0.0" ] "both, in version order"

            Expect.stringContains
                (behindReleaseReport (v (0, 22, 0)) ahead)
                "v1.0.0"
                "the report names what is already published"

            Expect.isEmpty (releasesAhead (v (0, 23, 0)) [ "v0.22.0" ]) "nothing ahead of a leading version")

        // ── Version parsing ───────────────────────────────────────────

        testCase "versions parse with or without the tag's v, and past a pre-release suffix" (fun _ ->
            Expect.equal (parseVersion "v0.22.0") (Ok(v (0, 22, 0))) "a tag name"
            Expect.equal (parseVersion "0.22.0") (Ok(v (0, 22, 0))) "a props value"
            Expect.equal (parseVersion " 0.23.0 ") (Ok(v (0, 23, 0))) "surrounding whitespace"
            Expect.equal (parseVersion "0.23.0-rc.1") (Ok(v (0, 23, 0))) "a pre-release makes the same slot promise"
            Expect.equal (parseVersion "0.23.0+build.7") (Ok(v (0, 23, 0))) "build metadata is not a slot")

        testCase "an unreadable version is an error, never a guess" (fun _ ->
            Expect.isError (parseVersion "0.22") "two parts are not a SemVer core"
            Expect.isError (parseVersion "latest") "a moving name has no slots"
            Expect.isError (parseVersion "0.x.0") "a wildcard is not a number"
            Expect.isError (parseVersion "") "nothing at all")

        // ── Reading the declared version ──────────────────────────────

        testCase "a <Version> inside an XML comment is not the declared version" (fun _ ->
            // Directory.Build.props' own prose mentions `<Version>` while
            // explaining per-package overrides. A reader that took the
            // first match would be reporting on documentation.
            let props =
                "<Project>\n  <!-- per-package <Version>9.9.9</Version> overrides live in each fsproj -->\n  <PropertyGroup>\n    <Version>0.23.0</Version>\n  </PropertyGroup>\n</Project>"

            Expect.equal (declaredVersionIn props) (Ok(v (0, 23, 0))) "the live element, not the commented one")

        testCase "two live <Version> declarations are refused" (fun _ ->
            let props =
                "<Project><PropertyGroup><Version>0.23.0</Version><Version>0.24.0</Version></PropertyGroup></Project>"

            Expect.isError (declaredVersionIn props) "the lockstep version must be a single declaration")

        testCase "no <Version> at all is refused" (fun _ ->
            Expect.isError (declaredVersionIn "<Project></Project>") "there is nothing to check against")

        // ── Anti-dormancy: the LIVE props file ────────────────────────

        testCase "the committed Directory.Build.props declares a readable lockstep version" (fun _ ->
            // Without this, every case above could pass over synthetic
            // strings while the real file had drifted into a shape the
            // reader cannot parse — and the first anyone would learn of
            // it is the release the check was written to protect. This is
            // the same anti-vacuity pin `SdkManifestTests` puts on
            // discovery.
            let propsPath = Path.Combine(repoRoot (), "Directory.Build.props")
            Expect.isTrue (File.Exists propsPath) "Directory.Build.props is where the check looks for it"

            match declaredVersionIn (File.ReadAllText propsPath) with
            | Error e -> failtestf "the committed Directory.Build.props declares no readable <Version>: %s" e
            | Ok declared ->
                Expect.isGreaterThan
                    (Version.compare declared (v (0, 0, 0)))
                    0
                    "the declared SDK version is a real version")

        testCase "the api-baselines directory the check diffs is where it looks" (fun _ ->
            // The other half of the same pin: a moved baseline directory
            // would make every package classify as withdrawn — or, via an
            // empty changed-set, as unchanged — rather than fail.
            let dir = baselineDir (repoRoot ())
            Expect.isTrue (Directory.Exists dir) "api-baselines/ exists at the path the check reads"

            Expect.isGreaterThan
                (Directory.GetFiles(dir, "*.approved.txt").Length)
                0
                "and carries approved baselines to diff")

        testCase "a baseline path maps to its package id" (fun _ ->
            Expect.equal
                (packageOfBaselinePath "api-baselines/ToolUp.Graph.Core.approved.txt")
                "ToolUp.Graph.Core"
                "a git-style forward-slashed path"

            Expect.equal
                (packageOfBaselinePath "api-baselines\\ToolUp.Graph.Core.approved.txt")
                "ToolUp.Graph.Core"
                "and a Windows-style one name the same package")

        // ── The report ────────────────────────────────────────────────

        testCase "the proposal is described even when the check passes" (fun _ ->
            // A gate that only speaks when it is angry teaches nobody
            // what it measures, and the operator deciding a number is the
            // reader who most needs the classification.
            let a = assessOne (v (0, 22, 0)) (v (0, 23, 0)) [ change [ alpha; beta ] [ alpha ] ]
            let text = describe a
            Expect.stringContains text "breaking" "the class is stated"
            Expect.stringContains text "minor" "so is the bump it demands"
            Expect.stringContains text "0.x" "and which policy table produced it")

        testCase "a withdrawn package is called out in the failure text" (fun _ ->
            // The one break a version number cannot express: a consumer
            // that raises its pin without dropping the PackageReference
            // fails at RESTORE with NU1101, not at compile.
            let a =
                assessOne (v (0, 22, 0)) (v (0, 22, 1)) [ classifyPackage "Demo" (Some(baseline [ alpha ])) None ]

            match defect a with
            | None -> failtest "a withdrawal under a patch bump must fail"
            | Some report ->
                Expect.stringContains report "withdrawn" "the report says the package stopped being produced")
    ]