module ToolUp.Platform.ShareTokenStore

open System
open System.Security.Cryptography
open System.Text
open System.Text.Json
open System.Threading
open ToolUp.Remoting.Json.SystemTextJson
open ToolUp.Platform
open ToolUp.Platform.BlobStorage
open ToolUp.Platform.Secrets

// ─── Storage layout ──────────────────────────────────────────────────
//
// Container: always `_platform`.
// Token blob:           `share-tokens/{scopeId}/{tokenId}.json`
// Resource index entry: `share-tokens/{scopeId}/_by-resource/{sha256(kind|id)}/{tokenId}.ref`
//
// Mirrors the `_platform/jobs/`, `_platform/webhooks/`, and
// `_platform/audit/` layouts so operators see one consistent shape
// across SDK subsystems. Scope sits in the path prefix so per-scope
// operations are a cheap `List(container, "share-tokens/{scopeId}/...")`
// call and cross-scope leakage is structurally impossible.
//
// Resource-index segment hashes `{kind}|{id}` to bound path length
// and avoid path-incompatible characters in user-supplied
// `resourceKind` / `resourceId` values.

// Public (not `private`) so the Wave 19 share-token-signing-key
// provenance preflight validator can probe the key's presence in the
// same container / secret-name without duplicating the constants
// (single source of truth — no drift).
[<Literal>]
let platformContainer = "_platform"

[<Literal>]
let signingKeySecretName = "share_token_signing_key"

/// Phase 460 — the sidecar secret written beside `share_token_signing_key`
/// whenever THIS SDK auto-generates the key. Its presence is what lets
/// preflight tell an operator-provisioned key apart from an auto-minted
/// one; without it the two are byte-indistinguishable in the store, which
/// is precisely why the auto-generate path was invisible to governance.
[<Literal>]
let signingKeyOriginSecretName = "share_token_signing_key_origin"

/// The only value `signingKeyOriginSecretName` ever holds. A key with no
/// marker beside it is treated as operator-provisioned — the honest
/// reading, since a key minted before Phase 460 shipped carries no marker
/// and cannot be retro-classified.
[<Literal>]
let autoGeneratedOriginMarker = "auto-generated"

/// Phase 460 — where the signing key currently in force came from.
/// Reported on the preflight snapshot so the posture is visible without
/// log archaeology.
type SigningKeyProvenance =
    /// Present in `ISecretStore` with no auto-generation marker beside
    /// it: either genuinely operator-provisioned, or minted before the
    /// marker existed. Backup / rotation governance is presumed.
    | OperatorProvisioned
    /// Present, and minted by this deployment (or a peer replica) rather
    /// than by an operator. Nobody was told to back it up; losing the
    /// secret store silently invalidates every outstanding share link.
    | AutoGenerated
    /// Absent — the next signing-key resolution will mint and persist one.
    | AbsentWillAutoGenerate

/// Read the key's provenance **without resolving it** — this never
/// writes, so preflight can report the posture without itself creating
/// the very key it is warning about.
let probeSigningKeyProvenance (secretStore: ISecretStore) : Async<SigningKeyProvenance> = async {
    let! key = secretStore.GetSecret(platformContainer, signingKeySecretName)

    match key with
    | None -> return AbsentWillAutoGenerate
    | Some _ ->
        let! origin = secretStore.GetSecret(platformContainer, signingKeyOriginSecretName)

        match origin with
        | Some marker when marker = autoGeneratedOriginMarker -> return AutoGenerated
        | _ -> return OperatorProvisioned
}

let private tokenBlob (scopeId: string) (tokenId: string) =
    $"share-tokens/{scopeId}/{tokenId}.json"

let private resourceHash (resourceKind: string) (resourceId: string) =
    use sha = SHA256.Create()
    let key = $"{resourceKind}|{resourceId}"
    let hash = sha.ComputeHash(Encoding.UTF8.GetBytes key)
    Convert.ToHexString(hash).ToLowerInvariant()

let private resourceIndexBlob (scopeId: string) (resourceKind: string) (resourceId: string) (tokenId: string) =
    let h = resourceHash resourceKind resourceId
    $"share-tokens/{scopeId}/_by-resource/{h}/{tokenId}.ref"

let private resourceIndexPrefix (scopeId: string) (resourceKind: string) (resourceId: string) =
    let h = resourceHash resourceKind resourceId
    $"share-tokens/{scopeId}/_by-resource/{h}/"

let private tokensPrefix (scopeId: string) = $"share-tokens/{scopeId}/"

// ─── JSON ────────────────────────────────────────────────────────────

module private Json =
    let private options = FableConverters.create ()

    let serialize (value: 'T) : byte[] =
        JsonSerializer.Serialize(value, options) |> Encoding.UTF8.GetBytes

    let serializeString (value: 'T) : string =
        JsonSerializer.Serialize(value, options)

    let tryDeserialize<'T> (bytes: byte[]) : 'T option =
        try
            let json = Encoding.UTF8.GetString bytes
            Some(JsonSerializer.Deserialize<'T>(json, options))
        with _ ->
            None

// ─── Base64url + HMAC helpers ─────────────────────────────────────────
//
// The base64url codec, HMAC and the (formerly hand-rolled XOR)
// constant-time compare are the shared SDK primitives in
// `ToolUp.Platform.Base64Url` / `ToolUp.Platform.JwtCrypto` — the local
// copies (incl. the one piece of unaudited hand-rolled crypto in the
// set) are gone in favour of the BCL `CryptographicOperations`-backed
// `JwtCrypto.fixedTimeEquals`.

// ─── Wire format ─────────────────────────────────────────────────────
//
// `{tokenId}.{base64url(payloadJson)}.{base64url(hmac)}`
//
// `tokenId` is the storage-key for the persisted claim. The signed
// `payload` carries (TokenId, ScopeId, ResourceKind, ResourceId) so
// a swapped tokenId fails verification and a swapped scope or
// resource is detected without trusting the embedded values — the
// persisted record stays the source of truth.

/// Public so the STJ FableConverters record converter can read
/// the synthesised public constructor and round-trip the fields.
/// A `private` F# record hides the constructor from the converter,
/// which silently produces `{}` and breaks the Validate path. Same
/// gotcha as
/// `JobStore.IdempotencyEntry`.
type SignedPayload = {
    TokenId: string
    ScopeId: string
    ResourceKind: string
    ResourceId: string
}

let private encodeToken (signingKey: byte[]) (claim: ShareTokenClaim) : string =
    let payload = {
        TokenId = claim.TokenId
        ScopeId = claim.ScopeId
        ResourceKind = claim.ResourceKind
        ResourceId = claim.ResourceId
    }

    let payloadJson = Json.serializeString payload
    let payloadBytes = Encoding.UTF8.GetBytes payloadJson
    let signature = JwtCrypto.computeHmac signingKey payloadBytes
    sprintf "%s.%s.%s" claim.TokenId (Base64Url.encode payloadBytes) (Base64Url.encode signature)

/// Returns the verified `tokenId` plus the parsed `SignedPayload` on
/// success, so callers can cross-check the embedded scope/resource
/// against the persisted claim.
let private parseToken (signingKey: byte[]) (token: string) : Result<string * SignedPayload, ShareTokenError> =
    let parts = token.Split('.')

    if parts.Length <> 3 then
        Error ShareTokenError.Malformed
    else
        let tokenIdFromPrefix = parts[0]

        match Base64Url.tryDecode parts[1], Base64Url.tryDecode parts[2] with
        | Some payloadBytes, Some signatureBytes ->
            let expected = JwtCrypto.computeHmac signingKey payloadBytes

            if not (JwtCrypto.fixedTimeEquals expected signatureBytes) then
                Error ShareTokenError.InvalidSignature
            else
                match Json.tryDeserialize<SignedPayload> payloadBytes with
                | Some payload when payload.TokenId = tokenIdFromPrefix -> Ok(tokenIdFromPrefix, payload)
                | Some _ -> Error ShareTokenError.InvalidSignature
                | None -> Error ShareTokenError.Malformed
        | _ -> Error ShareTokenError.Malformed

// ─── Signing-key resolution ──────────────────────────────────────────
//
// 32-byte HMAC key persisted in `ISecretStore` under the reserved
// `_platform` scope. The key is an OPERATOR-MANAGED SECRET: Phase 460
// promoted `ShareTokenSigningKeyProvenanceValidator` to refuse startup
// in a production-shaped deployment (public base URL, or declared
// replicas) whose key is unprovisioned, unless the operator explicitly
// accepts an ephemeral one. Rotation is the secret store's normal
// Set/Delete flow — every process picks up the new key within the cache
// TTL below, no restart required; all previously-issued tokens then fail
// verification, which is the documented and intended consequence.
//
// The auto-generate path survives for the acknowledged case (dev, CI,
// single-instance), and Phase 460 makes it safe to run under several
// replicas rather than merely likely to work:
//
//   * **Serialised within the process.** One `SemaphoreSlim` gates
//     generation, and the store is re-read INSIDE the gate. Without it,
//     N concurrent first calls in one process each mint a key and each
//     overwrite the last — the process would sign with one key and
//     verify against another, depending on which task cached first.
//   * **Read-back adoption across processes.** After persisting, the
//     key is re-read and whatever the STORE holds is what gets returned.
//     If a peer replica won the write, this replica adopts the peer's
//     key instead of caching a value the store no longer has. The
//     invariant that buys: a replica never signs with a key the secret
//     store does not hold, so a token minted by one replica verifies on
//     every other.
//
// It is deliberately NOT presented as a compare-and-set: `ISecretStore`
// exposes `GetSecret` / `SetSecret` with no conditional write, so a
// genuine CAS is not expressible over the interface. What is closed is
// the divergence window — narrowed from "the whole boot" to one store
// round-trip, with convergence guaranteed by the read-back and, failing
// that, by the TTL refresh below. The complete fix remains
// pre-provisioning, which is what the validator now insists on.

/// Serialises signing-key GENERATION within this process. Not a
/// cross-process lock — see the read-back adoption above for the
/// multi-replica half.
let private signingKeyGenerationGate = new SemaphoreSlim(1, 1)

let private decodeSigningKey (encoded: string) : Result<byte[], string> =
    match Base64Url.tryDecode encoded with
    | Some bytes when bytes.Length >= 32 -> Ok bytes
    | _ -> Error "share_token_signing_key is malformed (expected base64url-encoded 32+ bytes)"

let private resolveSigningKey (secretStore: ISecretStore) (logger: ILogger) : Async<Result<byte[], string>> = async {
    let! existing = secretStore.GetSecret(platformContainer, signingKeySecretName)

    match existing with
    | Some s -> return decodeSigningKey s
    | None ->
        do! signingKeyGenerationGate.WaitAsync() |> Async.AwaitTask

        try
            // Re-read inside the gate: a sibling task may have generated
            // and persisted while this one waited.
            let! recheck = secretStore.GetSecret(platformContainer, signingKeySecretName)

            match recheck with
            | Some s -> return decodeSigningKey s
            | None ->
                let key = Array.zeroCreate<byte> 32
                use rng = RandomNumberGenerator.Create()
                rng.GetBytes(key)
                let encoded = Base64Url.encode key
                let! saveResult = secretStore.SetSecret(platformContainer, signingKeySecretName, encoded)

                match saveResult with
                | Error e -> return Error(sprintf "couldn't persist share_token_signing_key: %s" e)
                | Ok() ->
                    // Mark the key as auto-generated so preflight can tell
                    // it apart from an operator-provisioned one. A failure
                    // here costs visibility, never correctness — the key
                    // itself is already durable, so do not fail the resolve.
                    let! markerResult =
                        secretStore.SetSecret(platformContainer, signingKeyOriginSecretName, autoGeneratedOriginMarker)

                    match markerResult with
                    | Ok() -> ()
                    | Error e ->
                        logger.Warn
                            $"share-token signing key was auto-generated but its provenance marker could not be persisted; preflight will report the key as operator-provisioned: {e}"

                    // Adopt whatever the store now holds. Under concurrent
                    // replicas the last writer wins the slot, and every
                    // replica must sign with the winner — not with the
                    // value it happened to mint locally.
                    let! readBack = secretStore.GetSecret(platformContainer, signingKeySecretName)

                    match readBack with
                    | Some stored when stored <> encoded ->
                        logger.Warn
                            "share-token signing key: a peer replica persisted a different key concurrently; adopting the stored value so tokens verify across replicas. Pre-provision share_token_signing_key to avoid the race entirely."

                        return decodeSigningKey stored
                    | Some stored -> return decodeSigningKey stored
                    | None ->
                        // The key was written and immediately read back as
                        // absent: a store with weak read-after-write, or a
                        // concurrent delete. Serving the local value would
                        // sign tokens no sibling can verify.
                        return
                            Error
                                "share_token_signing_key was persisted but read back as absent — the ISecretStore is not providing read-after-write consistency"
        finally
            signingKeyGenerationGate.Release() |> ignore
}

// ─── BlobShareTokenStore ─────────────────────────────────────────────

/// Default `IShareTokenStore` impl. Persists claims under
/// `_platform/share-tokens/{scopeId}/...` and HMAC-signs token strings
/// against a key resolved from `ISecretStore`. Audit emission is
/// optional — pass `None` for the `audit` constructor parameter when
/// the deployment runs `AuditLog = NoAuditLog`.
type BlobShareTokenStore(storage: IBlobStorage, secretStore: ISecretStore, audit: IAuditLog option, logger: ILogger) =

    let lockObj = obj ()

    // Phase 116 — serialise the claim read-modify-write paths
    // (`MarkUsed`, `Revoke`) within this process. Without it, N concurrent
    // `MarkUsed` calls all read `UsedCount = k` and all write `k + 1`, so a
    // `UseLimit = 1` token admits every concurrent submitter. This is the
    // *interim single-instance* guard: it holds the use-count invariant on
    // one node but NOT across replicas (two processes each hold their own
    // semaphore). The multi-replica fix is ETag-conditional-write CAS on
    // `IBlobStorage.UploadWithETag` (Phase 9c half-2), deferred — see the
    // Phase 116 ETag-gated tasks. A non-reentrant `SemaphoreSlim`: no
    // locked path calls another locked path.
    let claimWriteLock = new SemaphoreSlim(1, 1)

    // Cached signing key — resolved lazily on first use, then re-read
    // from `ISecretStore` once the TTL lapses. ISecretStore reads are
    // cheap but not free; one read per token operation would be
    // wasteful — but a process-lifetime memo (the pre-hardening shape,
    // Gap audit 2026-06-12 Auth G7) meant key rotation needed a
    // full-fleet restart and staggered restarts yielded split-brain
    // `InvalidSignature` indefinitely. Mirrors the OIDC JWKS cache:
    // 10-minute TTL + stale-fallback when the refresh fetch fails
    // (prefer the stale key over failing during a brief secret-store
    // outage). Contrast `PeerBearerAuthMiddleware`, which deliberately
    // re-reads per call.
    let signingKeyTtl = TimeSpan.FromMinutes 10.0
    let mutable signingKeyCache: (byte[] * DateTime) option = None

    let getSigningKey () = async {
        let now = DateTime.UtcNow

        match signingKeyCache with
        | Some(k, fetchedAt) when now - fetchedAt < signingKeyTtl -> return Ok k
        | stale ->
            let! resolved = resolveSigningKey secretStore logger

            match resolved with
            | Ok k ->
                lock lockObj (fun () -> signingKeyCache <- Some(k, now))
                return Ok k
            | Error e ->
                match stale with
                | Some(k, _) ->
                    logger.Warn $"share-token signing-key refresh failed; serving with the stale cached key: {e}"
                    return Ok k
                | None -> return Error(ShareTokenError.StorageFailed e)
    }

    let writeClaim (claim: ShareTokenClaim) = async {
        let bytes = Json.serialize claim
        let! result = storage.Upload(platformContainer, tokenBlob claim.ScopeId claim.TokenId, bytes)

        match result with
        | Ok _ -> return Ok()
        | Error e -> return Error(ShareTokenError.StorageFailed e)
    }

    let writeResourceIndex (claim: ShareTokenClaim) = async {
        let blob =
            resourceIndexBlob claim.ScopeId claim.ResourceKind claim.ResourceId claim.TokenId

        let! result = storage.Upload(platformContainer, blob, [||])

        match result with
        | Ok _ -> return Ok()
        | Error e -> return Error(ShareTokenError.StorageFailed e)
    }

    // Phase 116 audit (fail-closed decode): this read already fails
    // closed — a present-but-unparseable claim blob returns
    // `StorageFailed`, never a default/empty claim. Every mutating path
    // (`MarkUsed`, `Revoke`) routes through `readClaim` and short-circuits
    // on that `Error` before any `writeClaim`, so a corrupt claim is never
    // overwritten with a record derived from a failed decode. No change
    // needed here; unlike the pending-invites store, claims are
    // one-blob-per-token (not a single full-blob-overwrite map), so a
    // corrupt blob can only break its own token, not erase its siblings.
    //
    // A failed `Download` is NOT evidence of absence. `IBlobStorage`
    // reports it as `Error of string` — `LocalFileStorage` returns
    // "Blob not found: …" for a missing blob and `ex.Message` for a
    // caught exception, and both are just strings — so a transient IO
    // error, a permissions problem or a misconfigured container all
    // used to collapse into `NotFound` here, pointing the caller at the
    // wrong subsystem. `MarkUsed` and `Revoke` both route through this
    // read and short-circuit on its `Error`, so a storage fault reached
    // an operator as "no such token".
    //
    // `Exists` disambiguates, probed only on the error path so the
    // happy path pays nothing. The disambiguation is deliberately
    // ONE-SIDED, and that asymmetry is exactly what it buys:
    //
    //   Exists = true  → the blob is there and we could not read it.
    //                    Positively a storage failure.
    //   Exists = false → absent, OR a fault that took `Exists` down
    //                    with it. The signature has no error channel
    //                    (`Async<bool>`) and every cloud implementation
    //                    ends it `with _ -> return false`, so a
    //                    container-wide permissions or configuration
    //                    failure still reads as `NotFound`.
    //
    // So this closes "the blob is there, the read failed" and NOT the
    // container-wide cases. Closing those needs absence and failure to
    // be distinguishable one layer down — a typed blob-read error. That
    // is not a local change: `Download` sits on the api-baseline with
    // thirteen in-tree implementers plus consumer-side custom stores,
    // and the ETag (Phase 600) and signed-URL (Phase 108) seams in
    // `IBlobStorage.fs` both record why such a widening goes behind a
    // probed capability interface rather than into the contract every
    // backend must answer.
    //
    // No existence oracle is opened: `Validate` runs `parseToken` — a
    // full HMAC check — before it reaches this read, so a caller can
    // only tell `StorageFailed` from `NotFound` for a token they could
    // already validly sign.
    let readClaim (scopeId: string) (tokenId: string) = async {
        let blob = tokenBlob scopeId tokenId
        let! result = storage.Download(platformContainer, blob)

        match result with
        | Ok bytes ->
            match Json.tryDeserialize<ShareTokenClaim> bytes with
            | Some claim -> return Ok claim
            | None -> return Error(ShareTokenError.StorageFailed "share-token blob deserialisation failed")
        | Error downloadError ->
            let! present = storage.Exists(platformContainer, blob)

            if present then
                return Error(ShareTokenError.StorageFailed downloadError)
            else
                return Error ShareTokenError.NotFound
    }

    let recordAudit (scopeId: string) (event: AuditEvent) =
        match audit with
        | Some a ->
            // Fire-and-forget; audit failure must never block the
            // primary operation. `IAuditLog.Record` itself logs at
            // Warn on internal errors.
            Async.Start(a.Record(scopeId, event))
        | None -> ()

    interface IShareTokenStore with
        member _.Issue(request) = async {
            // Phase 21e — reject malformed rate-limit at issue-time
            // rather than first-use so operators see the failure in
            // the issue flow rather than the first respondent's
            // request.
            match ShareTokenTypes.validateRateLimit request.RateLimit with
            | Error msg -> return Error(ShareTokenError.StorageFailed msg)
            | Ok() ->

                let! signingKey = getSigningKey ()

                match signingKey with
                | Error err -> return Error err
                | Ok key ->
                    let now = DateTimeOffset.UtcNow

                    let useLimit =
                        match request.UseLimit with
                        | None -> ShareTokenTypes.DefaultUseLimit
                        | Some explicit -> explicit

                    let expiresAt =
                        match request.ExpiresAt with
                        | Some at -> at
                        | None -> now + ShareTokenTypes.DefaultLifetime

                    let tokenId =
                        let bytes = Array.zeroCreate<byte> 16
                        use rng = RandomNumberGenerator.Create()
                        rng.GetBytes(bytes)
                        Base64Url.encode bytes

                    let claim = {
                        TokenId = tokenId
                        ScopeId = request.ScopeId
                        ResourceKind = request.ResourceKind
                        ResourceId = request.ResourceId
                        AttributedHandle = request.AttributedHandle
                        IssuedBy = request.IssuedBy
                        IssuedAt = now
                        ExpiresAt = expiresAt
                        UseLimit = useLimit
                        UsedCount = 0
                        Revoked = false
                        RateLimit = request.RateLimit
                    }

                    match! writeClaim claim with
                    | Error e -> return Error e
                    | Ok() ->
                        match! writeResourceIndex claim with
                        | Error e -> return Error e
                        | Ok() ->
                            let tokenString = encodeToken key claim

                            recordAudit
                                request.ScopeId
                                (AuditEvent.ShareTokenIssued {
                                    UserId = request.IssuedBy
                                    TokenId = tokenId
                                    ResourceKind = request.ResourceKind
                                    ResourceId = request.ResourceId
                                    AttributedHandle = request.AttributedHandle
                                    ExpiresAt = expiresAt
                                })

                            return Ok { Token = tokenString; Claim = claim }
        }

        member _.Validate(token) = async {
            let! signingKey = getSigningKey ()

            match signingKey with
            | Error err -> return Error err
            | Ok key ->
                match parseToken key token with
                | Error err -> return Error err
                | Ok(_, payload) ->
                    let! claimResult = readClaim payload.ScopeId payload.TokenId

                    match claimResult with
                    | Error err -> return Error err
                    | Ok claim ->
                        // Cross-check the signed payload against the
                        // persisted record. A mismatch means someone
                        // tried to splice a different scope / resource
                        // into a valid signature — reject as if the
                        // signature itself was bad.
                        if
                            claim.ScopeId <> payload.ScopeId
                            || claim.ResourceKind <> payload.ResourceKind
                            || claim.ResourceId <> payload.ResourceId
                        then
                            return Error ShareTokenError.InvalidSignature
                        elif claim.Revoked then
                            return Error ShareTokenError.RevokedToken
                        elif claim.ExpiresAt <= DateTimeOffset.UtcNow then
                            return Error ShareTokenError.Expired
                        else
                            match claim.UseLimit with
                            | Some limit when claim.UsedCount >= limit -> return Error ShareTokenError.UseLimitExceeded
                            | _ -> return Ok claim
        }

        member _.MarkUsed(scopeId, tokenId) = async {
            // Serialise the read → increment → write so concurrent uses of
            // a `UseLimit = N` token cannot all observe the same `UsedCount`
            // and each write `count + 1` (Phase 116). Interim single-
            // instance guard; multi-replica needs ETag CAS (deferred).
            do! claimWriteLock.WaitAsync() |> Async.AwaitTask

            try
                let! claimResult = readClaim scopeId tokenId

                match claimResult with
                | Error err -> return Error err
                | Ok claim ->
                    if claim.Revoked then
                        return Error ShareTokenError.RevokedToken
                    else
                        match claim.UseLimit with
                        | Some limit when claim.UsedCount >= limit -> return Error ShareTokenError.UseLimitExceeded
                        | _ ->
                            let updated = {
                                claim with
                                    UsedCount = claim.UsedCount + 1
                            }

                            match! writeClaim updated with
                            | Error e -> return Error e
                            | Ok() ->
                                recordAudit
                                    scopeId
                                    (AuditEvent.ShareTokenUsed {
                                        TokenId = tokenId
                                        ResourceKind = claim.ResourceKind
                                        ResourceId = claim.ResourceId
                                        AttributedHandle = claim.AttributedHandle
                                    })

                                return Ok()
            finally
                claimWriteLock.Release() |> ignore
        }

        member _.Revoke(scopeId, tokenId, actorUserId) = async {
            // Same RMW serialisation as `MarkUsed` — a revoke racing a use
            // must not be lost to a stale-read overwrite (Phase 116).
            do! claimWriteLock.WaitAsync() |> Async.AwaitTask

            try
                let! claimResult = readClaim scopeId tokenId

                match claimResult with
                | Error ShareTokenError.NotFound -> return Error ShareTokenError.NotFound
                | Error err -> return Error err
                | Ok claim when claim.Revoked ->
                    // Idempotent — already revoked, no audit re-emission.
                    return Ok()
                | Ok claim ->
                    let updated = { claim with Revoked = true }

                    match! writeClaim updated with
                    | Error e -> return Error e
                    | Ok() ->
                        recordAudit
                            scopeId
                            (AuditEvent.ShareTokenRevoked {
                                UserId = actorUserId
                                TokenId = tokenId
                                ResourceKind = claim.ResourceKind
                                ResourceId = claim.ResourceId
                            })

                        return Ok()
            finally
                claimWriteLock.Release() |> ignore
        }

        member _.ListByResource(scopeId, resourceKind, resourceId) = async {
            let prefix = resourceIndexPrefix scopeId resourceKind resourceId
            let! refs = storage.List(platformContainer, prefix)

            let tokenIds =
                refs
                |> List.choose (fun blobName ->
                    // LocalFileStorage on Windows returns paths with `\`;
                    // cloud impls use `/`. Normalise before prefix-match
                    // (mirrors `DataObjectStore.normalize`).
                    let normalised = blobName.Replace('\\', '/')

                    if normalised.StartsWith prefix && normalised.EndsWith ".ref" then
                        let trimmed = normalised.Substring(prefix.Length)
                        Some(trimmed.Substring(0, trimmed.Length - 4))
                    else
                        None)

            let! claims =
                tokenIds
                |> List.map (fun tid -> async {
                    let! r = readClaim scopeId tid

                    return
                        match r with
                        | Ok claim -> Some claim
                        | Error _ ->
                            // A dangling index entry is recoverable noise — log
                            // and skip rather than fail the entire listing.
                            logger.Warn $"share-token index entry without claim: scope=%s{scopeId} token=%s{tid}"
                            None
                })
                |> Async.Parallel

            return claims |> Array.choose id |> Array.toList |> List.sortByDescending _.IssuedAt
        }

        member _.ListByIssuer(scopeId, issuerUserId) = async {
            // No per-issuer index blob exists (unlike `_by-resource/`).
            // Scan the scope's token blobs directly and filter on
            // `IssuedBy` in memory — the membership-change cadence this
            // serves (a leaver's claims, enumerated once on removal)
            // does not warrant a second index to keep in sync on every
            // issue. The prefix `share-tokens/{scopeId}/` also covers
            // the `_by-resource/` index subtree, so direct token blobs
            // are isolated by requiring a `.json` extension AND no `/`
            // in the path segment after the prefix.
            let prefix = tokensPrefix scopeId
            let! blobs = storage.List(platformContainer, prefix)

            let tokenIds =
                blobs
                |> List.choose (fun blobName ->
                    let normalised = blobName.Replace('\\', '/')

                    if normalised.StartsWith prefix && normalised.EndsWith ".json" then
                        let trimmed = normalised.Substring(prefix.Length)

                        // A `/` here means the blob lives under a
                        // sub-prefix (`_by-resource/`), not a top-level
                        // token blob — skip it.
                        if trimmed.Contains '/' then
                            None
                        else
                            Some(trimmed.Substring(0, trimmed.Length - 5))
                    else
                        None)

            let! claims =
                tokenIds
                |> List.map (fun tid -> async {
                    let! r = readClaim scopeId tid

                    return
                        match r with
                        | Ok claim -> Some claim
                        | Error _ ->
                            logger.Warn
                                $"share-token blob unreadable during ListByIssuer: scope=%s{scopeId} token=%s{tid}"

                            None
                })
                |> Async.Parallel

            return
                claims
                |> Array.choose id
                |> Array.filter (fun c -> c.IssuedBy = issuerUserId)
                |> Array.toList
                |> List.sortByDescending _.IssuedAt
        }

/// Convenience constructor mirroring `JobStore.BlobJobStore` /
/// `EntityStore.BlobEntityStore` — keeps the wiring in `compose`
/// terse.
let create
    (storage: IBlobStorage)
    (secretStore: ISecretStore)
    (audit: IAuditLog option)
    (logger: ILogger)
    : IShareTokenStore =
    BlobShareTokenStore(storage, secretStore, audit, logger) :> IShareTokenStore