// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

/// `ISparseAnalyzer` for non-space-delimited scripts — Chinese, Japanese,
/// Korean — by **character n-gram segmentation**.
///
/// **The problem.** The default analyzer splits on Unicode letter/digit runs,
/// and a Chinese or Japanese sentence contains no spaces, so the whole clause
/// arrives as ONE term. A document indexed that way is reachable only by a
/// query that reproduces the clause verbatim; BM25 over such an index is not
/// degraded, it is inert. This is not a ranking problem, it is a tokenisation
/// problem, and no amount of dense retrieval on the other leg makes the
/// lexical leg work.
///
/// **The approach, and its honest posture.** Overlapping character n-grams
/// (bigrams by default) are the dictionary-free segmentation: 東京都 indexes as
/// 東京 / 京都, and a query for 東京 matches. It needs no dictionary, no model,
/// no native binary, and no per-language configuration, and it degrades
/// gracefully on mixed-script text (Latin runs keep word tokenisation).
///
/// What it costs, stated plainly because the alternative is discovering it in
/// production:
///
/// - **Index size.** An n-gram index holds roughly one posting per character
///   rather than one per word — expect the sparse index to grow by a factor of
///   2–3 on CJK-heavy corpora.
/// - **Precision.** Bigrams cross word boundaries, so 京都 is generated by the
///   *phrase* 東京都 even though the city 京都 is not mentioned. BM25's IDF
///   absorbs much of this and RRF fusion with the dense leg absorbs more, but
///   a bigram index does return matches a word segmenter would not.
///
/// **Dev vs production.** This analyzer is production-*viable* — it is
/// deterministic, stateless, allocation-light, and it is what several
/// well-known search engines fall back to when no segmenter is installed. It
/// is not, however, *best*: a dictionary or model-based segmenter (MeCab /
/// Kuromoji for Japanese, jieba for Chinese) produces word tokens, a smaller
/// index and better precision. Those carry a dictionary file or a native
/// binary, which is a different companion with a different supply-chain
/// posture — deliberately out of scope here. Choose this one when you want CJK
/// retrieval to work today with no operational surface; reach for a segmenter
/// companion when CJK is the primary corpus language and precision matters
/// more than deployment simplicity.
module ToolUp.SparseIndices.Cjk.CjkAnalyzer

open System
open System.Text
open ToolUp.RAG.SparseAnalysis

/// Is this character part of a CJK script — i.e. one that does not delimit
/// words with spaces? Covers the CJK Unified Ideographs blocks (including
/// Extension A and the compatibility block), Hiragana, Katakana and Hangul.
/// Latin, Cyrillic, Greek, digits and punctuation are all excluded and fall
/// through to ordinary word tokenisation.
let isCjk (c: char) =
    let code = int c

    (code >= 0x3040 && code <= 0x30FF) // Hiragana + Katakana
    || (code >= 0x3400 && code <= 0x4DBF) // CJK Unified Ideographs Extension A
    || (code >= 0x4E00 && code <= 0x9FFF) // CJK Unified Ideographs
    || (code >= 0xF900 && code <= 0xFAFF) // CJK Compatibility Ideographs
    || (code >= 0xAC00 && code <= 0xD7AF) // Hangul Syllables
    || (code >= 0x1100 && code <= 0x11FF) // Hangul Jamo

/// Analyzer configuration. Both fields participate in the analyzer id, so a
/// change invalidates a persisted index snapshot and forces re-analysis rather
/// than mixing a bigram vocabulary with a trigram one.
type CjkOptions = {
    /// n-gram width over CJK runs. 2 (bigrams) is the standard choice: 1
    /// indexes single characters, which for Chinese is close to indexing
    /// individual letters, and 3+ misses two-character words, which are most
    /// of them.
    NGramSize: int
    /// Also emit each CJK run's single characters alongside the n-grams.
    /// Buys recall for one-character queries (a surname, a single-kanji noun)
    /// at the cost of a longer posting list per character. Off by default.
    IncludeUnigrams: bool
}

module CjkOptions =
    /// Overlapping bigrams, no unigrams — the standard dictionary-free
    /// configuration.
    let bigrams = {
        NGramSize = 2
        IncludeUnigrams = false
    }

/// Split `text` into maximal runs, tagged with whether the run is CJK.
let private runs (text: string) =
    let result = ResizeArray<bool * string>()
    let sb = StringBuilder()
    let mutable currentIsCjk = false

    let flush () =
        if sb.Length > 0 then
            result.Add(currentIsCjk, sb.ToString())
            sb.Clear() |> ignore

    for c in text do
        let cjk = isCjk c

        if sb.Length > 0 && cjk <> currentIsCjk then
            flush ()

        currentIsCjk <- cjk
        sb.Append c |> ignore

    flush ()
    List.ofSeq result

let private nGrams (size: int) (includeUnigrams: bool) (run: string) = [
    if includeUnigrams || run.Length < size then
        for i in 0 .. run.Length - 1 do
            string run[i]

    if run.Length >= size then
        for i in 0 .. run.Length - size do
            run.Substring(i, size)
]

/// The analyzer id — readable, and carrying the configuration, because it is
/// what the persisted snapshot records and what the index prints when it
/// re-analyses a corpus.
let idFor (options: CjkOptions) =
    sprintf "cjk+ngram%d%s" options.NGramSize (if options.IncludeUnigrams then "+uni" else "")

/// Raised when the requested configuration cannot be served.
exception CjkAnalyzerConfigurationException of message: string

/// Build the analyzer. A CJK run is n-grammed; every non-CJK run falls through
/// to the default word tokenisation, so mixed-script text ("Windows 11 の
/// 設定") indexes sensibly on both sides without a second analyzer.
let create (options: CjkOptions) : ISparseAnalyzer =
    if options.NGramSize < 1 then
        raise (CjkAnalyzerConfigurationException(sprintf "NGramSize must be at least 1 (got %d)." options.NGramSize))

    let analyzerId = idFor options

    { new ISparseAnalyzer with
        member _.Id = analyzerId

        member _.Analyse text =
            if String.IsNullOrEmpty text then
                []
            else
                runs text
                |> List.collect (fun (cjk, run) ->
                    if cjk then
                        nGrams options.NGramSize options.IncludeUnigrams run
                    else
                        // Non-CJK runs keep the shipped word rule verbatim —
                        // one definition of a word boundary across the estate.
                        tokeniseWords run)
    }

/// `create CjkOptions.bigrams` — the common case.
let bigrams () : ISparseAnalyzer = create CjkOptions.bigrams