// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

namespace ToolUp.Remoting.Generator

open System
open System.Text

// =============================================================================
// Phase 69k — rendering a plan as F# source
// =============================================================================
//
// The emitter renders and decides NOTHING. Every choice about which combinator
// decodes what, in which order, and what is refused, was made in `Plan`; this
// file turns that record into text. Keeping the split sharp is what lets the
// fidelity test (Phase 69k.I) assert against the PLAN — a structural claim
// about decoder expressions per field — rather than against formatted source,
// which would make the test a whitespace pin.
//
// The emitted module is deliberately the same shape as the hand-written
// `PlatformDecoders` (Phase 785): named decoders in dependency order, then
// `covered`, then `registerAll`, then `coveredApiRecords`. A reader who has
// read one has read the other, and the facet consumes both through the same
// `RemotingDecoderFacet.inspect`.

/// What to emit, beyond the plan itself.
type EmitOptions = {
    /// The namespace the module is declared in. `ToolUp.Remoting` puts the
    /// module beside `RemotingDecoders` and `Decode`, which is where a
    /// registration module belongs.
    Namespace: string
    /// The module's name.
    ModuleName: string
    /// `open` lines beyond `System`, in the order they should appear.
    Opens: string list
    /// One entry per API record the emitted `registerAll` covers:
    /// the record's name, the F# SOURCE SPELLING of every wire type it
    /// carries, and whether the wire corpus draws those shapes.
    ///
    /// Spellings rather than `Type.FullName` strings, because the facet
    /// compares against `RemotingDecoders.registered ()`, which is keyed by
    /// `FullName` — and a generic type's `FullName` embeds the assembly
    /// VERSION of every type argument. Emitting those as literals would
    /// bake `Version=0.23.0.0` into generated source and silently stop
    /// matching at the next version bump; emitting `typeof<…>.FullName`
    /// computes the same string at runtime and cannot go stale.
    ///
    /// The corpus flag is a DECLARATION the caller makes, never something
    /// the generator infers — `false` is the honest default, and the facet
    /// renders `Observed` rather than `Verified` for it.
    ApiRecords: (string * string list * bool) list
}

[<RequireQualifiedAccess>]
module Emit =

    let private header (options: EmitOptions) =
        [
            "// SPDX-License-Identifier: Apache-2.0"
            "// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)"
            "//"
            "// <auto-generated>"
            "//   Phase 69k — emitted by ToolUp.Remoting.Generator from the SAME"
            "//   record/union metadata `Write.writeRecord` and `Write.writeUnion`"
            "//   enumerate, so field positions and union tags are the writer's own"
            "//   ordering rather than a second derivation of it."
            "//"
            "//   DO NOT EDIT. Re-run the generator; a contract test in"
            "//   ToolUp.Platform.Tests holds this file to what the generator emits."
            "// </auto-generated>"
            ""
            sprintf "namespace %s" options.Namespace
            ""
            "open System"
            // Phase 804 — the algebra's home, opened explicitly. The default
            // namespace IS `ToolUp.Remoting`, where `Decode`, `Decoder` and
            // `RemotingDecoders` resolve unqualified; a consumer emitting into
            // its own namespace (samples/HelloWorld-AOT was the first) found
            // none of them without this line.
            "open ToolUp.Remoting"
        ]
        @ (options.Opens |> List.map (sprintf "open %s"))
        @ [
            ""
            "/// Generated algebra decoders: one per wire type the covered API records"
            "/// carry, registered by `registerAll` (or, verified against the reflection"
            "/// reader first, by `registerAllVerified`). Emitted by ToolUp.Remoting.Generator;"
            "/// do not edit."
            "[<RequireQualifiedAccess>]"
            sprintf "module %s =" options.ModuleName
            ""
        ]

    /// A record decoder: an applicative chain over the construction lambda.
    let private recordBody (keyword: string) (binding: string) (typeSpelling: string) (fields: FieldPlan list) =
        let parameters =
            fields
            |> List.map (fun f -> Plan.parameterName f.FieldName)
            |> String.concat " "

        // Phase 804 — the construction is ANNOTATED with the record's own
        // spelling. A type declared inside a module (`WireCorpus.Address`)
        // has labels that are not in scope unless that module is opened,
        // and the lambda handed to `Decode.succeed` is checked before the
        // binding's annotation can reach it; an annotation on the record
        // expression itself resolves the labels type-directed. Measured
        // against the alternatives: a module-qualified first label leaves
        // the remaining labels unresolved, and a `Module.Type.Label` path is
        // an invalid field label outright. Harmless where the labels were
        // already in scope, the only case the hand-written decoders met.
        let assignments =
            fields
            |> List.map (fun f -> sprintf "            %s = %s" f.FieldName (Plan.parameterName f.FieldName))
            |> String.concat "\n"

        let applies =
            fields
            |> List.map (fun f ->
                let d =
                    if f.Decoder.Contains " " then
                        "(" + f.Decoder + ")"
                    else
                        f.Decoder

                sprintf "        |> Decode.apply (Decode.field \"%s\" %d %s)" f.FieldName f.Position d)
            |> String.concat "\n"

        [
            sprintf "    %s %s: Decoder<%s> =" keyword binding typeSpelling
            sprintf "        Decode.succeed (fun %s -> ({" parameters
            assignments
            sprintf "        }: %s))" typeSpelling
            applies
            ""
        ]

    /// A union decoder: a total tag match, with an unrecognised tag
    /// refusing rather than falling through.
    let private unionBody (keyword: string) (binding: string) (typeSpelling: string) (cases: UnionCasePlan list) =
        let arms =
            cases
            |> List.collect (fun c ->
                match c.Payload with
                | CasePayload.NoFields -> [
                    sprintf "            | %d -> Some(Decode.case0 %s.%s)" c.Tag typeSpelling c.CaseName
                  ]
                | CasePayload.OneField payload ->
                    let d =
                        if payload.Contains " " then
                            "(" + payload + ")"
                        else
                            payload

                    [
                        sprintf
                            "            | %d -> Some(Decode.payload (%s |> Decode.map %s.%s))"
                            c.Tag
                            d
                            typeSpelling
                            c.CaseName
                    ]
                | CasePayload.SeveralFields fields ->
                    // Phase 800 — `fields n` over the record-shaped pipeline
                    // the case's inner array is: `succeed` the case
                    // constructor, one `field` per declared field, in order.
                    let parameters =
                        fields
                        |> List.map (fun f -> Plan.parameterName f.FieldName)
                        |> String.concat " "

                    let arguments =
                        fields
                        |> List.map (fun f -> Plan.parameterName f.FieldName)
                        |> String.concat ", "

                    let applies =
                        fields
                        |> List.map (fun f ->
                            let d =
                                if f.Decoder.Contains " " then
                                    "(" + f.Decoder + ")"
                                else
                                    f.Decoder

                            sprintf
                                "                         |> Decode.apply (Decode.field \"%s\" %d %s)"
                                f.FieldName
                                f.Position
                                d)

                    [
                        sprintf "            | %d ->" c.Tag
                        "                Some("
                        "                    Decode.fields"
                        sprintf "                        %d" (List.length fields)
                        sprintf
                            "                        (Decode.succeed (fun %s -> %s.%s(%s))"
                            parameters
                            typeSpelling
                            c.CaseName
                            arguments
                    ]
                    @ (applies
                       |> List.mapi (fun i line -> if i = List.length applies - 1 then line + ")" else line))
                    @ [ "                )" ])

        [
            sprintf "    %s %s: Decoder<%s> =" keyword binding typeSpelling
            sprintf "        Decode.union \"%s\" (function" typeSpelling
        ]
        @ arms
        @ [ "            | _ -> None)"; "" ]

    let private bindingBody (keyword: string) =
        function
        | RecordDecoder(b, t, fields) -> recordBody keyword b t fields
        | UnionDecoder(b, t, cases) -> unionBody keyword b t cases

    /// Phase 816 — a binding of a `let rec` group, eta-expanded.
    ///
    /// The body a plain binding evaluates at initialisation is wrapped in
    /// `fun value -> (…) value`, so a recursive reference inside it is read
    /// on the first DECODE rather than while the group is being built.
    /// That is what keeps a recursive plan an ordinary value: without it
    /// F# would either reject the group or guard every back-edge with a
    /// runtime initialisation check (warning FS0040), and the emitted code
    /// would carry a hazard the algebra has no name for. Applied to every
    /// member of a recursive group and to nothing else; the cost is one
    /// closure allocation per member at module load.
    let private etaExpand (lines: string list) =
        // A body line may carry several source lines joined by `\n` (the
        // record shape's assignments and applies do), so flatten first;
        // the trailing blank separator is re-appended after the wrap.
        let flat = lines |> List.collect (fun l -> l.Split '\n' |> List.ofArray)

        match flat with
        | header :: body ->
            let body = body |> List.filter (fun l -> l <> "")

            // Every body line sits at eight spaces or deeper; the wrap
            // re-homes it under the lambda at twelve, one further for the
            // continuation lines so they stay right of the opening paren.
            let wrapped =
                body
                |> List.mapi (fun i l ->
                    let content = l.Substring 8

                    let shifted =
                        if i = 0 then
                            "            (" + content
                        else
                            "             " + content

                    if i = List.length body - 1 then shifted + ")" else shifted)

            [ header; "        fun value ->" ] @ wrapped @ [ "                value"; "" ]
        | [] -> []

    /// Every key the emitted `registerAll` registers, bindings first then
    /// roots, deduplicated by `Type.FullName` and order-preserving.
    let coveredSpellings (plan: GenerationPlan) : (string * string) list =
        let bindingEntries =
            plan.Bindings |> List.map (fun b -> TypePlan.typeSpelling b, TypePlan.binding b)

        let bound = bindingEntries |> List.map fst |> Set.ofList

        let rootEntries =
            plan.Roots
            |> List.filter (fun r -> not (bound.Contains r.RootSpelling))
            |> List.map (fun r -> r.RootSpelling, r.RootDecoder)

        bindingEntries @ rootEntries

    let private coveredBlock (plan: GenerationPlan) =
        let entries =
            coveredSpellings plan
            |> List.map (fun (spelling, _) -> sprintf "        typeof<%s>.FullName" spelling)

        [
            "    /// The wire types this module covers, in registration order."
            "    let covered: string list = ["
        ]
        @ entries
        @ [ "    ]"; "" ]

    let private registerBlock (plan: GenerationPlan) =
        let registrations =
            coveredSpellings plan
            |> List.map (fun (spelling, decoder) ->
                let d =
                    if decoder.Contains " " then
                        "(" + decoder + ")"
                    else
                        decoder

                sprintf "        RemotingDecoders.register<%s> %s" spelling d)

        // Phase 801 — the differential gate, emitted beside the
        // registrations. `verifyAll` runs every decoder this module
        // registers beside the reflection reader over draws of its own
        // type, and `registerAllVerified` registers ONLY when every one
        // agrees. .NET only, because drawing and encoding a value need
        // reflection and the shipped writer; the browser registers what a
        // build gate verified.
        let verifications =
            coveredSpellings plan
            |> List.map (fun (spelling, decoder) ->
                let d =
                    if decoder.Contains " " then
                        "(" + decoder + ")"
                    else
                        decoder

                sprintf "        RemotingDecoders.verify<%s> draws seed %s" spelling d)

        [
            "    /// Register every decoder above. Idempotent, and explicit —"
            "    /// a static initialiser would fire at a moment nothing states,"
            "    /// so a deployment could not say whether the algebra path was live."
            "    let registerAll () : unit ="
        ]
        @ registrations
        @ [
            ""
            "#if !FABLE_COMPILER"
            "    /// Phase 801 — every decoder above beside the reflection reader,"
            "    /// over `draws` draws of its own type from `seed`. One outcome per"
            "    /// registration, in registration order; a refusal names the type"
            "    /// and the first diverging draw."
            "    let verifyAll (draws: int) (seed: int) : Result<DecoderVerification, DecoderRefusal> list = ["
        ]
        @ verifications
        @ [
            "    ]"
            ""
            "    /// Phase 801 — `registerAll`, gated: registers every decoder above"
            "    /// only when every one verifies, and registers NOTHING otherwise, so"
            "    /// a disagreement can never leave the table half-adopted."
            "    let registerAllVerified (draws: int) (seed: int) : Result<DecoderVerification list, DecoderRefusal list> ="
            "        let outcomes = verifyAll draws seed"
            ""
            "        let refusals ="
            "            outcomes"
            "            |> List.choose (function"
            "                | Error refusal -> Some refusal"
            "                | Ok _ -> None)"
            ""
            "        if List.isEmpty refusals then"
            "            registerAll ()"
            ""
            "            Ok("
            "                outcomes"
            "                |> List.choose (function"
            "                    | Ok verification -> Some verification"
            "                    | Error _ -> None)"
            "            )"
            "        else"
            "            Error refusals"
            "#endif"
            ""
        ]

    let private apiRecordsBlock (options: EmitOptions) =
        if List.isEmpty options.ApiRecords then
            []
        else
            let entries =
                options.ApiRecords
                |> List.map (fun (record, wireTypes, corpusCovered) ->
                    let types =
                        wireTypes |> List.map (sprintf "typeof<%s>.FullName") |> String.concat "; "

                    sprintf "        \"%s\", [ %s ], %b" record types corpusCovered)

            [
                "    /// The API records this module covers, shaped exactly as"
                "    /// `RemotingDecoderFacet.inspect` takes them. The corpus flag is"
                "    /// DECLARED by whoever generated this file, never inferred."
                "    let coveredApiRecords: (string * string list * bool) list = ["
            ]
            @ entries
            @ [ "    ]"; "" ]

    /// Render a plan as an F# compilation unit.
    let compilationUnit (options: EmitOptions) (plan: GenerationPlan) : string =
        let sb = StringBuilder()

        let write (lines: string list) =
            lines |> List.iter (fun l -> sb.Append(l).Append('\n') |> ignore)

        write (header options)

        // Phase 816 — each recursive group (contiguous in `Bindings`, by
        // the planner's ordering) is one `let rec … and …` of eta-expanded
        // bindings; every binding outside a group is the plain `let` it
        // always was, byte for byte.
        let groupOf (name: string) =
            plan.RecursiveGroups |> List.tryFind (List.contains name)

        // Phase 801 — every binding is public surface of the module that
        // hosts it, so each carries the doc comment the tracked surface
        // asks of a public member (the doc-coverage ratchet): what it
        // decodes, and that it was read off the type rather than written.
        let docOf (binding: TypePlan) = [
            sprintf
                "    /// Generated decoder for `%s` — one combinator per field or case, read off the type's own shape."
                (TypePlan.typeSpelling binding)
        ]

        plan.Bindings
        |> List.iter (fun binding ->
            let name = TypePlan.binding binding

            match groupOf name with
            | None -> write (docOf binding @ bindingBody "let" binding)
            | Some group ->
                let keyword = if List.head group = name then "let rec" else "and"
                write (docOf binding @ etaExpand (bindingBody keyword binding)))

        write (coveredBlock plan)
        write (registerBlock plan)
        write (apiRecordsBlock options)
        sb.ToString()

    /// The refusals, rendered for a human. Printed by the CLI rather than
    /// emitted into the file: a refused type keeps the reflection path, and
    /// a comment in a generated file is not where an operator looks.
    let refusalReport (plan: GenerationPlan) : string =
        if List.isEmpty plan.Refusals then
            "no refusals — every requested wire type is expressible in the closed algebra"
        else
            plan.Refusals
            |> List.map (fun r -> sprintf "  %s\n    %s" r.RefusedType r.Why)
            |> String.concat "\n"
            |> sprintf "%d wire type(s) kept the reflection path:\n%s" (List.length plan.Refusals)