// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)

namespace ToolUp.Remoting.Generator

open System
open System.Text

// =============================================================================
// Phase 69k — rendering a plan as F# source
// =============================================================================
//
// The emitter renders and decides NOTHING. Every choice about which combinator
// decodes what, in which order, and what is refused, was made in `Plan`; this
// file turns that record into text. Keeping the split sharp is what lets the
// fidelity test (Phase 69k.I) assert against the PLAN — a structural claim
// about decoder expressions per field — rather than against formatted source,
// which would make the test a whitespace pin.
//
// The emitted module is deliberately the same shape as the hand-written
// `PlatformDecoders` (Phase 785): named decoders in dependency order, then
// `covered`, then `registerAll`, then `coveredApiRecords`. A reader who has
// read one has read the other, and the facet consumes both through the same
// `RemotingDecoderFacet.inspect`.

/// What to emit, beyond the plan itself.
type EmitOptions = {
    /// The namespace the module is declared in. `ToolUp.Remoting` puts the
    /// module beside `RemotingDecoders` and `Decode`, which is where a
    /// registration module belongs.
    Namespace: string
    /// The module's name.
    ModuleName: string
    /// `open` lines beyond `System`, in the order they should appear.
    Opens: string list
    /// One entry per API record the emitted `registerAll` covers:
    /// the record's name, the F# SOURCE SPELLING of every wire type it
    /// carries, and whether the wire corpus draws those shapes.
    ///
    /// Spellings rather than `Type.FullName` strings, because the facet
    /// compares against `RemotingDecoders.registered ()`, which is keyed by
    /// `FullName` — and a generic type's `FullName` embeds the assembly
    /// VERSION of every type argument. Emitting those as literals would
    /// bake `Version=0.23.0.0` into generated source and silently stop
    /// matching at the next version bump; emitting `typeof<…>.FullName`
    /// computes the same string at runtime and cannot go stale.
    ///
    /// The corpus flag is a DECLARATION the caller makes, never something
    /// the generator infers — `false` is the honest default, and the facet
    /// renders `Observed` rather than `Verified` for it.
    ApiRecords: (string * string list * bool) list
}

[<RequireQualifiedAccess>]
module Emit =

    let private header (options: EmitOptions) =
        [
            "// SPDX-License-Identifier: Apache-2.0"
            "// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)"
            "//"
            "// <auto-generated>"
            "//   Phase 69k — emitted by ToolUp.Remoting.Generator from the SAME"
            "//   record/union metadata `Write.writeRecord` and `Write.writeUnion`"
            "//   enumerate, so field positions and union tags are the writer's own"
            "//   ordering rather than a second derivation of it."
            "//"
            "//   DO NOT EDIT. Re-run the generator; a contract test in"
            "//   ToolUp.Platform.Tests holds this file to what the generator emits."
            "// </auto-generated>"
            ""
            sprintf "namespace %s" options.Namespace
            ""
            "open System"
            // Phase 804 — the algebra's home, opened explicitly. The default
            // namespace IS `ToolUp.Remoting`, where `Decode`, `Decoder` and
            // `RemotingDecoders` resolve unqualified; a consumer emitting into
            // its own namespace (samples/HelloWorld-AOT was the first) found
            // none of them without this line.
            "open ToolUp.Remoting"
        ]
        @ (options.Opens |> List.map (sprintf "open %s"))
        @ [
            ""
            "[<RequireQualifiedAccess>]"
            sprintf "module %s =" options.ModuleName
            ""
        ]

    /// A record decoder: an applicative chain over the construction lambda.
    let private recordBody (binding: string) (typeSpelling: string) (fields: FieldPlan list) =
        let parameters =
            fields
            |> List.map (fun f -> Plan.parameterName f.FieldName)
            |> String.concat " "

        // Phase 804 — the construction is ANNOTATED with the record's own
        // spelling. A type declared inside a module (`WireCorpus.Address`)
        // has labels that are not in scope unless that module is opened,
        // and the lambda handed to `Decode.succeed` is checked before the
        // binding's annotation can reach it; an annotation on the record
        // expression itself resolves the labels type-directed. Measured
        // against the alternatives: a module-qualified first label leaves
        // the remaining labels unresolved, and a `Module.Type.Label` path is
        // an invalid field label outright. Harmless where the labels were
        // already in scope, the only case the hand-written decoders met.
        let assignments =
            fields
            |> List.map (fun f -> sprintf "            %s = %s" f.FieldName (Plan.parameterName f.FieldName))
            |> String.concat "\n"

        let applies =
            fields
            |> List.map (fun f ->
                let d =
                    if f.Decoder.Contains " " then
                        "(" + f.Decoder + ")"
                    else
                        f.Decoder

                sprintf "        |> Decode.apply (Decode.field \"%s\" %d %s)" f.FieldName f.Position d)
            |> String.concat "\n"

        [
            sprintf "    let %s: Decoder<%s> =" binding typeSpelling
            sprintf "        Decode.succeed (fun %s -> ({" parameters
            assignments
            sprintf "        }: %s))" typeSpelling
            applies
            ""
        ]

    /// A union decoder: a total tag match, with an unrecognised tag
    /// refusing rather than falling through.
    let private unionBody (binding: string) (typeSpelling: string) (cases: UnionCasePlan list) =
        let arms =
            cases
            |> List.collect (fun c ->
                match c.Payload with
                | CasePayload.NoFields -> [
                    sprintf "            | %d -> Some(Decode.case0 %s.%s)" c.Tag typeSpelling c.CaseName
                  ]
                | CasePayload.OneField payload ->
                    let d =
                        if payload.Contains " " then
                            "(" + payload + ")"
                        else
                            payload

                    [
                        sprintf
                            "            | %d -> Some(Decode.payload (%s |> Decode.map %s.%s))"
                            c.Tag
                            d
                            typeSpelling
                            c.CaseName
                    ]
                | CasePayload.SeveralFields fields ->
                    // Phase 800 — `fields n` over the record-shaped pipeline
                    // the case's inner array is: `succeed` the case
                    // constructor, one `field` per declared field, in order.
                    let parameters =
                        fields
                        |> List.map (fun f -> Plan.parameterName f.FieldName)
                        |> String.concat " "

                    let arguments =
                        fields
                        |> List.map (fun f -> Plan.parameterName f.FieldName)
                        |> String.concat ", "

                    let applies =
                        fields
                        |> List.map (fun f ->
                            let d =
                                if f.Decoder.Contains " " then
                                    "(" + f.Decoder + ")"
                                else
                                    f.Decoder

                            sprintf
                                "                         |> Decode.apply (Decode.field \"%s\" %d %s)"
                                f.FieldName
                                f.Position
                                d)

                    [
                        sprintf "            | %d ->" c.Tag
                        "                Some("
                        "                    Decode.fields"
                        sprintf "                        %d" (List.length fields)
                        sprintf
                            "                        (Decode.succeed (fun %s -> %s.%s(%s))"
                            parameters
                            typeSpelling
                            c.CaseName
                            arguments
                    ]
                    @ (applies
                       |> List.mapi (fun i line -> if i = List.length applies - 1 then line + ")" else line))
                    @ [ "                )" ])

        [
            sprintf "    let %s: Decoder<%s> =" binding typeSpelling
            sprintf "        Decode.union \"%s\" (function" typeSpelling
        ]
        @ arms
        @ [ "            | _ -> None)"; "" ]

    let private bindingBody =
        function
        | RecordDecoder(b, t, fields) -> recordBody b t fields
        | UnionDecoder(b, t, cases) -> unionBody b t cases

    /// Every key the emitted `registerAll` registers, bindings first then
    /// roots, deduplicated by `Type.FullName` and order-preserving.
    let coveredSpellings (plan: GenerationPlan) : (string * string) list =
        let bindingEntries =
            plan.Bindings |> List.map (fun b -> TypePlan.typeSpelling b, TypePlan.binding b)

        let bound = bindingEntries |> List.map fst |> Set.ofList

        let rootEntries =
            plan.Roots
            |> List.filter (fun r -> not (bound.Contains r.RootSpelling))
            |> List.map (fun r -> r.RootSpelling, r.RootDecoder)

        bindingEntries @ rootEntries

    let private coveredBlock (plan: GenerationPlan) =
        let entries =
            coveredSpellings plan
            |> List.map (fun (spelling, _) -> sprintf "        typeof<%s>.FullName" spelling)

        [
            "    /// The wire types this module covers, in registration order."
            "    let covered: string list = ["
        ]
        @ entries
        @ [ "    ]"; "" ]

    let private registerBlock (plan: GenerationPlan) =
        let registrations =
            coveredSpellings plan
            |> List.map (fun (spelling, decoder) ->
                let d =
                    if decoder.Contains " " then
                        "(" + decoder + ")"
                    else
                        decoder

                sprintf "        RemotingDecoders.register<%s> %s" spelling d)

        [
            "    /// Register every decoder above. Idempotent, and explicit —"
            "    /// a static initialiser would fire at a moment nothing states,"
            "    /// so a deployment could not say whether the algebra path was live."
            "    let registerAll () : unit ="
        ]
        @ registrations
        @ [ "" ]

    let private apiRecordsBlock (options: EmitOptions) =
        if List.isEmpty options.ApiRecords then
            []
        else
            let entries =
                options.ApiRecords
                |> List.map (fun (record, wireTypes, corpusCovered) ->
                    let types =
                        wireTypes |> List.map (sprintf "typeof<%s>.FullName") |> String.concat "; "

                    sprintf "        \"%s\", [ %s ], %b" record types corpusCovered)

            [
                "    /// The API records this module covers, shaped exactly as"
                "    /// `RemotingDecoderFacet.inspect` takes them. The corpus flag is"
                "    /// DECLARED by whoever generated this file, never inferred."
                "    let coveredApiRecords: (string * string list * bool) list = ["
            ]
            @ entries
            @ [ "    ]"; "" ]

    /// Render a plan as an F# compilation unit.
    let compilationUnit (options: EmitOptions) (plan: GenerationPlan) : string =
        let sb = StringBuilder()

        let write (lines: string list) =
            lines |> List.iter (fun l -> sb.Append(l).Append('\n') |> ignore)

        write (header options)
        plan.Bindings |> List.iter (bindingBody >> write)
        write (coveredBlock plan)
        write (registerBlock plan)
        write (apiRecordsBlock options)
        sb.ToString()

    /// The refusals, rendered for a human. Printed by the CLI rather than
    /// emitted into the file: a refused type keeps the reflection path, and
    /// a comment in a generated file is not where an operator looks.
    let refusalReport (plan: GenerationPlan) : string =
        if List.isEmpty plan.Refusals then
            "no refusals — every requested wire type is expressible in the closed algebra"
        else
            plan.Refusals
            |> List.map (fun r -> sprintf "  %s\n    %s" r.RefusedType r.Why)
            |> String.concat "\n"
            |> sprintf "%d wire type(s) kept the reflection path:\n%s" (List.length plan.Refusals)