// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Andrew J. Willshire / ToolUp Analytics Ltd (UK)
//
// <auto-generated>
//   Phase 853 — emitted by ToolUp.Remoting.Generator from the SAME
//   record/union metadata the System.Text.Json converter set reads:
//   one encoder per argument type and one decoder per response type an
//   API record's methods carry, and one proxy builder per record.
//
//   DO NOT EDIT. Re-run the generator; a contract test in
//   ToolUp.Platform.Tests holds this file to what the generator emits.
// </auto-generated>

namespace ToolUp.Platform.Tests.Remoting

open System
open ToolUp.Remoting
open ToolUp.Remoting.Json
open ToolUp.Remoting.Client
open ToolUp.Platform.Tests.Remoting

/// Generated client proxies: each API record's methods build their request
/// through generated encoders and read their response through generated
/// decoders, with no reflection at construction or per call. Emitted by
/// ToolUp.Remoting.Generator; do not edit.
[<RequireQualifiedAccess>]
module ReadCatalogClientProxies =

    /// Generated client proxy for `ReadPolicyFixture.ReadCatalogApi` — 4 method(s), each a closure over its
    /// generated encoders, the transport and its generated response decoder.
    let readCatalogApiProxy (options: RemoteBuilderOptions) : ReadPolicyFixture.ReadCatalogApi =
        ReadPolicies.register "ToolUp.Platform.Tests.Remoting.ReadPolicyFixture.ReadCatalogApi" [
            "GetCount", ReadPolicy.cacheable 60
            "GetShared", ReadPolicy.cacheable 0
            "Bump", ReadPolicy.invalidates [ "GetCount" ]
        ]

        let api = Proxy.generatedApi "ToolUp.Platform.Tests.Remoting.ReadPolicyFixture.ReadCatalogApi" "ReadCatalogApi" options
        let callGetCount = Proxy.generatedMethod<int> api "GetCount" true JsonDecode.asInt32
        let callGetShared = Proxy.generatedMethod<int> api "GetShared" true JsonDecode.asInt32
        let callGetUndeclared = Proxy.generatedMethod<int> api "GetUndeclared" true JsonDecode.asInt32
        let callBump = Proxy.generatedMethod<int> api "Bump" true JsonDecode.asInt32

        {
            GetCount = fun a0 -> callGetCount (JsonEncode.arguments [ JsonEncode.string a0 ])
            GetShared = fun a0 -> callGetShared (JsonEncode.arguments [ JsonEncode.string a0 ])
            GetUndeclared = fun a0 -> callGetUndeclared (JsonEncode.arguments [ JsonEncode.string a0 ])
            Bump = fun a0 -> callBump (JsonEncode.arguments [ JsonEncode.string a0 ])
        }

    /// The API records this module builds a generated proxy for, by the key
    /// `Api.makeProxy` looks a record up under.
    let coveredApiRecords: string list = [
        "ToolUp.Platform.Tests.Remoting.ReadPolicyFixture.ReadCatalogApi"
    ]

    /// The generated proxy for the record `apiKey` names, built over
    /// `options`; `None` for a record this module does not cover.
    let tryBuild (apiKey: string) (options: RemoteBuilderOptions) : obj option =
        match apiKey with
        | "ToolUp.Platform.Tests.Remoting.ReadPolicyFixture.ReadCatalogApi" -> Some(box (readCatalogApiProxy options))
        | _ -> None

    /// Register every proxy builder above with `GeneratedProxies`, where
    /// `Api.makeProxy` finds it. Idempotent; call it at composition. A proxy
    /// built before it runs resolves on its first call instead.
    let registerAll () : unit =
        GeneratedProxies.register "ToolUp.Platform.Tests.Remoting.ReadPolicyFixture.ReadCatalogApi" (fun options -> box (readCatalogApiProxy options))

