#Requires -Version 7.0
<#
.SYNOPSIS
    Phase 805 — the three-way merge driver for the generated API baselines.

.DESCRIPTION
    `api-baselines/<Assembly>.approved.txt` (Phase 175) and
    `api-baselines/doc-coverage.approved.txt` (Phase 261) are PROJECTIONS: pure
    functions of the built tree, regenerated by `TOOLUP_APPROVE_API`. Two branches
    that each add disjoint public members therefore conflict on them textually
    while agreeing on them semantically — the merged projection is fully
    determined, and git's line merge cannot compute it because the additions land
    in the same sorted region.

    This driver computes it. It is registered by `dotnet run -- Setup`, which
    writes the `merge.toolup-*.driver` commands into THIS CLONE's `.git/config`;
    `.gitattributes` names the driver per path. A clone that has not run Setup has
    no driver definition, so git falls back to its built-in text merge and the
    developer sees today's plain conflict — the gate itself is untouched (GP 11).

    Modes:

      -Mode coverage   `doc-coverage.approved.txt`. One row per assembly,
                       `<assembly> <documented>/<total>`. Per row the merged value
                       is `base + (ours - base) + (theirs - base)` on BOTH numbers
                       — the arithmetic six hand resolutions on 2026-09-16 each
                       performed and each re-gated. A row present on only one side
                       is taken as-is. A row whose arithmetic goes negative, or
                       whose documented count would exceed its total, is left
                       CONFLICTED: that is a real disagreement, not a merge.

      -Mode members    `<Assembly>.approved.txt`. The header comes from base by an
                       ordinary three-way rule; the body is the union of both
                       sides' additions over base, re-emitted in the generator's
                       own order (types by ordinal FullName, members by ordinal
                       token within their type, an `(obsolete)` marker following
                       the token it marks). A line REMOVED on one side while the
                       other side left it untouched is taken as removed (Phase
                       933): that side's own baseline already carried the
                       removal, so the breaking change reached its human
                       (Phase 618) on the branch that made it — and a retype is
                       exactly such a removal plus an addition. What stays
                       CONFLICTED is the case no three-way rule can decide: a
                       row removed on BOTH sides whose replacements differ —
                       deleted on one side and retyped on the other, or retyped
                       two different ways. A row is keyed by the line's leading
                       name (`Type.Member`, `Type..ctor`, or the type itself),
                       so an overload set shares one key.

    Exit 0 with the merged bytes in %A, or exit 1 with %A carrying standard
    conflict markers and the reason on stderr.

.PARAMETER Mode
    `coverage` or `members`.

.PARAMETER Base
    git's %O — the merge base's version of the file.

.PARAMETER Ours
    git's %A — our version on entry, and the file the result is WRITTEN to.

.PARAMETER Theirs
    git's %B — their version of the file.

.PARAMETER Pathname
    git's %P — the path being merged, used only in the stderr reason.

.EXAMPLE
    pwsh -NoProfile -File dev-scripts/merge-baselines.ps1 -Mode coverage %O %A %B %P

.NOTES
    Dependency-free by design: it runs inside `git merge`, under whatever `pwsh`
    is on PATH, in a tree that may not build. No dotnet, no modules, nothing but
    the shared framework. The regenerate-from-the-merged-tree fallback for the
    conflicted cases is `dotnet run -- MergeBaselines --assemblies <a,b>`.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][ValidateSet('coverage', 'members')][string]$Mode,
    [Parameter(Mandatory, Position = 0)][string]$Base,
    [Parameter(Mandatory, Position = 1)][string]$Ours,
    [Parameter(Mandatory, Position = 2)][string]$Theirs,
    [Parameter(Position = 3)][string]$Pathname = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# .NET's file APIs do not track PowerShell's location, so every path is resolved
# against the FileSystem provider's directory before it reaches them.
function Resolve-AgainstCwd([string]$path) {
    [System.IO.Path]::GetFullPath($path, (Get-Location -PSProvider FileSystem).ProviderPath)
}

function Read-LfLines([string]$path) {
    if ([string]::IsNullOrWhiteSpace($path)) { return @() }
    $full = Resolve-AgainstCwd $path
    if (-not [System.IO.File]::Exists($full)) { return @() }
    $text = [System.IO.File]::ReadAllText($full).Replace("`r`n", "`n")
    if ($text.Length -eq 0) { return @() }
    $lines = $text.Split("`n")
    # A trailing newline yields one final empty element; drop exactly that one so
    # a round-trip through Write-LfFile is byte-identical.
    if ($lines[-1] -eq '') { $lines = $lines[0..($lines.Length - 2)] }
    return , [string[]]$lines
}

function Write-LfFile([string]$path, [string[]]$lines) {
    $full = Resolve-AgainstCwd $path
    $text = if ($lines.Count -eq 0) { '' } else { ($lines -join "`n") + "`n" }
    # LF and no BOM: `.gitattributes` pins these files to `eol=lf`, and a BOM
    # would be a one-byte diff against every regeneration.
    [System.IO.File]::WriteAllText($full, $text, (New-Object System.Text.UTF8Encoding($false)))
}

function Sort-Ordinal([string[]]$items) {
    $list = [System.Collections.Generic.List[string]]::new()
    foreach ($i in $items) { $list.Add($i) }
    # Ordinal, matching `String.CompareOrdinal` in the generator. A culture sort
    # would order `.` against `+` differently and the next regen would rewrite
    # the file.
    $list.Sort([System.StringComparer]::Ordinal)
    return , [string[]]$list.ToArray()
}

# Concatenate line groups into ONE flat string array. Written out rather than
# composed with `@(...) + @(...)`, which binds an inner array to a `[string[]]`
# parameter by space-joining it: the whole body arrived at `Write-LfFile` as a
# single line during this phase's own bring-up, and the file's LENGTH was
# unchanged, so only a byte compare caught it.
function Join-Lines() {
    $flat = [System.Collections.Generic.List[string]]::new()

    foreach ($group in $args) {
        foreach ($line in $group) { $flat.Add([string]$line) }
    }

    , [string[]]$flat.ToArray()
}

function Exit-Conflict([string]$reason) {
    $out = Join-Lines @('<<<<<<< ours') (Read-LfLines $Ours) @('=======') (Read-LfLines $Theirs) @('>>>>>>> theirs')
    Write-LfFile $Ours $out
    $where = if ([string]::IsNullOrWhiteSpace($Pathname)) { 'the baseline' } else { $Pathname }
    [Console]::Error.WriteLine("merge-baselines ($Mode): $where left CONFLICTED — $reason")
    [Console]::Error.WriteLine('Resolve it by REGENERATING from the merged tree, never by picking a side:')
    [Console]::Error.WriteLine('  dotnet run -- MergeBaselines --assemblies <assembly,...>')
    exit 1
}

# The leading comment block is the generated header; everything after the first
# non-comment line is body.
function Split-Header([string[]]$lines) {
    $header = [System.Collections.Generic.List[string]]::new()
    $body = [System.Collections.Generic.List[string]]::new()
    $inHeader = $true

    foreach ($l in $lines) {
        if ($inHeader -and $l.StartsWith('#')) { $header.Add($l) } else { $inHeader = $false; $body.Add($l) }
    }

    @{ Header = [string[]]$header.ToArray(); Body = [string[]]$body.ToArray() }
}

# An ordinary three-way merge of the header block: unchanged on a side means that
# side has nothing to say about it. Both sides changing it differently is a real
# conflict — the header names the assembly and the regeneration switch, and
# guessing at it would hide a generator change.
function Merge-Header([string[]]$b, [string[]]$o, [string[]]$t) {
    $bs = $b -join "`n"
    $os = $o -join "`n"
    $ts = $t -join "`n"
    if ($os -ceq $ts) { return , $o }
    if ($os -ceq $bs) { return , $t }
    if ($ts -ceq $bs) { return , $o }
    $null
}

# ─── Mode: coverage ──────────────────────────────────────────────────

$script:CoverageRow = [regex]'^(?<name>\S+)\s+(?<documented>\d+)/(?<total>\d+)\s*$'

# Unlike the gate's own parser, an unparseable row is NOT dropped here. The gate
# drops it so a mangled line reads as "no floor recorded", which fails loudly at
# that assembly; a merge driver that dropped it would DELETE the line and present
# the deletion as a clean merge.
function ConvertFrom-CoverageBody([string[]]$body, [string]$side) {
    $rows = [System.Collections.Generic.Dictionary[string, int[]]]::new([System.StringComparer]::Ordinal)

    foreach ($l in $body) {
        $t = $l.Trim()
        if ($t -eq '' -or $t.StartsWith('#')) { continue }
        $m = $script:CoverageRow.Match($t)
        if (-not $m.Success) { Exit-Conflict "the $side side carries a row this driver cannot parse: '$t'" }
        $rows[$m.Groups['name'].Value] = @([int]$m.Groups['documented'].Value, [int]$m.Groups['total'].Value)
    }

    $rows
}

function Invoke-CoverageMerge() {
    $b = Split-Header (Read-LfLines $Base)
    $o = Split-Header (Read-LfLines $Ours)
    $t = Split-Header (Read-LfLines $Theirs)

    $header = Merge-Header $b.Header $o.Header $t.Header
    if ($null -eq $header) { Exit-Conflict 'both sides rewrote the generated header differently' }

    $bRows = ConvertFrom-CoverageBody $b.Body 'base'
    $oRows = ConvertFrom-CoverageBody $o.Body 'ours'
    $tRows = ConvertFrom-CoverageBody $t.Body 'theirs'

    $names = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($src in @($bRows, $oRows, $tRows)) { foreach ($k in $src.Keys) { [void]$names.Add($k) } }

    $merged = [System.Collections.Generic.Dictionary[string, int[]]]::new([System.StringComparer]::Ordinal)

    foreach ($name in $names) {
        $inB = $bRows.ContainsKey($name)
        $inO = $oRows.ContainsKey($name)
        $inT = $tRows.ContainsKey($name)

        if ($inB) {
            $bv = $bRows[$name]

            if (-not $inO -and -not $inT) {
                # Dropped on both sides — the package left the tracked set.
                continue
            }
            elseif (-not $inO) {
                # Ours dropped the row. Taking the deletion is right only if
                # theirs left it alone; a modified row means the two sides
                # disagree about whether the package still exists.
                $tv = $tRows[$name]

                if ($tv[0] -ne $bv[0] -or $tv[1] -ne $bv[1]) {
                    Exit-Conflict "row '$name' was removed on one side and changed on the other"
                }

                continue
            }
            elseif (-not $inT) {
                $ov = $oRows[$name]

                if ($ov[0] -ne $bv[0] -or $ov[1] -ne $bv[1]) {
                    Exit-Conflict "row '$name' was removed on one side and changed on the other"
                }

                continue
            }

            $ov = $oRows[$name]
            $tv = $tRows[$name]
            $documented = $bv[0] + ($ov[0] - $bv[0]) + ($tv[0] - $bv[0])
            $total = $bv[1] + ($ov[1] - $bv[1]) + ($tv[1] - $bv[1])

            if ($documented -lt 0 -or $total -lt 0) {
                Exit-Conflict "row '$name' merges to a negative count ($documented/$total) — the two sides' deltas cannot both be right"
            }

            if ($documented -gt $total) {
                Exit-Conflict "row '$name' merges to $documented documented of $total total — more documented members than members"
            }

            $merged[$name] = @($documented, $total)
        }
        else {
            # New to base. One side only: take it. Both sides, same numbers: take
            # it. Both sides, different numbers: there is no base to difference
            # against, so nothing here can compute the answer.
            if ($inO -and $inT) {
                $ov = $oRows[$name]
                $tv = $tRows[$name]

                if ($ov[0] -ne $tv[0] -or $ov[1] -ne $tv[1]) {
                    Exit-Conflict "row '$name' is new on both sides with different counts ($($ov[0])/$($ov[1]) vs $($tv[0])/$($tv[1]))"
                }

                $merged[$name] = $ov
            }
            elseif ($inO) { $merged[$name] = $oRows[$name] }
            else { $merged[$name] = $tRows[$name] }
        }
    }

    # `foreach`, not a pipeline: `Sort-Ordinal` returns ONE string array, and a
    # pipeline hands that whole array to the first `ForEach-Object` iteration.
    $rows = [System.Collections.Generic.List[string]]::new()

    foreach ($name in (Sort-Ordinal @($merged.Keys))) {
        $rows.Add("$name $($merged[$name][0])/$($merged[$name][1])")
    }

    Write-LfFile $Ours (Join-Lines $header $rows)
    exit 0
}

# ─── Mode: members ───────────────────────────────────────────────────

# The closed set of kinds `typeKind` emits. Tight on purpose: no member line can
# match it (a field carries ` : `, a marker two spaces), so a type header is
# identifiable without tracking which type is open.
$script:TypeHeader = [regex]'^(?<name>\S+) \((?:enum|interface|delegate|struct|class)\)$'
$script:ObsoleteSuffix = '  (obsolete)'
# A member's row name: everything before its parameter list or its ` : type`.
$script:RowName = [regex]'^[^ (]+'

function New-TypeBlock() {
    @{
        Header  = [System.Collections.Generic.List[string]]::new()
        Members = [System.Collections.Generic.Dictionary[string, System.Collections.Generic.List[string]]]::new([System.StringComparer]::Ordinal)
    }
}

# Parse a body into type blocks. Each block is its header line (plus that type's
# own `(obsolete)` marker, if it carries one) and its member entries, each entry
# being a token line plus that token's marker.
function ConvertFrom-MembersBody([string[]]$body, [string]$side) {
    $types = [System.Collections.Generic.Dictionary[string, hashtable]]::new([System.StringComparer]::Ordinal)
    $current = $null
    $lastToken = $null
    $lastBucket = $null

    foreach ($l in $body) {
        if ($l -eq '') { continue }

        $m = $script:TypeHeader.Match($l)

        if ($m.Success) {
            $name = $m.Groups['name'].Value
            if (-not $types.ContainsKey($name)) { $types[$name] = New-TypeBlock }
            $current = $types[$name]
            if (-not $current.Header.Contains($l)) { $current.Header.Add($l) }
            $lastToken = $l
            $lastBucket = $current.Header
            continue
        }

        if ($null -eq $current) {
            Exit-Conflict "the $side side has a body line before any type header: '$l'"
        }

        if ($null -ne $lastToken -and $l -ceq ($lastToken + $script:ObsoleteSuffix)) {
            if (-not $lastBucket.Contains($l)) { $lastBucket.Add($l) }
            continue
        }

        if (-not $current.Members.ContainsKey($l)) {
            $current.Members[$l] = [System.Collections.Generic.List[string]]::new()
            $current.Members[$l].Add($l)
        }

        $lastToken = $l
        $lastBucket = $current.Members[$l]
    }

    $types
}

# Union two parsed bodies. Both sides' additions survive; nothing is chosen
# between, because by the time this runs the removal check has established that
# neither side removed anything.
function Join-TypeBlocks($a, $b) {
    $out = [System.Collections.Generic.Dictionary[string, hashtable]]::new([System.StringComparer]::Ordinal)

    foreach ($src in @($a, $b)) {
        foreach ($name in $src.Keys) {
            if (-not $out.ContainsKey($name)) { $out[$name] = New-TypeBlock }
            $dst = $out[$name]

            foreach ($h in $src[$name].Header) { if (-not $dst.Header.Contains($h)) { $dst.Header.Add($h) } }

            foreach ($token in $src[$name].Members.Keys) {
                if (-not $dst.Members.ContainsKey($token)) {
                    $dst.Members[$token] = [System.Collections.Generic.List[string]]::new()
                }

                foreach ($line in $src[$name].Members[$token]) {
                    if (-not $dst.Members[$token].Contains($line)) { $dst.Members[$token].Add($line) }
                }
            }
        }
    }

    $out
}

# Re-emit in the generator's order: types by ordinal FullName, members by ordinal
# token, each marker immediately after what it marks.
function Write-TypeBlocks($types) {
    $out = [System.Collections.Generic.List[string]]::new()

    foreach ($name in (Sort-Ordinal @($types.Keys))) {
        foreach ($h in $types[$name].Header) { $out.Add($h) }

        foreach ($token in (Sort-Ordinal @($types[$name].Members.Keys))) {
            foreach ($line in $types[$name].Members[$token]) { $out.Add($line) }
        }
    }

    , [string[]]$out.ToArray()
}

function New-OrdinalSet([string[]]$lines) {
    $set = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($l in $lines) { if ($l -ne '') { [void]$set.Add($l) } }
    , $set
}

# The row a line belongs to: a type header by its type, a member (and its
# `(obsolete)` marker) by its leading `Type.Member` / `Type..ctor` name. A
# retype rewrites the line but keeps its key, which is what lets the removal
# check tell "retyped" from "deleted".
function Get-RowKey([string]$line) {
    $m = $script:TypeHeader.Match($line)
    if ($m.Success) { return 'type ' + $m.Groups['name'].Value }

    $l = if ($line.EndsWith($script:ObsoleteSuffix)) { $line.Substring(0, $line.Length - $script:ObsoleteSuffix.Length) } else { $line }
    $n = $script:RowName.Match($l)
    if ($n.Success) { return $n.Value }
    $l
}

# A side's added lines (absent from base), grouped by row key.
function Group-AddedByRowKey([string[]]$body, $baseSet) {
    $groups = [System.Collections.Generic.Dictionary[string, System.Collections.Generic.HashSet[string]]]::new([System.StringComparer]::Ordinal)

    foreach ($l in $body) {
        if ($l -eq '' -or $baseSet.Contains($l)) { continue }
        $key = Get-RowKey $l
        if (-not $groups.ContainsKey($key)) { $groups[$key] = New-OrdinalSet @() }
        [void]$groups[$key].Add($l)
    }

    , $groups
}

# Take the removals out of the union. A dropped line can take nothing with it
# that the other side changed: a marker the other side ADDED to a member this
# side removed, or members the other side added under a type this side removed,
# are a removal on one side and a change on the other.
function Remove-DroppedLines($types, $drop) {
    foreach ($name in @($types.Keys)) {
        $block = $types[$name]

        foreach ($h in @($block.Header)) { if ($drop.Contains($h)) { [void]$block.Header.Remove($h) } }

        foreach ($token in @($block.Members.Keys)) {
            $entry = $block.Members[$token]

            if ($drop.Contains($token)) {
                foreach ($line in $entry) {
                    if (-not $drop.Contains($line)) {
                        Exit-Conflict "row '$(Get-RowKey $token)' was removed on one side and changed on the other"
                    }
                }

                [void]$block.Members.Remove($token)
                continue
            }

            foreach ($line in @($entry)) { if ($drop.Contains($line)) { [void]$entry.Remove($line) } }
        }

        $hasHeader = $false
        foreach ($h in $block.Header) { if ($script:TypeHeader.IsMatch($h)) { $hasHeader = $true } }

        if (-not $hasHeader) {
            if ($block.Header.Count -gt 0 -or $block.Members.Count -gt 0) {
                Exit-Conflict "row 'type $name' was removed on one side and changed on the other"
            }

            [void]$types.Remove($name)
        }
    }
}

function Invoke-MembersMerge() {
    $b = Split-Header (Read-LfLines $Base)
    $o = Split-Header (Read-LfLines $Ours)
    $t = Split-Header (Read-LfLines $Theirs)

    $header = Merge-Header $b.Header $o.Header $t.Header
    if ($null -eq $header) { Exit-Conflict 'both sides rewrote the generated header differently' }

    $bSet = New-OrdinalSet $b.Body
    $oSet = New-OrdinalSet $o.Body
    $tSet = New-OrdinalSet $t.Body

    $oAdded = Group-AddedByRowKey $o.Body $bSet
    $tAdded = Group-AddedByRowKey $t.Body $bSet

    # Every base line one side no longer carries. Missing from ONE side only,
    # the other side left that line untouched, so the removal (or the removal
    # half of a retype) is that side's alone and is taken. Missing from BOTH,
    # the two sides must agree on what replaced the row.
    $drop = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)

    foreach ($line in $b.Body) {
        if ($line -eq '') { continue }
        $inO = $oSet.Contains($line)
        $inT = $tSet.Contains($line)
        if ($inO -and $inT) { continue }

        [void]$drop.Add($line)
        if ($inO -or $inT) { continue }

        $key = Get-RowKey $line
        # Assigned, not `$x = if (...) { $set }`: an `if` used as an
        # expression enumerates the set into its output, and a one-line
        # replacement arrives as a bare string.
        $ro = New-OrdinalSet @()
        $rt = New-OrdinalSet @()
        if ($oAdded.ContainsKey($key)) { $ro = $oAdded[$key] }
        if ($tAdded.ContainsKey($key)) { $rt = $tAdded[$key] }

        if ($ro.SetEquals($rt)) { continue }

        if ($ro.Count -eq 0 -or $rt.Count -eq 0) {
            Exit-Conflict "row '$key' was removed on one side and changed on the other"
        }

        Exit-Conflict "row '$key' was changed differently on the two sides"
    }

    $merged = Join-TypeBlocks (ConvertFrom-MembersBody $o.Body 'ours') (ConvertFrom-MembersBody $t.Body 'theirs')
    Remove-DroppedLines $merged $drop
    Write-LfFile $Ours (Join-Lines $header (Write-TypeBlocks $merged))
    exit 0
}

switch ($Mode) {
    'coverage' { Invoke-CoverageMerge }
    'members' { Invoke-MembersMerge }
}
