#Requires -Version 7.0
<#
.SYNOPSIS
    Phase 805 — the three-way merge driver for the generated API baselines.

.DESCRIPTION
    `api-baselines/<Assembly>.approved.txt` (Phase 175) and
    `api-baselines/doc-coverage.approved.txt` (Phase 261) are PROJECTIONS: pure
    functions of the built tree, regenerated by `TOOLUP_APPROVE_API`. Two branches
    that each add disjoint public members therefore conflict on them textually
    while agreeing on them semantically — the merged projection is fully
    determined, and git's line merge cannot compute it because the additions land
    in the same sorted region.

    This driver computes it. It is registered by `dotnet run -- Setup`, which
    writes the `merge.toolup-*.driver` commands into THIS CLONE's `.git/config`;
    `.gitattributes` names the driver per path. A clone that has not run Setup has
    no driver definition, so git falls back to its built-in text merge and the
    developer sees today's plain conflict — the gate itself is untouched (GP 11).

    Modes:

      -Mode coverage   `doc-coverage.approved.txt`. One row per assembly,
                       `<assembly> <documented>/<total>`. Per row the merged value
                       is `base + (ours - base) + (theirs - base)` on BOTH numbers
                       — the arithmetic six hand resolutions on 2026-09-16 each
                       performed and each re-gated. A row present on only one side
                       is taken as-is. A row whose arithmetic goes negative, or
                       whose documented count would exceed its total, is left
                       CONFLICTED: that is a real disagreement, not a merge.

      -Mode members    `<Assembly>.approved.txt`. The header comes from base by an
                       ordinary three-way rule; the body is the union of both
                       sides' additions over base, re-emitted in the generator's
                       own order (types by ordinal FullName, members by ordinal
                       token within their type, an `(obsolete)` marker following
                       the token it marks). A member REMOVED on either side leaves
                       the file CONFLICTED — a removal is the breaking direction
                       Phase 618 exists to put in front of a human, and no
                       automatic resolution of it is correct.

    Exit 0 with the merged bytes in %A, or exit 1 with %A carrying standard
    conflict markers and the reason on stderr.

.PARAMETER Mode
    `coverage` or `members`.

.PARAMETER Base
    git's %O — the merge base's version of the file.

.PARAMETER Ours
    git's %A — our version on entry, and the file the result is WRITTEN to.

.PARAMETER Theirs
    git's %B — their version of the file.

.PARAMETER Pathname
    git's %P — the path being merged, used only in the stderr reason.

.EXAMPLE
    pwsh -NoProfile -File dev-scripts/merge-baselines.ps1 -Mode coverage %O %A %B %P

.NOTES
    Dependency-free by design: it runs inside `git merge`, under whatever `pwsh`
    is on PATH, in a tree that may not build. No dotnet, no modules, nothing but
    the shared framework. The regenerate-from-the-merged-tree fallback for the
    conflicted cases is `dotnet run -- MergeBaselines --assemblies <a,b>`.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][ValidateSet('coverage', 'members')][string]$Mode,
    [Parameter(Mandatory, Position = 0)][string]$Base,
    [Parameter(Mandatory, Position = 1)][string]$Ours,
    [Parameter(Mandatory, Position = 2)][string]$Theirs,
    [Parameter(Position = 3)][string]$Pathname = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# .NET's file APIs do not track PowerShell's location, so every path is resolved
# against the FileSystem provider's directory before it reaches them.
function Resolve-AgainstCwd([string]$path) {
    [System.IO.Path]::GetFullPath($path, (Get-Location -PSProvider FileSystem).ProviderPath)
}

function Read-LfLines([string]$path) {
    if ([string]::IsNullOrWhiteSpace($path)) { return @() }
    $full = Resolve-AgainstCwd $path
    if (-not [System.IO.File]::Exists($full)) { return @() }
    $text = [System.IO.File]::ReadAllText($full).Replace("`r`n", "`n")
    if ($text.Length -eq 0) { return @() }
    $lines = $text.Split("`n")
    # A trailing newline yields one final empty element; drop exactly that one so
    # a round-trip through Write-LfFile is byte-identical.
    if ($lines[-1] -eq '') { $lines = $lines[0..($lines.Length - 2)] }
    return , [string[]]$lines
}

function Write-LfFile([string]$path, [string[]]$lines) {
    $full = Resolve-AgainstCwd $path
    $text = if ($lines.Count -eq 0) { '' } else { ($lines -join "`n") + "`n" }
    # LF and no BOM: `.gitattributes` pins these files to `eol=lf`, and a BOM
    # would be a one-byte diff against every regeneration.
    [System.IO.File]::WriteAllText($full, $text, (New-Object System.Text.UTF8Encoding($false)))
}

function Sort-Ordinal([string[]]$items) {
    $list = [System.Collections.Generic.List[string]]::new()
    foreach ($i in $items) { $list.Add($i) }
    # Ordinal, matching `String.CompareOrdinal` in the generator. A culture sort
    # would order `.` against `+` differently and the next regen would rewrite
    # the file.
    $list.Sort([System.StringComparer]::Ordinal)
    return , [string[]]$list.ToArray()
}

# Concatenate line groups into ONE flat string array. Written out rather than
# composed with `@(...) + @(...)`, which binds an inner array to a `[string[]]`
# parameter by space-joining it: the whole body arrived at `Write-LfFile` as a
# single line during this phase's own bring-up, and the file's LENGTH was
# unchanged, so only a byte compare caught it.
function Join-Lines() {
    $flat = [System.Collections.Generic.List[string]]::new()

    foreach ($group in $args) {
        foreach ($line in $group) { $flat.Add([string]$line) }
    }

    , [string[]]$flat.ToArray()
}

function Exit-Conflict([string]$reason) {
    $out = Join-Lines @('<<<<<<< ours') (Read-LfLines $Ours) @('=======') (Read-LfLines $Theirs) @('>>>>>>> theirs')
    Write-LfFile $Ours $out
    $where = if ([string]::IsNullOrWhiteSpace($Pathname)) { 'the baseline' } else { $Pathname }
    [Console]::Error.WriteLine("merge-baselines ($Mode): $where left CONFLICTED — $reason")
    [Console]::Error.WriteLine('Resolve it by REGENERATING from the merged tree, never by picking a side:')
    [Console]::Error.WriteLine('  dotnet run -- MergeBaselines --assemblies <assembly,...>')
    exit 1
}

# The leading comment block is the generated header; everything after the first
# non-comment line is body.
function Split-Header([string[]]$lines) {
    $header = [System.Collections.Generic.List[string]]::new()
    $body = [System.Collections.Generic.List[string]]::new()
    $inHeader = $true

    foreach ($l in $lines) {
        if ($inHeader -and $l.StartsWith('#')) { $header.Add($l) } else { $inHeader = $false; $body.Add($l) }
    }

    @{ Header = [string[]]$header.ToArray(); Body = [string[]]$body.ToArray() }
}

# An ordinary three-way merge of the header block: unchanged on a side means that
# side has nothing to say about it. Both sides changing it differently is a real
# conflict — the header names the assembly and the regeneration switch, and
# guessing at it would hide a generator change.
function Merge-Header([string[]]$b, [string[]]$o, [string[]]$t) {
    $bs = $b -join "`n"
    $os = $o -join "`n"
    $ts = $t -join "`n"
    if ($os -ceq $ts) { return , $o }
    if ($os -ceq $bs) { return , $t }
    if ($ts -ceq $bs) { return , $o }
    $null
}

# ─── Mode: coverage ──────────────────────────────────────────────────

$script:CoverageRow = [regex]'^(?<name>\S+)\s+(?<documented>\d+)/(?<total>\d+)\s*$'

# Unlike the gate's own parser, an unparseable row is NOT dropped here. The gate
# drops it so a mangled line reads as "no floor recorded", which fails loudly at
# that assembly; a merge driver that dropped it would DELETE the line and present
# the deletion as a clean merge.
function ConvertFrom-CoverageBody([string[]]$body, [string]$side) {
    $rows = [System.Collections.Generic.Dictionary[string, int[]]]::new([System.StringComparer]::Ordinal)

    foreach ($l in $body) {
        $t = $l.Trim()
        if ($t -eq '' -or $t.StartsWith('#')) { continue }
        $m = $script:CoverageRow.Match($t)
        if (-not $m.Success) { Exit-Conflict "the $side side carries a row this driver cannot parse: '$t'" }
        $rows[$m.Groups['name'].Value] = @([int]$m.Groups['documented'].Value, [int]$m.Groups['total'].Value)
    }

    $rows
}

function Invoke-CoverageMerge() {
    $b = Split-Header (Read-LfLines $Base)
    $o = Split-Header (Read-LfLines $Ours)
    $t = Split-Header (Read-LfLines $Theirs)

    $header = Merge-Header $b.Header $o.Header $t.Header
    if ($null -eq $header) { Exit-Conflict 'both sides rewrote the generated header differently' }

    $bRows = ConvertFrom-CoverageBody $b.Body 'base'
    $oRows = ConvertFrom-CoverageBody $o.Body 'ours'
    $tRows = ConvertFrom-CoverageBody $t.Body 'theirs'

    $names = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($src in @($bRows, $oRows, $tRows)) { foreach ($k in $src.Keys) { [void]$names.Add($k) } }

    $merged = [System.Collections.Generic.Dictionary[string, int[]]]::new([System.StringComparer]::Ordinal)

    foreach ($name in $names) {
        $inB = $bRows.ContainsKey($name)
        $inO = $oRows.ContainsKey($name)
        $inT = $tRows.ContainsKey($name)

        if ($inB) {
            $bv = $bRows[$name]

            if (-not $inO -and -not $inT) {
                # Dropped on both sides — the package left the tracked set.
                continue
            }
            elseif (-not $inO) {
                # Ours dropped the row. Taking the deletion is right only if
                # theirs left it alone; a modified row means the two sides
                # disagree about whether the package still exists.
                $tv = $tRows[$name]

                if ($tv[0] -ne $bv[0] -or $tv[1] -ne $bv[1]) {
                    Exit-Conflict "row '$name' was removed on one side and changed on the other"
                }

                continue
            }
            elseif (-not $inT) {
                $ov = $oRows[$name]

                if ($ov[0] -ne $bv[0] -or $ov[1] -ne $bv[1]) {
                    Exit-Conflict "row '$name' was removed on one side and changed on the other"
                }

                continue
            }

            $ov = $oRows[$name]
            $tv = $tRows[$name]
            $documented = $bv[0] + ($ov[0] - $bv[0]) + ($tv[0] - $bv[0])
            $total = $bv[1] + ($ov[1] - $bv[1]) + ($tv[1] - $bv[1])

            if ($documented -lt 0 -or $total -lt 0) {
                Exit-Conflict "row '$name' merges to a negative count ($documented/$total) — the two sides' deltas cannot both be right"
            }

            if ($documented -gt $total) {
                Exit-Conflict "row '$name' merges to $documented documented of $total total — more documented members than members"
            }

            $merged[$name] = @($documented, $total)
        }
        else {
            # New to base. One side only: take it. Both sides, same numbers: take
            # it. Both sides, different numbers: there is no base to difference
            # against, so nothing here can compute the answer.
            if ($inO -and $inT) {
                $ov = $oRows[$name]
                $tv = $tRows[$name]

                if ($ov[0] -ne $tv[0] -or $ov[1] -ne $tv[1]) {
                    Exit-Conflict "row '$name' is new on both sides with different counts ($($ov[0])/$($ov[1]) vs $($tv[0])/$($tv[1]))"
                }

                $merged[$name] = $ov
            }
            elseif ($inO) { $merged[$name] = $oRows[$name] }
            else { $merged[$name] = $tRows[$name] }
        }
    }

    # `foreach`, not a pipeline: `Sort-Ordinal` returns ONE string array, and a
    # pipeline hands that whole array to the first `ForEach-Object` iteration.
    $rows = [System.Collections.Generic.List[string]]::new()

    foreach ($name in (Sort-Ordinal @($merged.Keys))) {
        $rows.Add("$name $($merged[$name][0])/$($merged[$name][1])")
    }

    Write-LfFile $Ours (Join-Lines $header $rows)
    exit 0
}

# ─── Mode: members ───────────────────────────────────────────────────

# The closed set of kinds `typeKind` emits. Tight on purpose: no member line can
# match it (a field carries ` : `, a marker two spaces), so a type header is
# identifiable without tracking which type is open.
$script:TypeHeader = [regex]'^(?<name>\S+) \((?:enum|interface|delegate|struct|class)\)$'
$script:ObsoleteSuffix = '  (obsolete)'

function New-TypeBlock() {
    @{
        Header  = [System.Collections.Generic.List[string]]::new()
        Members = [System.Collections.Generic.Dictionary[string, System.Collections.Generic.List[string]]]::new([System.StringComparer]::Ordinal)
    }
}

# Parse a body into type blocks. Each block is its header line (plus that type's
# own `(obsolete)` marker, if it carries one) and its member entries, each entry
# being a token line plus that token's marker.
function ConvertFrom-MembersBody([string[]]$body, [string]$side) {
    $types = [System.Collections.Generic.Dictionary[string, hashtable]]::new([System.StringComparer]::Ordinal)
    $current = $null
    $lastToken = $null
    $lastBucket = $null

    foreach ($l in $body) {
        if ($l -eq '') { continue }

        $m = $script:TypeHeader.Match($l)

        if ($m.Success) {
            $name = $m.Groups['name'].Value
            if (-not $types.ContainsKey($name)) { $types[$name] = New-TypeBlock }
            $current = $types[$name]
            if (-not $current.Header.Contains($l)) { $current.Header.Add($l) }
            $lastToken = $l
            $lastBucket = $current.Header
            continue
        }

        if ($null -eq $current) {
            Exit-Conflict "the $side side has a body line before any type header: '$l'"
        }

        if ($null -ne $lastToken -and $l -ceq ($lastToken + $script:ObsoleteSuffix)) {
            if (-not $lastBucket.Contains($l)) { $lastBucket.Add($l) }
            continue
        }

        if (-not $current.Members.ContainsKey($l)) {
            $current.Members[$l] = [System.Collections.Generic.List[string]]::new()
            $current.Members[$l].Add($l)
        }

        $lastToken = $l
        $lastBucket = $current.Members[$l]
    }

    $types
}

# Union two parsed bodies. Both sides' additions survive; nothing is chosen
# between, because by the time this runs the removal check has established that
# neither side removed anything.
function Join-TypeBlocks($a, $b) {
    $out = [System.Collections.Generic.Dictionary[string, hashtable]]::new([System.StringComparer]::Ordinal)

    foreach ($src in @($a, $b)) {
        foreach ($name in $src.Keys) {
            if (-not $out.ContainsKey($name)) { $out[$name] = New-TypeBlock }
            $dst = $out[$name]

            foreach ($h in $src[$name].Header) { if (-not $dst.Header.Contains($h)) { $dst.Header.Add($h) } }

            foreach ($token in $src[$name].Members.Keys) {
                if (-not $dst.Members.ContainsKey($token)) {
                    $dst.Members[$token] = [System.Collections.Generic.List[string]]::new()
                }

                foreach ($line in $src[$name].Members[$token]) {
                    if (-not $dst.Members[$token].Contains($line)) { $dst.Members[$token].Add($line) }
                }
            }
        }
    }

    $out
}

# Re-emit in the generator's order: types by ordinal FullName, members by ordinal
# token, each marker immediately after what it marks.
function Write-TypeBlocks($types) {
    $out = [System.Collections.Generic.List[string]]::new()

    foreach ($name in (Sort-Ordinal @($types.Keys))) {
        foreach ($h in $types[$name].Header) { $out.Add($h) }

        foreach ($token in (Sort-Ordinal @($types[$name].Members.Keys))) {
            foreach ($line in $types[$name].Members[$token]) { $out.Add($line) }
        }
    }

    , [string[]]$out.ToArray()
}

function Invoke-MembersMerge() {
    $b = Split-Header (Read-LfLines $Base)
    $o = Split-Header (Read-LfLines $Ours)
    $t = Split-Header (Read-LfLines $Theirs)

    $header = Merge-Header $b.Header $o.Header $t.Header
    if ($null -eq $header) { Exit-Conflict 'both sides rewrote the generated header differently' }

    $oSet = [System.Collections.Generic.HashSet[string]]::new([string[]]$o.Body, [System.StringComparer]::Ordinal)
    $tSet = [System.Collections.Generic.HashSet[string]]::new([string[]]$t.Body, [System.StringComparer]::Ordinal)

    $removed = [System.Collections.Generic.List[string]]::new()

    foreach ($line in $b.Body) {
        if ($line -eq '') { continue }
        if (-not $oSet.Contains($line) -or -not $tSet.Contains($line)) { $removed.Add($line) }
    }

    if ($removed.Count -gt 0) {
        $sample = (($removed | Select-Object -First 5) -join '; ')
        $more = if ($removed.Count -gt 5) { " (and $($removed.Count - 5) more)" } else { '' }
        Exit-Conflict "$($removed.Count) member(s) present in the merge base are missing from one side — a removal is a BREAKING change and is never merged automatically: $sample$more"
    }

    $merged = Join-TypeBlocks (ConvertFrom-MembersBody $o.Body 'ours') (ConvertFrom-MembersBody $t.Body 'theirs')
    Write-LfFile $Ours (Join-Lines $header (Write-TypeBlocks $merged))
    exit 0
}

switch ($Mode) {
    'coverage' { Invoke-CoverageMerge }
    'members' { Invoke-MembersMerge }
}
